### ISSUE TITLE
sort things by source order

### ISSUE THREAD

**Issue by chadwhitacre** [mitmproxy/pdoc#103]
Pdoc [sorts](https://github.com/BurntSushi/pdoc/blob/bebf02b65636d5c5e03d8627381dd4cc75360549/pdoc/__init__.py#L774-L804) variables, classes, functions, and submodules alphabetically. I had expected it to respect the source code order.

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. This now is the default in the latest release. 😃

**Comment by chadwhitacre** [comment]
Huzzah! 💃

**Comment by abubelinha** [comment]
It is also possible to modify pdoc templates to let users sort/unsort the left index list of elements at any time.

Quite easy to implement by using a couple of top buttons and some javascript, with [tinysort.js](https://github.com/Sjeiti/TinySort/issues/125)

**Comment by marcomusy** [comment]
I would love to have them sorted alphabetically in [my project](https://vedo.embl.es/docs/vedo.html).. how should I do it?

**Comment by mhils** [comment]
The best approach is to also sort them alphabetically in your source code (if that's the best way to structure your package, it's also the best was to structure your sources?).

Alternatively you can modify the Jinja2 template and add some sorting there. If you play around a bit with the template you should be able to figure out how to do that.

**Comment by marcomusy** [comment]
Thanks - looks great now.. btw is there a simple way to get rid of the smooth scrolling?

**Comment by marcomusy** [comment]
PS: I still get a link to pdoc3 for some reasons at the bottom of the page, I would like to remove it.

```
These documentation pages are automatically generated by [pdoc](https://pdoc3.github.io/pdoc/) from the source files.
```

**Comment by mhils** [comment]
> Thanks - looks great now.. btw is there a simple way to get rid of the smooth scrolling?

```css
html, main {
    scroll-behavior: auto !important;
}
```

in a `custom.css` in your [custom template directory](https://pdoc.dev/docs/pdoc.html#edit-pdocs-html-template).


> PS: I still get a link to pdoc3 for some reasons at the bottom of the page, I would like to remove it.
> 
> ```
> These documentation pages are automatically generated by [pdoc](https://pdoc3.github.io/pdoc/) from the source files.
> ```

This means you are using pdoc3 and not pdoc, which is an entirely different project that assumes our name. See https://github.com/mitmproxy/pdoc#pdoc-vs-pdoc3. `pip uninstall pdoc3 && pip install pdoc` should fix it.

**Comment by marcomusy** [comment]
that's weird ... it's not even installed:
`pip uninstall pdoc3`
> WARNING: Skipping pdoc3 as it is not installed.

**Comment by mhils** [comment]
Somewhere on your system you seem to have a pdoc3 installation. pdoc itself will surely not add a link that points to pdoc3.

**Comment by marcomusy** [comment]
Oh yes - I didn't realize that I had a link in one include (i moved away from pdoc3).
sorry for the confusion.

**Comment by JLZ22** [comment]
> Thanks - looks great now.. btw is there a simple way to get rid of the smooth scrolling?

I haven't been able to figure out how to alphabetically sort my functions. Could you explain how you got it done?
