### ISSUE TITLE
AsciiDoc support

### ISSUE THREAD

**Issue by machacekondra** [mitmproxy/pdoc#108]
Hello,

we are using asciidoc format in our python documentation.
It would be nice if pdoc could support asciidoc in addition to markdown.

If we will post a patch adding this support, would you consider merging it?

Thanks,
Ondra

**Comment by machacekondra** [comment]
@BurntSushi

**Comment by BurntSushi** [comment]
I'd rather stick with one format for writing docs. The actual markdown integration is pretty light weight, so you should be able to modify just the templates to use a different format.

**Comment by peterjc** [comment]
Cross reference #111 for multiple input formats including RST, and #35 (epydoc input).

**Comment by cortesi** [comment]
Please see #153 for a unified discussion ticket about docstring flavors.
