### ISSUE TITLE
 __docformat__ reStructuredText/rst etc input as well as Markdown

### ISSUE THREAD

**Issue by peterjc** [mitmproxy/pdoc#111]
According to the README,

> It is intended that pdoc will be a replacement for the unmaintained epydoc.

epydoc defaults to its own simple epytext markup but supports additional markup languages, reStructuredText, Javadoc and plaintext:

http://epydoc.sourceforge.net/epydoc.html#alternate-markup-languages

They specifically recommend using reStructuredText if epytext is not expressive enough:

> Epytext is intentionally very lightweight. If you wish to use a more expressive markup language, I recommend reStructuredText.

http://epydoc.sourceforge.net/epydoc.html#the-epytext-markup-language

I am surprised to see that currently pdoc appears to assume the docstrings are written using Markdown notation (which is _not_ supported by epydoc).

Would you consider supporting other markup languages (I would particularly like to use reStructuredText aka rst) as indicated by the `__docformat__` attribute support and/or a command line switch as in epydoc?

e.g.

``` python
__docformat__ = "restructuredtext en"
```

or,

``` python
__docformat__ = "plaintext en"
```

or

``` python
__docformat__ = "epytext"
```

**Comment by automaticgiant** [comment]
I'd support this solely based on the ability to then use `pdoc --http` to view the 'canonical' doc format (that of the standard library, and whatever copies its format of choice).

**Comment by cortesi** [comment]
Hi there! We've decided that support for markup format beyond markdown is not a goal at this point. We feel this is the best way for pdoc to remain a small, clear, predictable tool.

**Comment by cortesi** [comment]
Please see #153 for a unified discussion ticket about docstring flavors.
