### ISSUE TITLE
Default HTML output line wraps source code

### ISSUE THREAD

**Issue by peterjc** [mitmproxy/pdoc#112]
I can reproduce this locally, but also:
1. Browse to http://pdoc.burntsushi.net/pdoc
2. Scroll to the first yellow "SHOW SOURCE" button
3. Click "SHOW SOURCE"
4. Look at the displayed code

In both Safari and Chrome I see  this where I have marked the line breaks with `*`

```
"""
Module pdoc provides types and functions for accessing the public *
documentation of a Python module. This includes modules (and *
sub-modules), functions, classes and module, class and instance *
variables.  Docstrings are taken from modules, functions and *
classes *
using the special `__doc__` attribute. Docstrings for variables are *
extracted by examining the module's abstract syntax tree. *

The public interface of a module is determined through one of two *
ways. If `__all__` is defined in the module, then all identifiers *
in *
that list will be considered public. No other identifiers will be *
considered as public. Conversely, if `__all__` is not defined, then *
`pdoc` will heuristically determine the public interface. There are *
three rules that are applied to each identifier in the module: *
...
```

Notice `classes` and `in` have been wrapped to the next line. These lines were only 68 characters:

```
>>> len("variables.  Docstrings are taken from modules, functions and classes")
68
>>> len("ways. If `__all__` is defined in the module, then all identifiers in")
68
```

In view of the current PEP8 guidelines https://www.python.org/dev/peps/pep-0008/#maximum-line-length the default output from pdoc should ideally show lines of up to 79 characters without line wrapping.

Also, perhaps the source blocks should automatically use horizontal scrolling if required rather than line wrapping?

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. This should be fixed with the latest release. 😃
