### ISSUE TITLE
Make pdoc work also for the most recent versions of Python 3.4, 3.5?

### ISSUE THREAD

**Issue by nbro** [mitmproxy/pdoc#116]
Hi,

I noticed that `pdoc` throws me an error if I don't have the `__init__.py` files under the folders to indicate that they are packages. Then I noticed also that in the README you say that `pdoc` has been tested with Python 3.3, but you don't mention anything regarding the last versions of Python. 

Are you willing to make pdoc work also for these last versions of Python so that I don't need to insert the `__init__.py` files under each folder to make `pdoc` recognise those folders as packages?

Thanks!

**Comment by cortesi** [comment]
Pdoc now targets Python 3.6 and up. Recent versions of Python still require an `__init__.py` file to treat directories as modules.
