### ISSUE TITLE
Publish as Wheel on PyPI

### ISSUE THREAD

**Issue by noelleleigh** [mitmproxy/pdoc#118]
Currently, pdoc lives on PyPI as a .tar.gz. Having a Wheel version allows those of use to use it even if the corporate firewall blocks tars.

**Comment by BurntSushi** [comment]
Could you outline the steps required to do this please?

**Comment by noahleigh** [comment]
The official packaging instructions are here: https://packaging.python.org/distributing/#wheels

There might be some additional metadata that might need to be set, but I'm not sure.
