### ISSUE TITLE
Add possibility to navigate in a more flexible way through the documentation 

### ISSUE THREAD

**Issue by nbro** [mitmproxy/pdoc#126]
So far, from what I understood, we can just go forward by clicking on the sub-modules or sub-packages' names on the left side panel, but we can't go back to parent modules or packages:

<img width="1104" alt="screen shot 2017-02-19 at 18 42 53" src="https://cloud.githubusercontent.com/assets/9349000/23104706/529d89a6-f6d3-11e6-8c5c-312f4099a096.png">

unless we click to go back in the browser.

It would be nice to have a more flexible way of navigating through the documentation.

**Comment by cudmore** [comment]
I agree. Maybe the left menu pane (index in the above example image) could provide constant links to all sub-modules? Otherwise, all is good.

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. This should be fixed with the latest release. 😃
