### ISSUE TITLE
Incorrect class names in html

### ISSUE THREAD

**Issue by boompig** [mitmproxy/pdoc#131]
Command run:

```
pdoc --html fastavro
```

(you can find `fastavro` module on pip)

Classes listed in sidebar:
![screen shot 2017-04-27 at 1 22 43 pm](https://cloud.githubusercontent.com/assets/2791268/25502712/9e0bd962-2b4c-11e7-8232-0c9152146565.png)

Note that the classes here are not consistent with those shown below (reader appears twice).

Classes listed in the body of the document:

![screen shot 2017-04-27 at 1 23 15 pm](https://cloud.githubusercontent.com/assets/2791268/25502729/b181b4da-2b4c-11e7-9f7a-98b1c72f2235.png)

As a separate issue, I don't think `class reader` is a valid class at all. It looks duplicated from `class iter_avro`.

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. This should be fixed with the latest release. 😃
