### ISSUE TITLE
generated submodule doc incomplete

### ISSUE THREAD

**Issue by kundeng** [mitmproxy/pdoc#141]
anybody actively maintaining this?

I tried this thing on splunk package included in a standard splunk enterprise install,  and noticed issues:

1. doesn't handle unicode well.  It errors out in the middle of generating html. 

2.  After fixing 1,  it still won't generate docs for modules inside a submodule.

**Comment by BurntSushi** [comment]
I don't know what splunk is. Please provide a reproducible example.

**Comment by kernc** [comment]
https://github.com/BurntSushi/pdoc/pull/145 (one line fix) generally fixes the issue with encoding.
