### ISSUE TITLE
pdoc.burntsushi.net is down

### ISSUE THREAD

**Issue by boyangwang** [mitmproxy/pdoc#142]
![image](https://user-images.githubusercontent.com/2408273/36018406-9c6a20d0-0db6-11e8-920f-9892747180f2.png)

**Comment by cdbennett** [comment]
In case it's helpful, here's a link to [the last snapshot on archive.org from 2017-09-08](https://web.archive.org/web/20170908232354/http://pdoc.burntsushi.net/pdoc).

**Comment by mhils** [comment]
pdoc has a new home now: https://pdoc.dev 🥳
