### ISSUE TITLE
Hide source code option

### ISSUE THREAD

**Issue by sangramga** [mitmproxy/pdoc#144]
Does pdoc have a hide source code option? It would be a nice feature to have. i did not find it in Docs.

**Comment by mhils** [comment]
With the latest pdoc release, you can hide the source code by overriding the `view_source` macro:

`template-directory/module.html.jinja2`:
```jinja2
{% extends "default/module.html.jinja2" %}
{% macro view_source(obj) %}{% endmacro %}
```

and then `pdoc -t template-directory ...`

**Comment by Stephane-Ag** [comment]
This can now be done with `--no-show-source` without needing to overwrite the macro.

```
pdoc --no-show-source ...
```
