### ISSUE TITLE
Can I only document the module itself?

### ISSUE THREAD

**Issue by marksweiss** [mitmproxy/pdoc#15]
I am very happy to find pdoc! I looked at other choices and they were heavy and poorly documented. So excellent to find something that works right away and is easy to manipulate.

That said, I have spent a few hours with the code but haven't quite figured out how to restrict the scope of documentation to just the contents of the module. I want to be able to only document:
- module scope variables
- module scope functions
- classes in a module
- methods in a class in a module
- instance variables in a class in a module

A standard use case for this that I imagine isn't just mine is for unit tests. Including in the documentation all the methods inherited from UnitTest does not add useful information.

I think this applies generally for any situation where you want the documentation to only focus on the module source, rather than being comprehensive about all the context of that module. In my case, I am documenting an intentionally minimal library and a very strong design goal is keeping every aspect of it as brief and simple as possible.

I will happily provide a pull request if necessary to implement this.

Thanks!

**Comment by mriehl** [comment]
Personally I don't think that *completely* disabling inherited attributes would be workable.
If you want to hide *all* functionality provided by the superclass, then why use inheritance at all (instead of composition)?

I have a use case where the parent class is bloated with private methods but has a few methods I would like to expose. So I'm much more in favour of a whitelist/blacklist.

For example some kind of `__all__` at the class level, e.G.

```
class Dog(Animal):
    __all__ = ["bark", "eat", "sleep"]
```

I thought about a decorator too but that would make it that much more difficult to document parent class behaviour.

**Comment by marksweiss** [comment]
Sorry I never saw your response from last August. 

Do you still want a pull request? It should be simple unless there are many subsequent changes to merge in, as I'm working from a fork that is just this diff I needed to get this to work. @mriehl @BurntSushi I'm all for a more flexible approach, so again let me know if you want a pull request for my broader change.

Thanks!

**Comment by BurntSushi** [comment]
@marksweiss I think I like @mriehl's suggested approach better. Reusing the concept of `__all__` is really nice IMO. :-) Thank you though!

**Comment by Leockard** [comment]
Hi, I tried using this solution found in #25 (which was closed in favor of this):
```
class MyCmd(Cmd):
    for field in Cmd.__dict__.keys():
        __pdoc__['MyCmd.%s' % field] = None
```
But didn't work. After this code, for some reason, __pdoc__ has only a few keys set to None (__module__, __init__, __doc__, etc). I also tried to use 

```
    for field in dir(Cmd):
        ...
```
In which case __pdoc__ IS full of the methods that I want to ignore, but they are still being documented.

Thanks.

**Comment by BurntSushi** [comment]
@Leockard Can you produce a minimal test case? It seems to be working fine over here:

```python
class A(object):
    afoo = 1
    def abaz(self):
        pass


class B(A):
    bfoo = 1
    def bbaz(self):
        pass
```

Then:

```
[andrew@Liger pdoc] pdoc 15.py
Module 15
---------

Classes
-------
A 
    Ancestors (in MRO)
    ------------------
    15.A
    __builtin__.object

    Descendents
    -----------
    15.B

    Class variables
    ---------------
    afoo

    Methods
    -------
    abaz(self)

B 
    Ancestors (in MRO)
    ------------------
    15.B
    15.A
    __builtin__.object

    Class variables
    ---------------
    afoo

    bfoo

    Methods
    -------
    abaz(self)

    bbaz(self)
```

Now applying the `__pdoc__` trick:

```python
__pdoc__ = {}

class A(object):
    afoo = 1
    def abaz(self):
        pass


class B(A):
    __pdoc__['B.k'] = None
    for k in A.__dict__:
        __pdoc__['B.%s' % k] = None

    bfoo = 1
    def bbaz(self):
        pass
```

And the `a` methods no longer show up for `B`:

```
[andrew@Liger pdoc] pdoc 15.py
Module 15
---------

Classes
-------
A 
    Ancestors (in MRO)
    ------------------
    15.A
    __builtin__.object

    Descendents
    -----------
    15.B

    Class variables
    ---------------
    afoo

    Methods
    -------
    abaz(self)

B 
    Ancestors (in MRO)
    ------------------
    15.B
    15.A
    __builtin__.object

    Class variables
    ---------------
    bfoo

    Methods
    -------
    bbaz(self)
```

**Comment by Leockard** [comment]
OK, first, I thought the ```__pdoc__``` variable was a class member, and didn't notice it was supposed to be a module-global variable. I got it to work now, BUT, see below.

I'm using wxpython for my application. Here's the test code:
```
import wx

__pdoc__ = {}

class Test(wx.Frame):
    for k in wx.Frame.__dict__.keys():
        __pdoc__['Test.%s' % k] = None

    def method(self, arg1):
        """method doc"""
        pass
```

And the output:

```
leo@lily:~$ pdoc test.py | tail -n15

    WindowToClientSize(*args, **kwargs)
        WindowToClientSize(self, Size size) -> Size

        Converts window size ``size`` to corresponding client area size. In
        other words, the returned value is what `GetClientSize` would return
        if this window had given window size. Components with
        ``wxDefaultCoord`` (-1) value are left unchanged.

        Note that the conversion is not always exact, it assumes that
        non-client area doesn't change and so doesn't take into account things
        like menu bar (un)wrapping or (dis)appearance of the scrollbars.

    method(self, arg1)
        method doc
```

Clearly, WindowToClientSize comes from wx.Frame.

I have also tried 
```
for k in wx.Frame.__dict__:
        __pdoc__['Test.%s' % k] = None
```
per your suggestion, but I get the same output.

I finally got it to work by using:

```
for k in dir(wx.Frame):
        __pdoc__['Test.%s' % k] = None
```

Which outputs:
```
leo@lily:~$ pdoc test.py | tail -n15
    wx._windows.Frame
    wx._windows.TopLevelWindow
    wx._core.Window
    wx._core.EvtHandler
    wx._core.Object
    __builtin__.object

    Class variables
    ---------------
    k

    Methods
    -------
    method(self, arg1)
        method doc
```

**Comment by BurntSushi** [comment]
@Leockard Ah, great! So `dir` is the trick. It must be including something that isn't covered in `__dict__`. Neat. I'll suggest that from now on. Thanks for reporting back! :-)

**Comment by Leockard** [comment]
OK, by looking at it more closely, it looks like ```wx.Frame.__dict__``` only contains the methods from wx.Frame proper, while ```dir(wx.Frame)``` is returning the list of all its members, _including the ones from its ancestors_.
Of course, I wanted to ignore all the methods coming from wx, so I wanted the latter one.

**Comment by Leockard** [comment]
Well, setting everything in dir(base_class) to None didn't work either. For example, 
```
__pdoc__ = {}

class Base():
    def override_method(self, arg1):
        """base method doc"""
        pass

class Child(Base):
    __pdoc__["Child.k"] = None
    for k in dir(Base):
        __pdoc__['Child.%s' % k] = None

    def override_method(self, arg1):
        """overriden method doc"""
        pass
```

Output:
```
leo@lily:~$ pdoc test.py
Module test
-----------

Classes
-------
Base 
    Ancestors (in MRO)
    ------------------
    test.Base

    Methods
    -------
    override_method(self, arg1)
        base method doc

Child 
    Ancestors (in MRO)
    ------------------
    test.Child
    test.Base
```

Of course, since we are setting ```__pdoc__[Base.override_method] = None```, the Child.override_method doesn't get documented either.

My workaround for now is to write something like this at the end of the file:
```
# pdoc setup
__pdoc__ = {}
for k in dir(Base):
    __pdoc__['Child.%s' % k] = None
for k in Child.__dict__.keys():
    del __pdoc__['Child.%s' % k]
```

While I think this is still concise enough, I think this solution is approaching dangerous levels...

**Comment by dakov** [comment]
Is this really the only way to accomplish that? Don't you think it's a lot of overhead in cases with dozens of classes?

For example, we want to generate a documentation for people who know very little programming. Therefore, we prepared many wrapper classes and methods for them to work with. So what I would need is to whitelist methods and attributes which will be reflected in the documentation, instead of black-listing those which will not. 

I'm a fan of the `__all__` approach, but I guess it's still not possible?

**Comment by mhils** [comment]
Hi there!

The latest pdoc release now detects and classifies inherited members. The recommended way to accomplish what OP wants is to extend the default template to hide inherited members:

```jinja2
{% extends "default/module.html.jinja2" %}
{% block inherited_members scoped %}{% endblock %}
```

**Comment by object-Object** [comment]
Here's a simpler method:
```jinja
{% extends "default/module.html.jinja2" %}
{% macro inherited(cls) %}{% endmacro %}
```
