### ISSUE TITLE
changelog not updated for 0.3.2

### ISSUE THREAD

**Issue by sjpb** [mitmproxy/pdoc#160]
The latest version of pydoc (on pypi) seems to be 0.3.2 - I went hunting for what changes that introduced and only found the CHANGELOG file in the github repo, which doesn't include 0.3.2.

**Comment by mhils** [comment]
Looking at https://github.com/mitmproxy/pdoc/commits/0.3.2, it seems like 0.3.2 is a bugfix-only release from two years ago. We'll definitely keep the changelog updated for further releases.

**Comment by mhils** [comment]
Quick Update: This should be fixed with the latest release. 😃
