### ISSUE TITLE
Was support for Python < 3.6 intentionally dropped?

### ISSUE THREAD

**Issue by ecederstrand** [mitmproxy/pdoc#164]
https://github.com/mitmproxy/pdoc/commit/b22f9884940f7eabf2ebe19e6874b8c030fef8f5#diff-6e25b76e2e8ac358872ad54a4fd44420 introduced f-strings which were introduced in Python 3.6. But `setup.py` just advertises that `pdoc` supports Python 3.*:

https://github.com/mitmproxy/pdoc/blob/d27d9839b05cbf541336f83f832f7fc5e1495fb6/setup.py#L34

Dropping Python 3.5 already is maybe a bit harsh, but at least setup.py should be updated to note the change.

**Comment by ecederstrand** [comment]
I have created a PR to restore Python 3.5 support. The changes are minimal.

**Comment by mitsuhiko** [comment]
Did that also drop 2.7 support or was that dropped earlier? Because on Python 3 all methods are misreported as static methods which is why I'm currently forced to use Python 2.7 and I noticed master does not work with it.

**Comment by mhils** [comment]
2.7 was dropped earlier, see https://github.com/mitmproxy/pdoc/issues/148. 

3.5 is definitely something we want to support for now, I'll take a look at @ecederstrand's excellent PR in a minute.

**Comment by mitsuhiko** [comment]
@mhils then the extractor needs to be fixed. It reports all methods as static methods (https://github.com/mitmproxy/pdoc/issues/48)
