### ISSUE TITLE
pdoc master does not understand --html-out (makes weird folders)

### ISSUE THREAD

**Issue by mitsuhiko** [mitmproxy/pdoc#169]
Somewhere something regressed recently. When I invoke it like this:

```
pdoc --overwrite --html --html-dir build/apidocs sentry_sdk
```

It does not create a folder named `build/apidocs` but instead one `Namespace(all_submodules=False, external_links=False, filter=None, html=True, html_dir='build`:

```
$ ls -alh | grep Name
drwxr-xr-x   3 mitsuhiko  staff    96B Sep  7 23:18 Namespace(all_submodules=False, external_links=False, filter=None, html=True, html_dir='build
```

**Comment by mhils** [comment]
Thanks for reporting - this has been fixed with #159. We're still a bit in a transitional state where things a broken, but we're getting there.
