### ISSUE TITLE
pdoc now reports submodules in __all__ as variables

### ISSUE THREAD

**Issue by mitsuhiko** [mitmproxy/pdoc#171]
With the last release version a submodule mentioned in `__all__` would be reported as a module. Now it's reported as variable as well as a module but the links are broken.

`integrations` here is a module in fact (mentioned in `__all__`):

<img width="165" alt="screen shot 2018-09-07 at 23 23 32" src="https://user-images.githubusercontent.com/7396/45243667-0ecf5300-b2f5-11e8-80c2-510c18d8fdba.png">

In the selector below the module in `__all__` has a different name than others (and the link is broken):

<img width="247" alt="screen shot 2018-09-07 at 23 23 30" src="https://user-images.githubusercontent.com/7396/45243693-23135000-b2f5-11e8-9d6d-b82169286908.png">

This change is likely related to #170

**Comment by mhils** [comment]
Hi @mitsuhiko, thanks for reporting this and sorry for the slow turnaround time. I've just released a new pdoc release where this should be fixed. :)

On another note, I noticed [your tweet on Python doc tools](https://twitter.com/mitsuhiko/status/1333154662506229771) a few weeks ago. We've just breathed quite a bit of new fresh air into pdoc - if you happen to switch doc tools the next time please let me know how if we can help you out in any way. :smiley:
