### ISSUE TITLE
Pythonhosted/ReadTheDocs and the future of Pdoc

### ISSUE THREAD

**Issue by karimbahgat** [mitmproxy/pdoc#173]
I'm a big fan of the simplicity of Pdoc and have up to now used it for my projects. However, this was always reliant on being able to upload the custom HTML output to pythonhosted.org. But now it seems pythonhosted.org is being deprecated in favor of ReadTheDocs (not allowed to manually upload new docs on the website, and distutils upload_docs no longer allowed and suggests switching to RTD). 

Not knowing any other doc hosting services I started looking into ReadTheDocs, but it seems they only allow either Sphinx documentation or MkDocs documentation (which so far doesn't seem to have any auto construction of API docstrings). 

What does this mean for the future of pdoc? Am I understanding this right? Or is there a way around it where ReadTheDocs would accept the custom HTML created by pdoc? Or maybe any other doc hosting websites?

**Comment by kernc** [comment]
> Or maybe any other doc hosting websites?

One could host your project website and docs on [GitHub Pages](https://pages.github.com/) like many other projects do.

**Comment by karimbahgat** [comment]
Thanks. Just realized that too. Just had to place the output files into a «docs» folder and specify that location in the repository settings. Works great.

**Comment by HananInfiniGrow** [comment]
How can I make pdoc output look like readthedocs template?

I hate mkdocs and sphinx. They just don't work out of the box. pdoc is the only tool without zillion of setup steps and solving import errors
