### ISSUE TITLE
Executing code

### ISSUE THREAD

**Issue by r2ad** [mitmproxy/pdoc#181]
Curious as to why pdoc also executes the code.  For example, create a simple hello.py and run pdoc on it.  The Hello World is executed.  I was not expecting this behaviour when running pdoc on files in a directory and it could result in code running when it is not desired.

Of course, it works as expected (great) on modules. :)

**Comment by kernc** [comment]
It imports the modules instead of merely parsing them.

**Comment by BurntSushi** [comment]
See also: https://github.com/mitmproxy/pdoc/issues/82 and https://github.com/mitmproxy/pdoc/issues/8

**Comment by mhils** [comment]
Thanks for chiming in you two! :)
