### ISSUE TITLE
Local HTTP server not updating

### ISSUE THREAD

**Issue by MaxHalford** [mitmproxy/pdoc#183]
Hello,

First of all thank you for writing and maintaining `pdoc`, I really like it.

When I'm working on my docs locally I don't see the changes I make reflected on the local HTTP server. Even when I shut the server down and boot it back up. Is there anything special that has be done?

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. Nonetheless, this should be fixed with the latest release. 😃
