### ISSUE TITLE
pydoc expands os.environ dictionary -> security issue

### ISSUE THREAD

**Issue by osynge** [mitmproxy/pdoc#185]
We had a function that pydoc documented:

    def cfg_get_env(env=os.environ):

Except 'pydoc' did not document 'env=os.environ' but expanded the content of 'os.environ' which is a security issue.

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. Nonetheless, this should be fixed with the latest release. 😃
