### ISSUE TITLE
`s.kwonlydefaults` can be None

### ISSUE THREAD

**Issue by gsmcwhirter** [mitmproxy/pdoc#188]
At https://github.com/mitmproxy/pdoc/blob/69ce6240df227b50c799073587d6358c368788a9/pdoc/doc.py#L719, the value of `s.kwonlydefaults` can apparently be `None` in the case where there are keyword-only args, and none of those keyword-only args have defaults (e.g., `def foo(arg1, *, arg2, arg3)`. This raises a `TypeError`, not a `KeyError`. Perhaps it is worth adding the `TypeError` to the except clause?

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. Nonetheless, this should be fixed with the latest release. 😃
