### ISSUE TITLE
Support comment docstrings for variables

### ISSUE THREAD

**Issue by plinss** [mitmproxy/pdoc#195]
Both Sphinx and epydoc allow docstrings on variables by using a `#:` comment after the variable on the same line, or on the preceding line, e.g.:

```
def __init__(self):
    self.one = 1  #: Docstring for one.
    #: List[int]: Docstring for two with type info
    self.two = [2]
```

Adding support for those would made switching to pdoc easier.

**Comment by mhils** [comment]
pdoc does support variable docstrings like this:
```
one: int = 1
"""docstring for one"""
```

For more details please see https://pdoc.dev/docs/pdoc.html#document-variables. 

Python's builtin [ast](https://docs.python.org/3/library/ast.html) module does not carry over comments, so supporting that would introduce more complexity than what it's worth. Sorry!
