### ISSUE TITLE
Windows Powershell

### ISSUE THREAD

**Issue by suidobashi** [mitmproxy/pdoc#20]
Installed using pip to a Windows 8.1 Powershell environment.

Was unable to run the pdoc script as a shebang script. (Powershell requires a filename extension to make the script executable.)

Workaround was to run directly from the python interpreter.

**Comment by BurntSushi** [comment]
Does anyone know how to fix this? I don't use Windows. What if I use a CLI hook in `setup.py`?

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. This should be fixed with the latest release. 😃
