### ISSUE TITLE
Magic method are not documented

### ISSUE THREAD

**Issue by pprados** [mitmproxy/pdoc#204]
#### Problem Description
With a class with magic method (__get__(), __contains__(), ...), the documentation are not generated.
I try to add these methods in __doc__
  ```
  __pdoc__ = {
      "grid.Grid.__get__": True,
```

Without result
#### Steps to reproduce the behavior:
1. Create a class with magic method and docstring
2. generate the doc

#### System Information
pdoc 0.9.2

**Comment by mhils** [comment]
Hi @pprados,

It looks like you have installed pdoc3, not pdoc (see [pdoc3 vs. pdoc3](https://github.com/mitmproxy/pdoc#pdoc-vs-pdoc3)). You may want to run `pip uninstall pdoc3` and then `pip install pdoc`.

We generally discourage documenting individual `__dunder__` methods. Have you considered giving some examples in your class docstring instead? I often feel that's much more useful for your readers.

If you definitely want to document your `__dunder__` methods, you can use a custom template with pdoc 2.0. Here's the relevant part in the documentation: https://pdoc.dev/docs/pdoc.html#control-what-is-documented

**Comment by pprados** [comment]
pdoc3 is not installed.

```
pip uninstall pdoc3
WARNING: Skipping pdoc3 as it is not installed.
```
But thanks. I will try to use the template.

**Comment by mhils** [comment]
To clarify, there never was a pdoc 0.9.x release. Just make sure that you get 2.0 or above when running it :)
