### ISSUE TITLE
Inline/link 'imported members'

### ISSUE THREAD

**Issue by brenthuisman** [mitmproxy/pdoc#208]
I have a package that has an `__init__.py` which does no more than a `from _package import *`. The classes and methods defined there are not shown in the packages docs. I do see a (complete) page is generated for `_package`, but it's not linked anywhere.

In Sphinx's autodoc, inlining is achieved with the `imported-members` option. It would be nice to have something similar.

**Comment by mhils** [comment]
So my general recommendation would be to declare `__all__` in your `__init__.py`, which should work fine already.

Then again I think the overall use case is reasonable. You can already [control what is documented](https://pdoc.dev/docs/pdoc.html#control-what-is-documented), but imported members are filtered out before. Let's see if we can fix this easily!

**Comment by mhils** [comment]
Hey there! I fiddled with this quite a bit today, but with no satisfying results. Implementing something alike `imported-members` incurs a bit too much complexity for what it's worth, so I'll keep it out of pdoc. Sorry!

If you want to document imported members, there are two approaches:

1. **Recommended:** Manually define `__all__` in your module.
2. If you really do not want to maintain `__all__`, you can also populate it automatically:

    ```python
    __all__ = [x for x in locals() if not x.startswith("_")]
    ```
