### ISSUE TITLE
Problem in first example

### ISSUE THREAD

**Issue by vpoulailleau** [mitmproxy/pdoc#209]
#### Problem Description

Typo in first example in the website

#### Steps to reproduce the behavior:
1. Go to https://pdoc.dev/
2. Read docstring: """🐕🐕‍🦺🦮"""
3. See generated documentation: not the same (when I copy to the clipboard, it's ok, but not when I read the doc with firefox, as seen on the screenshot below)

![Capture du 2021-01-26 06-40-27](https://user-images.githubusercontent.com/17438768/105805108-9b037300-5fa1-11eb-8cf4-b8467a1ffaca.png)

I assume this is just a problem of handling unicode composition. If I look at the HTML source code (with firefox) then it's correctly displayed!

I suggest not to use unicode composition, but only "simple" emojis.

BTW, thanks for what you've done.

#### System Information

* Website as of today
* Firefox 79

**Comment by mhils** [comment]
That is for the heads-up! I'll double-check the HTML output, but this is likely because the service dog emoji is a relatively recent Unicode addition. Does it render properly for you on https://emojipedia.org/service-dog/? 😃

**Comment by vpoulailleau** [comment]
No, it doesn't render properly on  emojipedia.org/service-dog. I checked with brave browser (Version 1.12.112 Chromium: 84.0.4147.125 (Build officiel) (64 bits)), it's worse, it displays two squares instead of the emoji.

**Comment by mhils** [comment]
Ok, let's keep this simple. Fixed, thank! 🍰
