### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Arkelis** [mitmproxy/pdoc#210]
It would be cool if we had a dark theme toggle button, and even better if dark/bright color scheme preference was detected automatically. I might work on this if I have some time.

Congrats for getting the project back on track!

**Comment by mhils** [comment]
Thanks for the kind words! I agree this would be cool, but it also introduces additional complexity I'm not really in favor of.
I'd maybe consider merging a PR that adds *isolated and minimal* dark mode styling based on `prefers-color-scheme`, but that depends on the actual amount of changes required. We definitely won't add an additional button or command line flag for this. 
If a fancier dark mode implementation is super important to you, please feel free to fork and and leave a link to your fork here. It's just that I want to keep pdoc itself simple and lightweight. :)

**Comment by Arkelis** [comment]
I've began to work on this, I can handle color changes with `prefers-color-scheme` media query. The problems come with code highlighting: Pygments does not generate a CSS with color variables, so to have a dark theme scheme, it is needed to have two CSS definitions generated by Pygments. The solutions that I can think of:

- Provide a dark theme by default for code highlighting, so it is suitable for both bright and dark themes. (The simplest)
- Provide a hard coded CSS file for code highlighting just like Bootstrap Reboot instead of creating it with Pygments in the source code: the theme then cannot be easily overwritten without regenerating another CSS files manually with Pygments. But currently we must modify `pdoc`'s source code to change the style of the formatter, using external CSS may be a bit more flexible when using custom templates. (Demands manual usage of Pygments but more flexible)
- Declare two formatters in `pdoc`'s source code and modify the `{% block style_pygments %}` block or the `{{ pygments_css }}` tag. (Simple, but not isolated as you wish)

**Comment by mhils** [comment]
Thanks @Arkelis! 😃 

Option 2 sounds best to me, this is also similar to what [Hugo is doing](https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css) for example. 
Let's add a `syntax-highlighting.css` file and include that instead of `formatter.get_style_defs()`. We can add a short comment in that file explaining how to invoke pygments. I might even be tempted to make the `github` style from https://xyproto.github.io/splash/docs/all.html our light theme default. 😋

**Comment by mhils** [comment]
Fixed in #217!

**Comment by Aran-Fey** [comment]
I'm confused about the status of this feature. Despite the issue being closed, there is [no mention of a dark mode in the documentation whatsoever](https://pdoc.dev/docs/pdoc.html?search=dark). How do I enable dark mode? Is it built in or do I have to download a template from somewhere? Please update the documentation.

**Comment by mhils** [comment]
A dark mode example is available at https://github.com/mitmproxy/pdoc/tree/main/examples/dark-mode. That being said, it's not an officially supported feature.
