### ISSUE TITLE
UML Diagrams

### ISSUE THREAD

**Issue by aviralg** [mitmproxy/pdoc#22]
Do you have any plans to integrate UML diagram generation. I find it really useful to view the entire class hierarchy visually.

**Comment by BurntSushi** [comment]
Not particularly. It seems like an orthogonal concept to an auto documentation tool.

If there exists a simple addition to `pdoc` that adds useful UML support, then I'd definitely consider it. In this context, "simple" refers both to implementation and usability. I'm kind of skeptical that such a thing exists, but I'm not sure.

**Comment by cortesi** [comment]
Please see #153 for a unified discussion ticket about docstring flavors.
