### ISSUE TITLE
pdoc is removing underlines from examples

### ISSUE THREAD

**Issue by rodrigomologni** [mitmproxy/pdoc#220]
#### Problem Description

`pdoc` is removing underlines from examples in docstring...

![image](https://user-images.githubusercontent.com/1608652/107810732-e365b380-6d4b-11eb-8fd3-df8c71080949.png)

![image](https://user-images.githubusercontent.com/1608652/107810639-c630e500-6d4b-11eb-8f42-38a185f0204e.png)

#### Steps to reproduce the behavior:

`python -m pdoc --docformat numpy -o docs cpgrid`

#### System Information

```
pdoc: 6.1.0
Python: 3.8.7
Platform: Windows-10-10.0.18362-SP0
```

**Comment by mhils** [comment]
This for the clean repro, definitely a bug. :)

**Comment by mhils** [comment]
Fixed in 341c2f, release should be out in ~10 mins. Thanks again! :)

**Comment by rodrigomologni** [comment]
Hi @mhils!

Bug fixed! Thank you! :clap:

![image](https://user-images.githubusercontent.com/1608652/107818089-d2ba3b00-6d55-11eb-938f-09cc7db7b4d4.png)

I realized that links to class methods were created in the examples. I don't know if it's a bug or intentional.

**Comment by mhils** [comment]
That's another interesting corner case, thanks :) We just link all identifiers in a comment, which I guess is somewhat reasonable. That being said, I agree that this looks relatively ugly. I guess we could change the color to black!

**Comment by rodrigomologni** [comment]
I find the links useful. The "problem" is that links were created only to class methods. Links to module methods weren't created.

![image](https://user-images.githubusercontent.com/1608652/107820454-94bf1600-6d59-11eb-8050-e796f3ef5344.png)

**Comment by mhils** [comment]
Ah, I see. This is nothing we can fix easily I believe. At the moment, we essentially run a heuristic that takes every identifier with a dot in it, check if it exists, and link it if it does. We can't extend that heuristic to plain words, which would cause too many false positives.

The only alternative I see is parsing and understanding code examples, which is incredibly complex and out of scope for pdoc.

**Comment by rodrigomologni** [comment]
So... painting the links black is a good choice! :sweat_smile:
Thank you! Congratulations on reactivating the project! :clap:

**Comment by mhils** [comment]
Thanks! After digging a bit into this, code example blocks are now not linked, but highlighted instead. That makes them consistent with normal fenced code blocks (&#96;&#96;&#96;python ...&#96;&#96;&#96;), and more pleasant to look at. 😃 I've pushed a 6.2.0 release that includes this.
