### ISSUE TITLE
Broken links on index page

### ISSUE THREAD

**Issue by seidlmic** [mitmproxy/pdoc#224]
The links on index page under search input are broken for modules from second level and probably lower.
Link `<package>.<module>.<submodule>` targets to non exists page `<package>/<module>.<submodule>.html`
but should target to page `<package>/<module>/<submodule>.html` which is correctly created.

#### System Information
Paste the output of "pdoc --version" here.
```
pdoc: 6.1.0
Python: 3.7.6
Platform: Linux-4.19.0-11-amd64-x86_64-with-debian-10.6
```

**Comment by mhils** [comment]
This has been [fixed in the last release](https://github.com/mitmproxy/pdoc/blob/main/CHANGELOG.md#2021-02-14-pdoc-630), `pip install -U pdoc` and you should be good to go! :smiley:

**Comment by seidlmic** [comment]
Confirmed, upgrade helped. Thanks
