### ISSUE TITLE
Data Descriptors aren't properly captured

### ISSUE THREAD

**Issue by barbester** [mitmproxy/pdoc#226]
#### Problem Description
When a class attribute is implemented as a data descriptor, pdoc doesn't seem to be able to capture its docstring correctly.

For instance, put the code below into a module called descriptor.py and run pdoc on it.

```python
class Descriptor():
    def __init__(self, func):
        self.__doc__ = func.__doc__

    def __get__(self, instance, owner):
        return self if instance is None else getattr(instance, "_x", 0)

    def __set__(self, instance, value):
        instance._x = value


class Dummy:
    @Descriptor
    def size(self):
        """This is the size"""
```
The result is like this:
![image](https://user-images.githubusercontent.com/32171758/109048669-a39db500-76d7-11eb-8a27-22315eaeeb90.png)

i.e. the size attribute is correctly identified as a `Descriptor` instance, but its `__doc__` is not captured.

---

Now remove method `__set__` from the `Descriptor` class, so that it is a non-data descriptor. This changes the result to:

![image](https://user-images.githubusercontent.com/32171758/109061474-ff236f00-76e6-11eb-9af1-2bdf0c7fd96d.png)

i.e. now the docstring is present.

#### System Information
```
pdoc: 6.3.1
Python: 3.7.9
Platform: Windows-10-10.0.19041-SP0
```

**Comment by mhils** [comment]
Good catch, thanks for the detailed description! Could you please verify that https://github.com/mitmproxy/pdoc/pull/227 behaves as expected? 😃

**Comment by barbester** [comment]
I had a look, seems fine now! Thanks for the super quick turnaround! 😃

**Comment by mhils** [comment]
Exellent.! 6.3.2 is out in a few minutes. 😃
