### ISSUE TITLE
Don't show non-public decorators above function signatures

### ISSUE THREAD

**Issue by zmoon** [mitmproxy/pdoc#230]
#### Problem Description
pdoc-generated docs show applied decorators above function definitions by default, including decorators whose names starts with `_`.

#### Proposal
Since the default pdoc behavior is to not document names starting with `_`, I think the application of such decorators should not be shown in the generated documentation for the function, especially since by default documentation for the decorators themselves won't be generated.

**Comment by mhils** [comment]
That sounds like a reasonable change to me.

We can probably just sneak in an `if not d.startswith("_")` at the end of the statement here:
https://github.com/mitmproxy/pdoc/blob/abec938e60fc72da87c381ce8c7c468549bfe236/pdoc/templates/default/module.html.jinja2#L514

This and a test example in `test/testdata/misc.py` and we should be good to go! :smiley:
