### ISSUE TITLE
`__doc__` class attributes are documented as class members in C extensions

### ISSUE THREAD

**Issue by ravenexp** [mitmproxy/pdoc#235]
#### Problem Description

I tried to generate pdoc documentation for my Python extension module.

The output looks mostly fine, but all module classes have their `__doc__` attributes included
in the document as if they were some user-defined attributes.

The same issue happens with other extension modules (not written in Python),
including Python built-ins like `csv`.

#### Steps to reproduce the behavior:

1. `pdoc csv`
2. Observe that all classes have `__doc__` attributes listed.
3. Observer that the module itself has its `__doc__` attribute listed.

What is puzzling that some other built-ins do not have this problem:

1. `pdoc json`
2. Class documentation does not have `__doc__` attributes listed.

#### System Information

pdoc: 6.4.0
Python: 3.9.2
Platform: Linux-5.10.24-1-lts-x86_64-with-glibc2.33

**Comment by mhils** [comment]
Thanks for providing a super straightforward repro, I'll take a look! 😃

**Comment by mhils** [comment]
Ok, there are two things going on:

 1. The csv module lists `__doc__` in `csv.__all__`, which is why pdoc picks it up.
 2. For everything except the top-level `__doc__` attribute, pdoc incorrectly checks if `__doc__` is in `__all__`, even though it should check for example if `Error.__doc__` is in `__all__`.

The second point is something I'll fix right away, the first point is something we should tackle as well but I need to understand better. Why do you and stdlib list `__doc__` in `__all__`? Is that advocated somewhere?

**Comment by mhils** [comment]
I grepped the entire standard library and only found `csv` to include `__doc__` in `__all__`. Do you know of any other examples?

I _think_ the intended use case here was that `dir(csv)` includes `__doc__`. In contrast, `concurrent.futures` explicitly covers it in `__dir__`:

https://github.com/python/cpython/blob/63298930fb531ba2bb4f23bc3b915dbf1e17e9e1/Lib/concurrent/futures/__init__.py#L36-L37

**Comment by ravenexp** [comment]
I use [PyO3](https://github.com/PyO3/pyo3) to write my extension module in Rust.

It generates `__all__` attribute for modules automatically, and it indeed includes `__doc__`.
Maybe I should file a bug there if it's not the correct behavior.

**Comment by mhils** [comment]
I actually do think this is undesired behavior by PyO3, then again `__all__` is just vastly underspecified in general. PyO3's `module.add` just generally adds items to the index:

https://github.com/PyO3/pyo3/blob/c0d49052b5f8d84a68b4d5d6c71c5def0bdc66a2/src/derive_utils.rs#L323

**Comment by ravenexp** [comment]
I created a PyO3 issue about module-level `__doc__`:

https://github.com/PyO3/pyo3/issues/1508

**Comment by ravenexp** [comment]
> I actually do think this is undesired behavior by PyO3, then again `__all__` is just vastly underspecified in general. PyO3's `module.add` just generally adds all members to the index:

It is not that bad. Only items added with `PyModule::add()` are added to `__all__`, but attributes set via `PyModule::setattr()` for example are not.

I set `__version__` and `__author__` attributes for my module, and they do not show up in `__all__`.
I beileve `add()` was intended to be a part of the user-facing API, but also was accidentally used in a proc macro.

**Comment by mhils** [comment]
#236 should fix this on pdoc's side, thanks again for the report! I'll ship a patch release once CI clears. 😃
