### ISSUE TITLE
Automatic Linking doesn't work when __all__ is specified.

### ISSUE THREAD

**Issue by impguard** [mitmproxy/pdoc#242]
#### Problem Description
I'm not super sure how hard this is, but currently when a module exposes its submodules with "__all__", dependency linking is lost. I understand if they're lost if the modules aren't included, but when they are, it's unfortunate that the linking is lost.

#### Steps to reproduce the behavior:
1. Create a module with two files each creating classes. Have one file's classes extend classes in the other file.
2. Create a `__init__.py` exposing an `__all__` that exports all classes
3. Generate docs

#### System Information
pdoc: 6.4.1
Python: 3.8.2
Platform: macOS-10.16-x86_64-i386-64bit

**Comment by mhils** [comment]
Thanks! Could you provide simple example files to reproduce it?

**Comment by impguard** [comment]
Sure.

```
# a.py
class A:
  def a():
    return 1
```

```
# b.py
class B(A):
  def b():
    return 2
```

```
# __init__.py
from .a import A
from .b import B

__all__ = ["A", "B"]
```

Toss all three in a module and run pdocs. A and B show up as valid files for the module but the inheritance links are missing.

**Comment by mhils** [comment]
Excellent, thanks! #243 has the fix, if CI goes green I'll follow up with a release straight away :)

**Comment by mhils** [comment]
6.4.2 is out! 🥳

**Comment by impguard** [comment]
Wow, that's awesome. Thanks!
