### ISSUE TITLE
Better directory customization

### ISSUE THREAD

**Issue by Quantalabs** [mitmproxy/pdoc#244]
#### Problem Description

When creating docs with the custom directory:
```terminal
pdoc [module] -o docs/
```
It puts the docs in the folder `docs/module`.

#### Proposal
 Putting the docs simply in `docs/` would be much better.

#### Alternatives
Using another documentation creator, however, they haven't worked as well with docstrings.

**Comment by mhils** [comment]
Hi there! Could you give a more concrete example of what you are trying to achieve? pdoc does put the rendered documentation directly in to `docs/` for me:

```
$ pdoc pdoc -o docs/
$ ls docs/
index.html  pdoc  pdoc.html
```

**Comment by Quantalabs** [comment]
The directory structure looks like this for a package with the name "Clarinet":
```shell
$ pdoc clarinet -o docs/
$ ls docs/
Clarinet/
$ cd docs/Clarinet
$ ls 
index.html 
```
However, what I'd want is:
```
$ pdoc clarinet -o docs/
$ ls docs/
index.html
```
and no clarinet subfolder.

**Comment by mhils** [comment]
Could you post the output of `pdoc --version` please?

**Comment by Quantalabs** [comment]
```
$ pdoc --version
pdoc.exe 0.9.2
```

**Comment by mhils** [comment]
This looks like you are using pdoc3, not pdoc (see [pdoc vs. pdoc3](https://github.com/mitmproxy/pdoc#pdoc-vs-pdoc3)).

You can run `pip uninstall pdoc3` followed by `pip install pdoc` to install pdoc.

**Comment by Quantalabs** [comment]
Oh no! Sorry! That was my pdoc3 version, not pdoc version!
```
$ pdoc --version
pdoc: 6.4.2
Python: 3.8.7
Platform: Windows-10-10.0.19041-SP0
```

**Comment by mhils** [comment]
The folder structure you generated looks like it has been generated by pdoc3, not by pdoc. If you run pdoc, you should get what I described in https://github.com/mitmproxy/pdoc/issues/244#issuecomment-813897580 :)

**Comment by Quantalabs** [comment]
It does seem that **pdoc** is outputting the docs in the right directory, sorry for the trouble!
