### ISSUE TITLE
Support `.. include:`

### ISSUE THREAD

**Issue by jstriebel** [mitmproxy/pdoc#249]
#### Problem Description
Additional markdown files might add useful context to the documentation are not parsed by pdoc.

#### Proposal
Would you be open to have support for pure markdown files as input? Those could either be discovered automatically in the source directory, or might be supplied via an extra path. I'd tend to the second variant, since this would not add any unexpected files to existing docs when upgrading, and one could easily use `pdoc --md-input pkg pkg` or something similar.

#### Alternatives
* One could of course generate the html from any other tool, but it would be nice to be able to easily generate them in a similar style as the docs and possibly with the same toc.
* Extracting the css from the templates might also help to style other html

#### Additional context
@mhils If you'd be open to add this functionality, I'd be happy to draft a PR (probably rather in the next weeks than days).

**Comment by mhils** [comment]
> Would you be open to have support for pure markdown files as input?

From a practical point of view I think this introduces too much complexity for what we gain. pdoc is really focused on API documentation, I'm not reallying planning to turn it into a fully-fledged static site generator. :) FWIW, the other way around (embedding pdoc into other systems) is [fairly well supported](https://pdoc.dev/docs/pdoc.html#integrate-pdoc-into-other-systems).

One possible alternative would be to add support for `.. include:: foo.md` reStructuredText directives. That would allow you to either include arbitrary markdown documents into your existing modules (or new modules that just do that). Would that also (at least partially) address your use case?

**Comment by jstriebel** [comment]
> From a practical point of view I think this introduces too much complexity for what we gain.

Sounds fair :+1:

> One possible alternative would be to add support for .. include:: foo.md reStructuredText directives. That would allow you to either include arbitrary markdown documents into your existing modules (or new modules that just do that). Would that also (at least partially) address your use case?

An include directive would be quite useful, since some modules might require long documentations that would clutter the code. :+1: For the moment embedding pdoc into some other system and just using links to other documents is also fine.

Feel free to close this issue or leave it as a placeholder for the include-directive.

**Comment by mhils** [comment]
Excellent 👍 

 `.. include:` should be relatively straightforward to implement, it just needs to be added here:

https://github.com/mitmproxy/pdoc/blob/41215bcce4708aa53c67bad3b2e786a80d387597/pdoc/docstrings.py#L198-L217

**Comment by mhils** [comment]
Support for `.. include::` has just landed on main! 😃
