### ISSUE TITLE
Provide custom values to templates

### ISSUE THREAD

**Issue by impguard** [mitmproxy/pdoc#253]
#### Problem Description

At doc generation time, sometimes it's useful to insert some metadata into custom templates. Providing a flag to pass in custom fields and then just passing these values wholesale into templates for use by jinja would be useful!

#### Proposal

A flag, say `--field key,value` or `--custom-fields field:value,field:value` depending on which is easier to implement that would said jinja global template vars for each field/value pair. Then, in jinja templates, these fields could be used as the user desired.

Right now, I'm handling this by autogenerating a jinja template from another template and then passing the template into pdoc, so this feature would remove an unnecessary and fairly hacky step in the process.

**Comment by mhils** [comment]
Hi there! This sounds like a useful suggestion, although I'd also like to keep pdoc as simple as possible. How would you feel about making environment variables accessible in the Jinja2 templates (e.g. `{{ env["GIT_COMMIT"] }}`)? Would that address your use case?

**Comment by impguard** [comment]
Yup, I think that makes complete sense and would keep pdoc simple.

**Comment by mhils** [comment]
Thanks again for the excellent suggestion! This has just landed on main, we should have a release on PyPI in a few minutes. 😃
