### ISSUE TITLE
Way to hide Python prompt in examples

### ISSUE THREAD

**Issue by mikecharles** [mitmproxy/pdoc#26]
It would be nice to be able to click something to hide the Python prompts in examples, like you can in the [Numpy docs](http://docs.scipy.org/doc/numpy/reference/generated/numpy.polynomial.polynomial.polytrim.html)

**Comment by BurntSushi** [comment]
That does seem nice. I'm happy to accept a PR so long as it doesn't add any significant complexity to the view logic (which is already too complex).
