### ISSUE TITLE
Parsing code examples renders empty lines incorrectly

### ISSUE THREAD

**Issue by Crozzers** [mitmproxy/pdoc#264]
#### Problem Description
Parsing "Example:" sections in google-style docstrings renders incorrectly in HTML docs if there are any empty lines in the example

#### Steps to reproduce the behavior:
1. Create test function with example section in docstring. EG:
```python
def a():
	'''
        Sample description

	Example:
		```python
		tmp = a()

                tmp2 = a()
		```
	'''
	return
```
2. Run command `pdoc -d google -o tmp ./test.py`
3. Open file `tmp/test.html`
4. ![image](https://user-images.githubusercontent.com/57498990/119879938-a94ba680-bf23-11eb-9862-ed7604b4d9ce.png)



#### System Information
pdoc: 7.0.1
Python: 3.9.2
Platform: Windows-10-10.0.19041-SP0

**Comment by mhils** [comment]
Good catch, thanks! I've just pushed a fix which resolves this issue. New wheels should be on PyPI in a few minutes! 😃

**Comment by Crozzers** [comment]
Can confirm [e997144](https://github.com/mitmproxy/pdoc/commit/e9971444c1b169dfb5f4112eedc739f34eeb121b) fixed the issue. Cheers for that. Makes the switch from pdoc3 much easier :)
