### ISSUE TITLE
Support for reST admonitions

### ISSUE THREAD

**Issue by corykinney** [mitmproxy/pdoc#272]
First off, I'm super excited this project is back! I don't have any skills with HTML or CSS, so I can't really contribute too much, but I've got some ideas for enhancements. If they aren't in line with the goals of pdoc though, or if the feature is already implemented and I somehow missed, we can close the issue!

#### Problem Description

pdoc doesn't currently have any styled support for warnings/caution messages besides including standard text in a notes section of the docstring. I know that pdoc's documentation says that "pdoc does not implement the full reStructuredText specification and does not plan on doing so", but I believe that specifically warning/caution messages would add a lot to the completeness of the documentation capabilities.

#### Proposal

It would be preferable if support for reST admonitions such as `.. caution::` or `.. warning::` could be implemented such that they would be highlighted in a orange or red framed box with a "Caution" or "Warning" header to draw attention when reading documentation.

**Comment by mhils** [comment]
Hi there!

Thanks for the suggestion. Two thoughts on this:

1. pdoc fundamentally works with Markdown as the intermediate format, which does not have a standard definition for admonitions. From that perspective it's really not in scope for pdoc. If you manage to integrate support for admonitions into [markdown2](https://github.com/trentm/python-markdown2) (which is what we use), I'd be happy to enable it and change the docstring converters.
2. As a more pragmatic alternative, I'd be more than happy to add emojis to some admonitions: 
![image](https://user-images.githubusercontent.com/1019198/120765992-1231b080-c51a-11eb-91df-830b868b2f11.png) That's a simple change which still adds a good amount of emphasis, and works with all docstring flavors. What do you think?

**Comment by corykinney** [comment]
1. I see now that the original suggestion is a bit out of scope for pdoc; I went ahead and opened a markdown2 feature request ([#401](https://github.com/trentm/python-markdown2/issues/401)) to see if it's something that others might be interested in as well. 
2. Regarding emojis, I personally am not sure whether I would use that or not, but it could be a good optional feature. Besides ⚠️ for warnings, are there any others that would make sense?

**Comment by mhils** [comment]
> Regarding emojis, I personally am not sure whether I would use that or not, but it could be a good optional feature. Besides ⚠️ for warnings, are there any others that would make sense?

I played around with this for a bit... from my perspective it only makes sense for warnings to add some emphasis. @mrossinek, I see you 👍ing things, do you have any opinions?

What I can say for sure is that we want to make a general decision here and not add an optional feature, I don't want to add additional complexity for such a niche case here.

**Comment by corykinney** [comment]
@mhils I think it would be a limited use case to add an emoji solely for warnings. After all, if someone wanted that there, couldn't they just put the emoji in the docstring since Python already supports Unicode characters? I think it might be best to just close this issue and reopen it if markdown2 ever happens to add admonition support.

**Comment by mrossinek** [comment]
I think some visual block for warnings, "tips and tricks" or simple notes could be a useful **niche** use case. However, I agree that this is likely a lot of overhead for such minor applications and, thus, think the emoji addition to a docstring suffices.

If a customizable _label-to-color highlight_ mapping would be thing in markdown, that would be neat. That being said, I have not tested if pdoc supports inlined HTML within Markdown docstrings :thinking:
