### ISSUE TITLE
Syntax highlighting compatibility

### ISSUE THREAD

**Issue by corykinney** [mitmproxy/pdoc#274]
#### Problem Description

Currently the color for class names, function names, and variables names is customized by a single `--name` variable in a module.html.jinja2 template file to override the default. 

#### Proposal

It would be nice if there could be additional control to separate class names, function names, and variable names if desired by the user, perhaps with optional `--class`, `--function`, and `--variable` variables so that the colors could match that of the syntax highlighter if desired.

#### Alternatives

It would be even better if there was a way to automatically set colors for module.html.jinja2 from syntax-highlighting.css for maximum consistency:
- `--code`
- `--def`  from `.k`
- `--class` from `.nc`
- `--function` from `.nf`
- `--variable` from `.nv`

**Comment by mhils** [comment]
FWIW you can control colors for variables/functions/classes individually like so:
```css
.pdoc .function > .name {
    color: pink;
}
```

I've also played around with reusing the pygments styles (https://github.com/mitmproxy/pdoc/compare/main...mhils:reuse-pygments-color), but honestly I feel it much rather makes the template less readable.  Also I prefer the darker blue for non-bold function definitions in the source code, whereas the lighter blue looks nicer to me for bold text in pdoc itself.

As long as we use the same color for all classes/functions/variables, I'd like to keep pdoc simple, not intermingle with pygments, and keep things as-is. :)

**Comment by corykinney** [comment]
@mhils what would be the best place to ask questions so that I make sure I'm not opening issues or suggesting enhancements that are already implemented? I'm trying my best to look through the documentation before posting, but I'm inevitably missing things, especially in the realm of CSS/templating.

**Comment by mhils** [comment]
@corykinney: If it's not mentioned in the docs and you can't find a relevant GitHub issue, please just open a new one. :)
