### ISSUE TITLE
Latex not rendered in search previews

### ISSUE THREAD

**Issue by corykinney** [mitmproxy/pdoc#276]
#### Problem Description
When using the search bar, Latex equations and symbols are shown in plain text rather than rendered properly. I would expect how the previews of function and class documentation look to match how the actual documentation is rendered. I'm not sure if this is intentional to save on resources/speed of showing search results or if there are other potential limitations I'm not aware of.

#### Steps to reproduce the behavior:
1. Have Latex in a function docstring in either single line (`$ ... $`) or multi-line (`$$ ... $$`) format
2. Generate documentaiton with pdoc using the [module template from the math example](https://github.com/mitmproxy/pdoc/blob/main/examples/math/module.html.jinja2)
3. Search for the name of the function

#### System Information
pdoc: 7.0.1
Python: 3.9.4
Platform: Windows-10-10.0.19041-SP0

**Comment by mhils** [comment]
Good catch, thanks for the report!
I think we need to tell MathJax to re-render when we add dynamic content, but that [doesn't seem to be too difficult](http://docs.mathjax.org/en/latest/advanced/typeset.html).  It's probably enough to just call `MathJax.typeset()` after rendering the search results. :)
I'm happy to give this a shot in the next few days unless someone beats me to it. :)

**Comment by mhils** [comment]
Actually scratch that, I was curious and this was straightforward. :) If you update to the latest example everything should work!

**Comment by corykinney** [comment]
@mhils awesome, it works perfectly! Thanks :)
