### ISSUE TITLE
Included markdown file not hot-reloaded

### ISSUE THREAD

**Issue by fm3** [mitmproxy/pdoc#277]
#### Problem Description
As described in https://pdoc.dev/docs/pdoc.html#include-markdown-files I included a markdown file in my docstring. When I edit this markdown file the pdoc output in the browser is not updated. Editing the python file that includes it also does not trigger a reload of the markdown file. (The content from the python file itself updates fine). It would be great if this could be added.

#### Steps to reproduce the behavior:
1. Include a markdown file in `__init__.py`, e.g. 
```
"""
.. include:: hello.md
"""
__docformat__ = "restructuredtext"
```
2. Run pdoc with `-p 8095 -h 0.0.0.0`
3. Open in browser, then edit and save the markdown file, refresh in browser, no updates shown

#### System Information
pdoc: 7.0.0
Python: 3.8.8
Platform: Linux-5.9.8-050908-generic-x86_64-with-glibc2.10

**Comment by mhils** [comment]
Good catch, thanks! 😃

**Comment by mhils** [comment]
I've just pushed a partial fix for this: Reloading the page now shows the updated docstring. However, pdoc will not pick up changes to the included Markdown file and automatically reload the page. The complexity of that outweights the benefits here. I think you can easily mock up similar functionality with https://github.com/cortesi/modd 😃

**Comment by fm3** [comment]
That’s great, thank you! Page refresh is fine by me :)
