### ISSUE TITLE
Splitting render_docstring filter into apply_docformat and md_to_html

### ISSUE THREAD

**Issue by jstriebel** [mitmproxy/pdoc#279]
#### Problem Description

I wrote a custom docstring macro that converts specific strings to links. It's awesome how nicely this can be integrated via the custom templates! :rocket: This conversion operates on the markdown of the pure docstring before `render_docstring` is applied, since markdown can handle simple syntax mistakes, such as nested links, which would require much more complexity if applying the links on the html. However, this currently does not work for included markdown files (via `.. include:: additional_docs.md`), since those are included during `render_docstring`.

#### Proposal
It would be helpful to split `render_docstring` into two parts, the first one applying the docformat (and therefore also processing the include directive), and the second one converting markdown to html. Then the custom logic on the markdown could nicely work on the in-between result.

#### Alternatives
* applying the custom logic to the html, which would introduce much more complexity in the template
* moving the included markdown into the docstrings directly, which clutters the code massively

#### Additional context
The macro is defined in a custom `module.html.jinja2` template and uses an environment variable and some hacky templating. The env var `AUTO_LINKS` is a mapping from specific class names to their modules, e.g. `MyImportantClass:some.module|AnotherClass:from.another.module`. Then automatic links for those classes are inserted wherever the class is used in docstrings:

```
{% defaultmacro docstring(var) %}
    {% if var.docstring %}
        {% set tmp_var = {"docstring": var.docstring} %}
        {% set top_level = "../" * module.modulename.count(".") %}
        {% for link_info in env["AUTO_LINKS"].split("|") %}
            {% set link_name, link_module = link_info.split(":") %}
            {% set link_html_path = link_module.replace(".", "/") + ".html#" + link_name %}
            {% set md_link = "[" + link_name + "](" + top_level + link_html_path + ")" %}
            {% if tmp_var.update({"docstring": tmp_var.docstring.replace(link_name, md_link)}) %}{% endif %}
        {% endfor %}
        <div class="docstring">{{ tmp_var.docstring | render_docstring | linkify(namespace=var.qualname) }}</div>
    {% endif %}
{% enddefaultmacro %}
```

**Comment by mhils** [comment]
That sounds like a reasonable change. We can maybe split render_docstring into `convert_docformats` and `render_markdown`? Do you want to send a PR? :)
