### ISSUE TITLE
Instance variable docstrings are lost if the variable is redefined

### ISSUE THREAD

**Issue by mikecharles** [mitmproxy/pdoc#28]
It appears that when an instance variable is redefined below its original definition (which includes the docstring), then the docstring gets lost.

For example:

``` python
class Test:
    def __init__(self, name=None):
        self.name = 'Mike'
        '''Name of person'''
        self.age = 30
        '''Age of person'''
        self.gender = None
        '''Gender of person'''
```

produces:

![screen shot 2015-02-13 at 3 57 28 pm](https://cloud.githubusercontent.com/assets/265620/6195124/0abe0252-b399-11e4-8d6c-b8daf3cb5150.png)

while this:

``` python
class Test:
    def __init__(self, name=None):
        self.name = 'Mike'
        '''Name of person'''
        self.age = 30
        '''Age of person'''
        self.gender = None
        '''Gender of person'''

        self.name = name
        self.gender = 'Male'
```

produces:

![screen shot 2015-02-13 at 3 58 16 pm](https://cloud.githubusercontent.com/assets/265620/6195134/2be2a186-b399-11e4-9fcb-525269beca09.png)

Shouldn't the docstring be locked down once it's found (unless another attached docstring is found)?

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. This should be fixed with the latest release. 😃
