### ISSUE TITLE
error: unrecognized arguments: -t

### ISSUE THREAD

**Issue by fabricix** [mitmproxy/pdoc#281]
#### Problem Description
Unrecognized arguments error when I am trying to test a math render example.

#### Steps to reproduce the behavior:
1. Clone the repository
2. Run `cd examples/math && pdoc -t . ./math_demo.py`

#### System Information
pdoc 0.9.2

**Comment by mhils** [comment]
The latest pdoc release is [7.1.1](https://pypi.org/project/pdoc/), so you need to update! It looks like you have pdoc3 installed, which also takes over pdoc's command name (https://github.com/mitmproxy/pdoc#pdoc-vs-pdoc3).
