### ISSUE TITLE
`include` directive doesn't appear to work

### ISSUE THREAD

**Issue by Terrance** [mitmproxy/pdoc#289]
### Problem description

I don't seem to be able to use `.. include:: path/to/file.md` -- the directive is left verbatim in pdoc's output.

Looking at #249 suggests this was introduced in version 6.5.0, and as far as I can tell it shouldn't require any additional configuration...  but I've tried this with 7.3.1, 6.5.0 and the current main branch, all with no success.

### Steps to reproduce the behavior

README.md:
```markdown
# README
```
module/\_\_init__.py:
```python
"""
.. include:: ../README.md
"""
```
Invoking pdoc:
```shell
$ pdoc -o html module
```
![Resulting output](https://user-images.githubusercontent.com/4025899/129113831-c36110a3-d316-4283-b1fb-2cb5bc95ac88.png)
(I've also tried moving README.md inside the module directory and adjusting the path, in case it's unhappy with traversing parent directories, but it still doesn't include.)

### System information

```
pdoc: 7.3.1
Python: 3.9.6
Platform: Linux-5.13.6-arch1-1-x86_64-with-glibc2.33
```

**Comment by mhils** [comment]
`.. include::` is not pure Markdown but part of reStructuredText. Have you set your [docformat](https://pdoc.dev/docs/pdoc.html#use-numpydoc-or-google-docstrings) accordingly?

**Comment by Terrance** [comment]
Aha, that would be it -- seems like it's recognised using anything but the default for `--docformat`.  It'd be useful to note at https://pdoc.dev/docs/pdoc.html#include-markdown-files that it isn't parsed by default, as it currently sounds like it should just work.

The help on docstring formats does shed some light on it, though I didn't think to look there as the heading only mentioned NumPy and Google.  🙂  From that section:

> While pdoc prefers docstrings that are plain Markdown, it also understands numpydoc and Google-style docstrings, including a limited subset of reStructuredText (as used by Sphinx).

I assume then that `-d restructuredtext` effectively enables the parsing of RST directives, but otherwise continue to treat the rest of the docstrings as Markdown, and doesn't attempt to parse a specific NumPy/Google docstring style?

**Comment by mhils** [comment]
> Aha, that would be it -- seems like it's recognised using anything but the default for --docformat. It'd be useful to note at https://pdoc.dev/docs/pdoc.html#include-markdown-files that it isn't parsed by default, 

Yes, this is useful feedback. I'll add a sentence. 😃 

> I assume then that -d restructuredtext effectively enables the parsing of RST directives, but otherwise continue to treat the rest of the docstrings as Markdown, and doesn't attempt to parse a specific NumPy/Google docstring style?

Exactly. The code here is quite straightforward:

https://github.com/mitmproxy/pdoc/blob/1459c5ff7c162b18cf58fc0897f9f9a1b4e297ef/pdoc/docstrings.py#L26-L41
