### ISSUE TITLE
Dynamically add/remove packages from HTTP server

### ISSUE THREAD

**Issue by mikecharles** [mitmproxy/pdoc#29]
It would be nice if it were possible to start the HTTP server, and then when someone creates a new package to somehow "add it" to the HTTP server that's running.

For example, if I have this set up for my org, it'll be run as root. I'm not sure how I'd add a package once the server is running, aside from restarting the server once I've installed the package

**Comment by BurntSushi** [comment]
Maybe. It depends on how complex this implementation would be. Restarting the server doesn't seem like a horrible workaround to me.

**Comment by mike-charles** [comment]
I agree that restarting the server isn't usually a big deal, but I'm working in a really restricted environment where it would take an IT support ticket to restart the server each time, and they would begin to question us if we were restarting it often.
