### ISSUE TITLE
Forward references in type aliases imported from other modules are not resolved

### ISSUE THREAD

**Issue by Terrance** [mitmproxy/pdoc#290]
### Problem description

Forward references of type annotations aren't resolved to their types, and annotations imported from other files trigger warnings that their references can't be resolved.

### Steps to reproduce the behavior

module/types.py:
```python
from typing import Union

class Concrete: pass

IntConcrete = Union[Concrete, int]
IntForward = Union["Forward", int]
ConcreteForward = Union[Concrete, "Forward"]
"""Documented type."""

class Forward: pass
```

module/main.py:
```python
from .types import ConcreteForward, IntConcrete, IntForward

class Test:
    def __init__(self, a: IntConcrete, b: IntForward, c: ConcreteForward):
        self.a = a
        self.b = b
        self.c = c
```

Invoking pdoc:
```
$ pdoc -o html module
```
> /usr/lib/python3.9/site-packages/pdoc/doc_types.py:120: UserWarning: Error parsing type annotation for module.main.Test.\_\_init__. Import of Forward failed: name 'Forward' is not defined

<details>
<summary>Resulting output</summary>

![Resulting output for module.types](https://user-images.githubusercontent.com/4025899/129343131-953a3a0c-886a-46e6-9fe1-e0d9533e27a3.png)

![Resulting output for module.main](https://user-images.githubusercontent.com/4025899/129342641-46e624ba-25ab-447d-a079-4e6e9f6bfa75.png)
</details>

The example is somewhat contrived; the use case here would be keeping a type annotation at the top of a file alongside its related class `Forward` (where `Concrete` could come from another import and therefore be defined first), usable both within `Forward` and elsewhere in the project.

### System information

```
pdoc: 7.3.1
Python: 3.9.6
Platform: Linux-5.13.6-arch1-1-x86_64-with-glibc2.33
```

**Comment by mhils** [comment]
Thanks for the clear report! This is a bit tricky to tackle, we fundamentally do dynamic analysis and not static analysis, but I may have some ideas on how we can work around this. I'll take a look next week. :)

**Comment by mhils** [comment]
I've tried to come up with some viable workarounds today, but we're really running into a Python bug here that's hard to fix from our end. I've created https://bugs.python.org/issue44926 to track this upstream. 

This may take some while before it's fixed. As a workaround, you could do two things:

1. Use `from __future__ import annotations` to get rid of the forward references in the type aliases:
    
    ```python
    from __future__ import annotations
    from typing import Union

    class Concrete: pass
        def foo(self) -> IntConcrete:  # can now already be used here.
            pass

    IntConcrete = Union[Concrete, int]
    """Documented type."""

    __all__ = [ ... ]  # optionally adjust the order in the documentation.
    ```
2. Reassign `IntForward` and friends at the end of the module:
    ```python
    from typing import Union

    class Concrete: pass

    IntConcrete = Union[Concrete, int]
    IntForward = Union["Forward", int]
    ConcreteForward = Union[Concrete, "Forward"]
    """Documented type."""

    class Forward: pass

    # reassign to avoid forward references
    IntForward = Union[Forward, int]
    ConcreteForward = Union[Concrete, Forward]
    ```

I'd recommend option 1, but either should ultimately work. :)

**Comment by Terrance** [comment]
Sadly I'm still supporting Python 3.6, so I don't have the luxury of postponed annotations just yet.  Moving the types to the bottom will work, at the cost of needing to quote the types across all their uses in the file where they're defined, but for the consistent linking within the docs it's probably worth it.  🙂

**Comment by mhils** [comment]
If you want to avoid the quotes, the second workaround I posted should do the trick. Either way, 3.6 EOL is end of this year. 😉

**Comment by mhils** [comment]
Following up from https://bugs.python.org/issue44926: The underlying problem here is more fundamental and can't be fixed on Python's side. pdoc is fundamentally based on dynamic analysis, so this is nothing we want to tackle statically here either. I'm closing this as wontfix, I think https://github.com/mitmproxy/pdoc/issues/290#issuecomment-899682415 has viable workarounds for all situations. :)
