### ISSUE TITLE
Forward references with typing.TYPE_CHECKING guard does not resolve correctly

### ISSUE THREAD

**Issue by davfsa** [mitmproxy/pdoc#291]
#### Problem Description
Making use of forward references typing with a `typing.TYPE_CHECKING` guard to avoid circular dependencies causes the typehint to not be resolved correctly and kept as a string

#### Steps to reproduce the behavior:
`dir`
```
test-pdoc/
    - __init__.py
    - foo.py
    - bar.py
```

`cat test-pdoc/foo.py`
```py
class Foo:
    ...
```

`cat test-pdoc/bar.py`
```py
from __future__ import annotations

import typing

if typing.TYPE_CHECKING:
    from test_pdoc import foo


def bar() -> foo.Foo:
    ...
```

#### Expected Behavior
![image](https://user-images.githubusercontent.com/29100934/129441778-a4c0d1d8-af6e-484a-92af-a27937e5593f.png)

#### Actual Behavior
![image](https://user-images.githubusercontent.com/29100934/129441815-7484295e-8b55-4304-bf19-1fed40a0a364.png)

*Command run to generate docs was `pdoc ./test_pdoc`* 

#### System Information
pdoc: 7.3.1
Python: 3.8.10
Platform: Linux-5.13.1-051301-generic-x86_64-with-glibc2.29

**Comment by mhils** [comment]
Thanks! That is closely related to #290, I'll take a look.

**Comment by mhils** [comment]
A fix for this is on main, thanks again! 😃
