### ISSUE TITLE
Allow applying a filter to all docstrings before rendering

### ISSUE THREAD

**Issue by mdaeron** [mitmproxy/pdoc#292]
#### Problem Description

I'm maintaining documentation for [D47crunch](https://github.com/mdaeron/D47crunch), a geochemistry library whose docstring use many subscripts and superscripts. I need the rendered documentation to have `<sub></sub>` and `<sup></sup>` tags, but I'd much prefer to leave them out in the plain text doscstring printed out by Python's `help()` function. This could be achieved relatively painlessly if there was an easy way to apply a user-defined filter function to all doscstrings before they are rendered by `pdoc`. My use case is but one of many, thus the proposal below would be useful in many different situations.

#### Proposal
Implement a way to specify a function to be applied to all docstrings before rendering. A valid filter function could be something like `lambda docstr: docstr.replace('foo', 'bar')`.

Ideally, this would take effect *after* injecting text from external files (using `.. include:: tutorial.md`), so that the content of said files is also affected.

**Comment by mhils** [comment]
Hi there!

@jstriebel asked for something similar in #279, you can now achieve this relatively easily with a custom Jinja2 template. Here's our default implementation for rendering docstrings:

https://github.com/mitmproxy/pdoc/blob/1459c5ff7c162b18cf58fc0897f9f9a1b4e297ef/pdoc/templates/default/module.html.jinja2#L608-L612

You can override this relatively simply with a custom template. This example here adds a [` | replace`](https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.replace) filter to modify all docstrings:

`module.html.jinja2`
```jinja2
{% extends "default/module.html.jinja2" %}
{% macro docstring(var) %}
    {% if var.docstring %}
        <div class="docstring">{{ var.docstring | to_markdown | replace("pdoc", "pdoc pdoc pdoc") | to_html | linkify(namespace=var.qualname) }}</div>
    {% endif %}
{% endmacro %}
```

See also https://pdoc.dev/docs/pdoc.html#editing-pdocs-html-template. If you really want to have a Python function for processing, you need to use pdoc as a library and add it to [`pdoc.render.env.filters`](https://github.com/mitmproxy/pdoc/blob/1459c5ff7c162b18cf58fc0897f9f9a1b4e297ef/pdoc/render.py#L155-L160)

**Comment by mdaeron** [comment]
Awesome, thank you for helping me out.

For future record, here is what works for my purpose. Substitutions are not applied in code blocks (fenced with <code>```</code>), nor in inline code (delimited by <code>`</code>).

```py
import pdoc

substitutions = [
	('δ13C_VPDB', 'δ<sup>13</sup>C<sub>VPDB</sub>'),
	('δ18O_VPDB', 'δ<sup>18</sup>O<sub>VPDB</sub>'),
	('δ18O_VSMOW', 'δ<sup>18</sup>O<sub>VSMOW</sub>'),
	('δ13CVPDB', 'δ<sup>13</sup>C<sub>VPDB</sub>'),
	('δ18OVPDB', 'δ<sup>18</sup>O<sub>VPDB</sub>'),
	('δ18OVSMOW', 'δ<sup>18</sup>O<sub>VSMOW</sub>'),
	('χ2', 'χ<sup>2</sup>'),
	('χ^2', 'χ<sup>2</sup>'),
	('CO2', 'CO<sub>2</sub>'),
	]

def myfilter(docstr):
	work = docstr.split('```')
	for k in range(len(work)):
		if k:
			work[k] = work[k].lstrip('`')
		if k%2 == 0:
			work[k] = work[k].split('`')
			for j in range(len(work[k])):
				if not j%2:
					for x,y in substitutions:
						work[k][j] = work[k][j].replace(x,y)
			work[k] = '`'.join(work[k])
	return ('```'.join(work))

pdoc.render.env.filters['myfilter'] = myfilter
pdoc.render.configure(template_directory = 'templates')

with open('index.html', 'w') as fid:
	fid.write(pdoc.pdoc('D47crunch'))
```
