### ISSUE TITLE
Make search and search.json optional via knob

### ISSUE THREAD

**Issue by trallnag** [mitmproxy/pdoc#294]
#### Problem Description

Currently the `search.json` is generated even if the search box is removed from the template. It would be nice to have a knob that disables (or just automatically deletes) the `search.json` and adjusts the template automatically.

**Comment by mhils** [comment]
Good point. Now that we have a bunch of CLI knobs for rendering, I think one for search makes sense as well! :)

**Comment by mhils** [comment]
7.4.0 is on PyPI in a few minutes, which has a `--search/--no-search` switch. 😃

**Comment by trallnag** [comment]
awesome, thank you
