### ISSUE TITLE
How can we propagate inherited functionality documentation without `__pdoc__` ? 

### ISSUE THREAD

**Issue by djberenberg** [mitmproxy/pdoc#295]
#### Problem Description
Greetings! I am a new user of `pdoc`, it's so easy to use! 

I have a system with multiple inheritance, I would like all inherited functionality to be documented in the child class. If `__pdoc__` still existed, I think this would be possible, but in light of its currently suspended support, is there a solution for this? 

#### code example
Suppose we have this class hierarchy:

```python3
class A:
    def a(self) -> str:
        """a doc"""
        return 'a'
class B:
     def b(self) -> str:
         """b doc"""
          return 'b'

class C(A, B):
    """C doc
    """
    pass
```
I would like the documentation of `C` to render as if I had something like:

```python3
class C(A, B):
    """C doc 
    """
    def a(self) -> str:
       """a doc"""
        return super().a()
    
    def b(self) -> str:
        """b doc"""
        return super().b()
```

Is this possible right now?

#### Proposal
None. This is more of a question.

#### Alternatives
I guess one alternative is to use the system as is, with inherited members. But I would like to view everything on the same page without changing the structure of my library.

#### Additional context
None

**Comment by mhils** [comment]
Hi there! Generally speaking pdoc really intends to document your API as it is, but there may be a few exceptions where what you are looking for makes sense (you mentioned mixins on Slack).
This is nothing that pdoc supports out of the box, but you should be able to get there easily by [modifying the default template](https://pdoc.dev/docs/pdoc.html#editing-pdocs-html-template). We have a `module_contents` block which you can override with your own:

https://github.com/mitmproxy/pdoc/blob/4bce7e2ba5fc774b87d93d4abb4f62ae26137a1a/pdoc/templates/default/module.html.jinja2#L789-L811


If you change the access from `m.own_members` to `m.members` in line 794 and remove the inheritance part starting in line 799, you should be good to go. 😃 https://pdoc.dev/docs/pdoc/doc.html has all the documentation for the objects you are working with here.

**Comment by djberenberg** [comment]
Thanks @mhils for the prompt response! Very elegant solution. Closing this issue.
