### ISSUE TITLE
Error when parsing reStructuredText when its located in between sections

### ISSUE THREAD

**Issue by davfsa** [mitmproxy/pdoc#296]
#### Problem Description
Error when parsing reStructuredText when its located in between sections as it detects it as if it is part of the section

#### Code:
```py
def testing():
    """This is a test docstring.

    Parameters
    ----------
    testing_param: str
        Some parameter.

        .. warning::
            Warning for this parameter.

    .. note::
        This is really important, but it will be rendered incorrectly.
    """
```

#### Render:
*Generated with `pdoc <file> -d numpy`*

![image](https://user-images.githubusercontent.com/29100934/130358641-ea0b96e1-65fa-48da-b284-b2cfbead2a97.png)

#### System Information
```
pdoc: 7.4.0
Python: 3.8.10
Platform: Linux-5.13.1-051301-generic-x86_64-with-glibc2.29
```

**Comment by mhils** [comment]
Thanks. Can you please post a repro that is not a screenshot?

**Comment by davfsa** [comment]
> Thanks. Can you please post a repro that is not a screenshot?

Updated the issue description. I created the issue in a rush and forgot to do it correctly :sweat_smile:

**Comment by mhils** [comment]
Ok, upon looking further this is a numpydoc problem. You can't put notes in the Parameter section. 
[`docstring_parser`](https://github.com/rr-/docstring_parser) fails on this as well, so does [`sphinxcontrib-napoleon`](https://pypi.org/project/sphinxcontrib-napoleon/), and so does [`numpydoc`](https://numpydoc.readthedocs.io/).
