### ISSUE TITLE
search.json - Fetch API error in Chrome

### ISSUE THREAD

**Issue by He-Wolf** [mitmproxy/pdoc#298]
#### Problem Description:
After generating html documentation, searching cannot be used in Chrome.
It gives the following error: **Fetch API cannot load file:///<mypath>/search.json. URL scheme "file" is not supported.**
Modern browsers do not let browser read files from the hard drive.
In the browser it show: **Error: Cannot fetch search index.**

#### Steps to reproduce the behavior:
1. generate documentation
2. open one of the module documentation html files in Chrome
3. try to search to a word

#### System Information:
pdoc: 7.4.0
Python: 3.9.6
Platform: Windows-10-10.0.19042-SP0

#### Temporarily I use a workaround:
- I rename the output *search.json* to *search.js* and put "var docs = " in front of the json.
- in *search.html.jinja2* I put *<script type="text/javascript" src="search.js"></script>*
- I also delete the following part from *search.html.jinja2*, function *async function initialize()*:
        {# Get the search index and compile it if necessary.
           This function will only be called once. #}
        let docs;
        try {
            let resp = await fetch("{{ rootprefix }}search.json");
            docs = await resp.json();
        } catch (e) {
            searchErr = "Cannot fetch search index.";
            throw e;
        }
- I remove *async* from function *initialize()*
- in "__ init__.py" I put "search = f'var docs = {search}'" after "search = render.search_index(doc_objects)" at the end of function 
*pdoc*.

I think it would be nice if this workaround was implemented in code.

**Comment by mhils** [comment]
Hi there!

Thanks for the detailed description. It looks like you want to be able to open pdoc's rendered HTML files locally in your browser using the `file://` protocol instead of `http[s]://`? Is there a reason why you prefer this over running pdoc interactively (e.g. `pdoc module`) instead of writing to disk (`pdoc -o ... module`)? I guess we can support that if the changes are minimal, I'm just trying to understand the use case here.

**Comment by He-Wolf** [comment]
Hello Max,

Works like charm! :)

Thank you for the quick response and good job.
