### ISSUE TITLE
Option to disable magic surrounding __init__ and __new__?

### ISSUE THREAD

**Issue by odigity** [mitmproxy/pdoc#312]
#### Problem Description

I'm trying out pdoc for the first time, and was getting frustrated and confused by all the magic handling around the `__init__` and `__new__` methods, so I spent a lot of time playing with the code to figure out how it works just enough to disable it.  However, I'm now dependent on a modified local copy of pdoc, which is unfortunate.

It would be convenient if it were instead implemented as an official option.

I created a mini-project to demonstrate what I mean:
https://github.com/odigity/pdocdemo/tree/main/testcases/constructors

I created a module [testmodule.py](https://github.com/odigity/pdocdemo/blob/main/testcases/constructors/testmodule.py) with every permutation to test, and added before/after screenshots, which I'll inline at the bottom for convenience.

Here's the commit showing what I changed in my local copy of pdoc:
https://github.com/odigity/pdocdemo/commit/46567cbc6cc0ba49aac6a524f6acbe37a452298b 

Specifically:
* Stopped pdoc from treating an inherited `__init__` as if it's part of the inheriting class.  (`doc.Class._declarations`)
* Stopped pdoc from playing with the identity and docstrings of `__new__` vs `__init__`. (`doc.Class._member_objects`)
* Stopped pdoc from presenting `__init__` as a constructor named after the class with no `self` in signature.  (`function` and `nav_members` macros in module template)
* Removed "Inherited Members" section. (`module_contents` block in in module template)

In principle, what I want to achieve is for the docs to actually reflect the source.  If I define a custom `__init__` in a class, I want it to show up in the docs - otherwise I don't.

As for the "Inherited Members" section - I primarily removed it to reduce visual noise, though putting it into a pre-collapsed section that can be manually re-opened might be an option I explore in the future.  The other reason is because the `is_public` macro still treats `__init__` as public - I didn't change that because I agree with it - but it means that almost every "Inherited Members" section now shows `__init__`, which is noisy because it adds no value.

Sorry for the ramblefest.  Hope it made sense.

EDIT:  I should mention these docs are for internal use (to document our own Django project), not user-facing, like docs for a library would be.  That may explain why my preferences are slightly out of alignment with the defaults.

![before](https://user-images.githubusercontent.com/155179/139958655-2639eb8a-daa0-4787-81d1-d7f3f9f4558f.png)
![after](https://user-images.githubusercontent.com/155179/139958650-7d24732d-062c-4237-bf97-3831f6d83713.png)

**Comment by mhils** [comment]
Hi @odigity! Thanks for the detailed description and screenshots, I appreciate it. 😃  

The current handling of `__new__` and `__init__` is based on how Python's builtin `inspect` module is handling things. I agree it's complicated, but unfortunately necessary to properly render dataclasses, enums, some C extensions, and a few other shenanigans that have non-standard constructors. If you rerender our snapshots tests (`test/test_snapshot.py`) with your fork you should see some examples of why we do this dance.

> In principle, what I want to achieve is for the docs to actually reflect the source. If I define a custom __init__ in a class, I want it to show up in the docs - otherwise I don't.

Could you give a practical example of a class where the current behavior is failing you?


> As for the "Inherited Members" section - I primarily removed it to reduce visual noise, though putting it into a pre-collapsed section that can be manually re-opened might be an option I explore in the future.

If you don't want inherited members to show up, you can override the [`inherited`](https://github.com/odigity/pdocdemo/blob/46567cbc6cc0ba49aac6a524f6acbe37a452298b/testcases/constructors/pdoc/templates/default/module.html.jinja2#L646) macro with an empty definition in a custom template (see https://pdoc.dev/docs/pdoc.html#editing-pdocs-html-template). I think this is a rather specific need, so I don't think we should add an option/increase the CLI surface/complexity for that.
