### ISSUE TITLE
Tables don't look nice

### ISSUE THREAD

**Issue by sitic** [mitmproxy/pdoc#315]
#### Problem Description
A table, e.g.

```
| Tables        |      Are      |  Cool |
| ------------- | :-----------: | ----: |
| col 3 is      | right-aligned | $1600 |
| col 2 is      |   centered    |   $12 |
| zebra stripes | are neat abcd |    $1 |

```

will display like this

![image](https://user-images.githubusercontent.com/423552/143316845-e2f69fa5-1b72-44a4-82ac-4249ce61a927.png)

which isn't particularly nice looking. Tables should be styled to look better, e.g. GitHub table styling:

| Tables        |      Are      |  Cool |
| ------------- | :-----------: | ----: |
| col 3 is      | right-aligned | $1600 |
| col 2 is      |   centered    |   $12 |
| zebra stripes | are neat abcd |    $1 |

#### System Information
`pdoc: 8.0.1`

**Comment by mhils** [comment]
Yes, I agree! I'd be happy to merge a PR that adds better table styling. :-)
