### ISSUE TITLE
command not found: pdoc

### ISSUE THREAD

**Issue by polakowo** [mitmproxy/pdoc#317]
Hi! 

Trying to run pdoc from terminal throws "command not found: pdoc".

Doing `ls /Users/olegpolakow/miniconda3/lib/python3.7/site-packages/pdoc` shows expected files but not `__init__.py` and `__main__.py`:

```plaintext
__pycache__       doc.py            doc_types.py      extract.py        render.py         search.py         web.py
_compat.py        doc_ast.py        docstrings.py     markdown2         render_helpers.py templates
```

```plaintext
pip show pdoc

Name: pdoc
Version: 8.0.1
Summary: API Documentation for Python Projects
Home-page: https://pdoc.dev/
Author: Maximilian Hils
Author-email: pdoc@maximilianhils.com
License: UNLICENSE
Location: /Users/olegpolakow/miniconda3/lib/python3.7/site-packages
Requires: astunparse, Jinja2, MarkupSafe, pygments
Required-by: 
```

**Comment by mhils** [comment]
How did you install pdoc? `__init__.py` and `__main__.py` are both in the wheel we distribute on https://pypi.org/project/pdoc/, so I'm a bit at a loss what could be causing this :)

**Comment by polakowo** [comment]
I first used pdoc3 but then upon discovering activity in the original version I wanted to give it a try. Seems like I installed pdoc without uninstalling pdoc3 first. I uninstalled pdoc3, reinstalled pdoc, and the issue is solved now. Thanks!
