### ISSUE TITLE
pdoc -o not working properly

### ISSUE THREAD

**Issue by abubelinha** [mitmproxy/pdoc#322]
#### Problem Description
I am a complete newbie. 
Just trying to see how pdoc works, with a single myscript.py file with some commented functions.
Tried different paths and scripts, with the same result.

#### Steps to reproduce the behavior:
1. pdoc ./path/to/myscript.py 
     runs OK: documentation is served from http://localhost:8080/path/to/myscript.html
2. pdoc -o ./output_path ./path/to/myscript.py 
    Raises this error (EDIT: although it generates the output files): 
```
c:\python38\lib\site-packages\pdoc\templates\build-search-index.js:5
let elasticlunr = require("./elasticlunr.min");
    ^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```
#### System Information
Paste the output of "pdoc --version" here:
```
pdoc: 8.0.1
Python: 3.8.7
Platform: Windows-7-6.1.7601-SP1
```

**Comment by mhils** [comment]
When rendering documentation to a directory, pdoc tries to precompile the search index to increase performance if `nodejs` or `node` are available on the system. This seems to fail on your system.

1. Could you please post the full output when invoking pdoc? Normally pdoc should catch search index compile errors and fall back to the raw search index.
1. Could you please open a PowerShell prompt and post the output of `Get-Command nodejs`, `Get-Command node`, `nodejs --version`, and `node --version`?

**Comment by abubelinha** [comment]
Thanks @mhils 
1. What do you mean with "full output"?  I already posted all the console output. Here it is again:
   COMMAND: `C:\python38\scripts\pdoc -o ./output_path ./path/to/myscript.py`
   OUTPUT (same output with different scripts and ./output_path):
```
c:\python38\lib\site-packages\pdoc\templates\build-search-index.js:5
let elasticlunr = require("./elasticlunr.min");
    ^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```    
2. I understand those should be 4 separated comands to run one by one. Right?
   If so, this is the output (error messages in Spanish, since I don't know how to change the Powershell language):
```
PS C:\python38> Get-Command nodejs
Get-Command : El término 'nodejs' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable. Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 12
+ Get-Command <<<<  nodejs
    + CategoryInfo          : ObjectNotFound: (nodejs:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

PS C:\python38> Get-Command node

CommandType     Name                                                Definition
-----------     ----                                                ----------
Application     node.exe                                            C:\Program Files\nodejs\node.exe


PS C:\python38> nodejs --version
El término 'nodejs' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable. Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 7
+ nodejs <<<<  --version
    + CategoryInfo          : ObjectNotFound: (nodejs:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\python38> node --version
v0.10.31
```

**Comment by abubelinha** [comment]
Added information: The error message made me open the issue, but it did not stop pdoc from generating its output:
So, the documentation files (index.html, search.js and myscript.html) were correctly generated at the `./output_path` folder.

Sorry I hadn't notice that. The error message made me think pdoc was simply failing.

I also believe the search bar is not working (in both server and output files). 
Not sure about how it should work, but whatever I type in it and hit return, nothing happens.
Is it somehow browser-specific?
Thanks

**Comment by mhils** [comment]
Ah, that clears up things - thanks! I think the error you are seeing is presumably because your Node.js version is too old to compile the search index. That's okay though, search should still work fine uncompiled. You should only get a note here for very large indexes. I've fixed the logic in 091eb44 and will push a release in a minute. :)

**Comment by abubelinha** [comment]
Thanks @mhils 
So I guess the error should also disappear if I uninstall node.js, shouldn't it? 

I am not a fluent Python programmer. 
I mostly use standalone .py scripts, which (at most) sometimes call functions from other .py scripts. 
But they are not structured into modules, projects or whatever.
I wonder if I still could use pdoc to generate .html doc files for some selected .py scripts in this context.

Do you have an example of how to use pdoc [as a library](https://pdoc.dev/docs/pdoc.html#using-pdoc-as-a-library) for this purpose?
I tried this:
```
import pdoc
myscripts = ["./thesis/catalog.py", "./names_parsers.py", "./text_functions.py"]
for myscript in myscripts:
	pdoc.pdoc(myscript, output_directory="./_mydocs")
```
But it fails:
```
Traceback (most recent call last):
  File "create_pdoc.py", line 12, in <module>
    pdoc.pdoc(myscript, output_directory="./_mydocs")
  File "C:\python38\lib\site-packages\pdoc\__init__.py", line 424, in pdoc
    write(doc_objects[module])
  File "C:\python38\lib\site-packages\pdoc\__init__.py", line 389, in write
    outfile = output_directory / f"{mod.fullname.replace('.', '/')}.html"
TypeError: unsupported operand type(s) for /: 'str' and 'str'

```

Actually, I wonder if that would be the right way to do it (calling pdoc one script at a time), if I want all the scripts to be shown in the index.html. Because each call would overwrite index.html
I suppose I should pass all the scripts in one call. I tried this from console and it worked:
`C:\python38\scripts\pdoc -o ./output_path ./myscript1.py ./myscript2.py ./myscript3.py
`

All the three scripts appear in the left menu of index.html 
But I don't know how to do the same using pdoc as a library.

**Comment by mhils** [comment]
> So I guess the error should also disappear if I uninstall node.js, shouldn't it?

If you upgrade to pdoc 8.1.0, the error will likely just disappear. If your search index becomes too large, a warning will reappear, but with clear messaging that it's not fatal - search performance is just degraded.

> But it fails:

You're passing a str as `output_directory`, which needs to be a `pathlib.Path`.

> But I don't know how to do the same using pdoc as a library.

The first argument is `*modules`, so you can do `pdoc.pdoc("./myscript1.py", "./myscript2.py", "./myscript3.py")`. See https://docs.python.org/3/tutorial/controlflow.html#arbitrary-argument-lists.

**Comment by abubelinha** [comment]
Thanks a lot @mhils . Now it works!
I leave the correction here, just in case someone else needs an example:

```Python
import pdoc
from pathlib import Path
myscripts = ["./myscript.py", "./path2/myscript.py", "./myscript3.py"]
pdoc.pdoc(*myscripts, output_directory=Path("./_mydocs"))
```

**Comment by abubelinha** [comment]
I have one related question about the html output after running the [above script.](https://github.com/mitmproxy/pdoc/issues/322#issuecomment-1002280227)
My script is located at `C:\Dropbox\python\create_pdoc.py` and I run it calling `C:\python38\python C:\Dropbox\python\create_pdoc.py`

As expected, output (3 html documents + index.html + search.js) is created in `C:\Dropbox\python\_mydocs`
And `index.html` left menu shows links to the 3 html in the same order they are in `myscripts` list, like this:
#### Available Modules
- Dropbox.python.myscript
- myscript
- Dropbox.python.myscript3

What I don't understand is the reason why the 2nd one (located inside path2) shows no path information, while the 1st and 3rd one (located in the same folder as my create_pdoc.py script) show the **full path** below C: (i.e. **Dropbox.python.**)
How can I control that? I would expect this result instead:
- myscript
- path2.myscript
- myscript3
