### ISSUE TITLE
search box odd behaviour

### ISSUE THREAD

**Issue by abubelinha** [mitmproxy/pdoc#323]
#### Problem Description
For some reason, search results disappear and reappear while typing words in search textbox.
Probably only happening with some particular text strings. I couldn't figure out why.

#### Steps to reproduce the behavior:
1. Create a script containing _[pypyodbc](https://pypi.org/project/pypyodbc/)_ string in some function names, plus some other scripts.
2. Create their documentation with `pdoc`
3. Start typing that _pypyodbc_ name in `pdoc`'s search box
4. In my case, search results disappear when I type the 4th letter (_pypy_) and reappear after typing one more

> 65 search results for 'p'.
> 63 search results for 'py'.
> 5 search results for 'pyp'.
> No search results for 'pypy'.   <-------  ???
> 5 search results for 'pypyo'.
> ...
> 5 search results for 'pypyodbc'.

#### System Information
Paste the output of "pdoc --version" here.
```
pdoc: 8.1.0
Python: 3.8.7
Platform: Windows-7-6.1.7601-SP1
```

**Comment by mhils** [comment]
Can you please provide an example script that exhibits that behavior?

**Comment by abubelinha** [comment]
In my case I need at least two scripts for the search box to work.

### pdoc_search_fails_1.py
```
#!/usr/bin/python
# -*- coding: utf-8 -*-

def pypyodbc_query(connection_string, sql_query):
	""" launches sql queries """
	import pypyodbc
	# some other code
```
### pdoc_search_fails_2.py
```
#!/usr/bin/python
# -*- coding: utf-8 -*-

def main():
	""" calls pypyodbc and launch sql query """
	from pdoc_search_fails_1 import pypyodbc_query
	# some other code
	
if __name__ == "__main__":
	print("Hello World")

```	
### generate documentation:

`pdoc -o ./output_path ./pdoc_search_fails_1.py ./pdoc_search_fails_2.py
`

**Comment by mhils** [comment]
Thanks! I fixed the incorrect search results in 6a1207a432b31d5deda891ba76df4ed9d06797a0 and then the single-module issue in  990b9b7e8412a9f277188e1b0a68b83f9c28d55d. 😃

**Comment by abubelinha** [comment]
Wow, you are really fast!
Thanks for fixing the single-module issue 
(the _pypy_ bug was more a curiosity, but nothing really annoying).

**Comment by abubelinha** [comment]
I have found new odd behaviours of search bar, using other search strings.
I have this function definition in my pdoc generated documentation:

script name: sendgmail.py
`def sendyagmail(gmailusername, gmailpassword, to, subject, contents)`

When I type "sendyagmail" in search bar, search results dissapear when the typing reaches "sendy", and then reappear after typing next character ("sendya...")

I take the opportunity to ask ... would it be possible to improve search bar so I also finds text in the middle of words?
(for example, typing "yagmail" to find the above function)

**Comment by mhils** [comment]
I cannot reproduce that issue on 8.2.0:

![image](https://user-images.githubusercontent.com/1019198/148811985-4636f455-3592-41e2-823a-76f0adb263f6.png)

> I take the opportunity to ask ... would it be possible to improve search bar so I also finds text in the middle of words?

I'm pretty sure you cannot do this with http://elasticlunr.com/, which is what we use. I'd be happy to look at PRs that propose different search engines, but let's say it's all but trivial.

**Comment by abubelinha** [comment]
I feel ridiculous @mhils but you are right: I had forgotten to upgrade pdoc in this computer (was still on 8.1.0)
Sorry about that.

> I'm pretty sure you cannot do this with http://elasticlunr.com/, which is what we use.

This sounds a bit ridiculous too, but after upgrading to pdoc 8.2.0 ... typing "yagmail" **I can** find `sendyagmail` function.
But I can't find many other functions by substrings in the middle of their names. 

I must be misunderstanding how [search box](https://pdoc.dev/docs/pdoc/search.html) works. What parts of my source code does it include in searches?
If it searches the whole function, as it contains "`import yagmail`", this would explain that behaviour.
But oddly, if I type one of its arguments (i.e. `gmailusername`, `gmailpassword`, ...) search box finds nothing.

Could you document this a bit, with examples of which searches should work and which should not?

**Comment by mhils** [comment]
> What parts of my source code does it include in searches?

See 5d32ea9f1320b39e8de7e28398da1d18eec85834.

**Comment by abubelinha** [comment]
> The search functionality covers all documented elements and their docstrings.
> You may find documentation objects using their name, arguments, or type annotations; the source code is not considered.

Thanks for clarification.
If arguments are searchable, I guess there is still some other bug.
In the same example above: it's not finding strings `gmailusername` or `gmailpassword`, which are arguments for the aforementioned `sendyagmail()` function.

**Comment by mhils** [comment]
Only on main, that's not yet in 8.2.0. :-)

**Comment by abubelinha** [comment]
I installed 8.3.0 ... much better, thanks !!

> The search functionality now also covers function parameters, annotated types, **_default values_**, and base classes.

Yes, that's true. Now I can find this function searching by the strings "myho" or "654":
`def myfunction(home='myhome', phone=654321012)`

But, oddly, this only works _sometimes_. It does not work for all my functions.
Try this:

#### myscript0.py
```Python
#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
This is myscript0.py
"""
def my_function0(saytext='Blahblahblah', saynum=654321012):
	""" I am **NOT** inside a subpath """
	pass
		
if __name__ == "__main__":
	my_function()
```	
#### myscript.py

```Python
#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
This is myscript.py
"""

def my_function(saytext='Blahblahblah', saynum=654321012):
	""" I am **NOT** inside a subpath """
	pass
		
if __name__ == "__main__":
	my_function()
```	
#### ... and then:
```Python
	import pdoc
	from pathlib import Path
	myscripts = ["./myscript0.py", "./myscript.py"]
	pdoc.pdoc(*myscripts, output_directory=Path("./_mydocs"))
```
#### Bugs:
- Default values search (i.e. "Blah" or "654") does not work for these functions.
- Search box keeps doing odd things (results disappear mysteriously). Not very annoying, though:  
   "myscript" vs "my" vs "my_f" vs "my_"
   "say" vs "sa"

pdoc: 8.3.0
Python: 3.8.7
Platform: Windows-7-6.1.7601-SP1

**Comment by mhils** [comment]
Thank you for the useful feedback again, I've just pushed some additional improvements to the search functionality. The issues you have mentioned are fixed on main now. :)
