### ISSUE TITLE
how to call pdoc after installing pdoc3 (or how to install pdoc3 without predating pdoc's name)

### ISSUE THREAD

**Issue by abubelinha** [mitmproxy/pdoc#324]
#### Problem Description
This is not a bug. My pdoc installation was running OK.
Then I just discovered a fork called pdoc3, and tried to install it to understand their differences (if there are any).

Now I am confused about how should I call one or the other either from CLI or as a library. 
Is there a way to install one package which uses the same name, without affecting the previously installed one?

#### Steps to reproduce the behavior:
1. `pip install pdoc`
   `Successfully installed pdoc-8.1.0`
2. `c:\python38\scripts\pdoc --version`
```
pdoc: 8.1.0
Python: 3.8.7
Platform: Windows-7-6.1.7601-SP1
```
3. pip install pdoc3
`Successfully installed pdoc3-0.10.0`
4. `c:\python38\scripts\pdoc --version`
  `pdoc.exe 0.10.0`
5. OK. How can I call "the real pdoc" now ??

#### System Information
Paste the output of "pdoc --version" here.
```
pdoc: 8.1.0
Python: 3.8.7
Platform: Windows-7-6.1.7601-SP1
```
Well ... this was before installing pdoc3 (see above)

**Comment by mhils** [comment]
"pdoc3" unfortunately hijacks the `pdoc` binary name, I'm afraid you cannot install both into the same Python environment.

For a comparison between the two see https://github.com/mitmproxy/pdoc#pdoc-vs-pdoc3.

**Comment by abubelinha** [comment]
Thanks again @mhils 
Looks like there is no good feeling between both projects. But there is no technical comparison in that link, other than moral or legal aspects.

I was looking for a comparison of software technical features.

Regarding name hijacking ... is this “legal”?
First time I see two pip projects conflicting like this.
Nobody controls pip to avoid me from developing a project, putting on pip and use the same name of another extant pip project??

**Comment by mhils** [comment]
> I was looking for a comparison of software technical features.

I don't think pdoc has to shy away from a comparison (quite the opposite), but the comparison criteria picked by either party would be highly subjective. The statement I linked above is really all that needs to be said.

**Comment by abubelinha** [comment]
Thanks for your comments.

I'll stick to pdoc (my requirements are so simple), but I was wondering about pdoc3 motivations 
It should have some features which are not available in pdoc ... otherwise I just can't understand why somebody would bother in maintaining such a fork.

It must be my little python experience, but I can't either understand how this name confussion can happen (new projects added to pip which hijack other packages' names).
