### ISSUE TITLE
link to a function inside a file (get function's name) when I only know a line number inside that file

### ISSUE THREAD

**Issue by abubelinha** [mitmproxy/pdoc#327]
#### Problem Description
As a Python newbie, my functions contain not only documentation strings below function definition.
I also use to insert some tips (`# _TIP` marks) about how-to-do something in Python, the first time I use that kind of code.

```Python
# file myscript_A.py
def myfunction1():
    """ my documentation """
    mylist = ["Jane", "John", "Jennifer"]
    surname = "Johanssen"
    # _TIP: list comprehension
    fullnames = [name+" "+surname for name in mylist]
...
def myfunction5():
    """ my documentation """
    import pandas as pd
    # _TIP: pandas dataframe merging
    pd.read_csv(...)

# file myscript_B.py
def myfunction22():
    """ my documentation """
    # my code
    # my code
    # _TIP: whatever
    # my code
    # my code
...
```
#### Proposal
I have created a `tips_collector.py` script, which reads a list of given python scripts content, locates all lines containing "`# _TIP`" marks, and generates a `my_tips.html` file like this:
- **myscript_A.py** [line 6]: _list comprehension_ 
- **myscript_A.py** [line 165]: _pandas dataframe merging_ 
- **myscript_B.py** [line 87]: _whatever_ 

As I have the line numbers and I also have pdoc-generated html documentation for each of these scripts, I would like to improve `my_tips.html` file including links to open documentation of container function for each of those tips.
I would take profit of anchor marks generated by pdoc (i.e. `<a href=./myscript_A.html#myfunction1>list comprehension</a>`), like this:
- **myscript_A.py** [line 6]: _[list comprehension](myscript_A.html#myfunction1)_ 
- **myscript_A.py** [line 165]: _[pandas dataframe merging](myscript_A.html#myfunction5)_ 
- **myscript_B.py** [line 87]: _[whatever](myscript_B.html#myfunction22)_ 

Obviously, to do this I need a way to get the function name which contains a given line of code inside a given script file.
So `get_function_name("myscript_A.py", 165)` should return `"myfunction5"`:
```Python
def get_function_name(script_name, line_number):
    # what should I do here?
    return(function_name)
```
#### Alternatives
I think these issues and concepts are somehow related, but I would need some examples so I can connect them to my specific problem:
[#268 Get line number of classes and functions](https://github.com/mitmproxy/pdoc/issues/268)
[Doc.source_lines](https://pdoc.dev/docs/pdoc/doc.html#Doc.source_lines)

#### Additional context
I am generating my pdoc html documents using the approach described in #325

**Comment by mhils** [comment]
I don't think your question is much about pdoc really. If I understand you correctly, it looks like you want to get the function name containing a specific line? pdoc only provides you with documentation object -> source lines data, not the other way around. So you can search through the pdoc tree, or build your TIP list by going through the tree and using [Doc.source](https://pdoc.dev/docs/pdoc/doc.html#Doc.source). But in either way it's not really a pdoc question. :)

**Comment by abubelinha** [comment]
Yes, your are right, but I don't know how to add a "question" or "help" label (instead of the default "bug" and "enhancement").

I am just asking for advice on how to do it, because I don't see many example scripts so I can figureout how to do "go through the tree and using Doc.source".  Any hints/links about Doc.source usage examples?

**Comment by abubelinha** [comment]
@mhils I finally discovered your [library-usage](https://github.com/mitmproxy/pdoc/blob/main/examples/library-usage/make.py) example. Some more examples like that would be great.
Its existence was not obvious to me (I suggest you to link it under [using-pdoc-as-a-library](https://pdoc.dev/docs/pdoc.html#using-pdoc-as-a-library) section).

I adapted my #325 `create_pdoc.py` (generates html docs from a script list to an output folder, in just one call) in order to process the same individual scripts one by one.
As they are standalone scripts, and not well-structured Python modules, I tried to do it this way:
```Python
import pdoc
myscripts = ["./myscript.py", "./path2/myscript.py", "myscript3.py"]
for script in myscripts:
    # - This is how I was generating output documentation:
    #    pdoc.pdoc(script) # returns HTML content, but I need a doc object instead !!!
    # - This is your example:  doc = pdoc.doc.Module(foo)
    #    doc = pdoc.doc.Module(script) # raises error: AttributeError: 'str' object has no attribute '__name__'
    # ... so I needed a way to import Python modules using variable names, like suggested here:
    #     https://stackoverflow.com/questions/24940545/import-modules-from-a-list-in-python
    modulename = script.split(".py")[0].split("/")[-1]
    foo = __import__(modulename)
    doc = pdoc.doc.Module(foo)
    # ... I guess now I can access doc.own_members list, to find out start/end lines of each function
```
Do you suggest a better/simpler way of doing this?

**Comment by mhils** [comment]
Everything that works is good, really. My recommendation would be to
simply do `import myscript` and then call `pdoc.doc.Module(myscript)`. This requires that all your modules are normally importable, but that's generally useful in either case. But again, your approach works as well.

**Comment by mhils** [comment]
No, I would to straight imports. Assuming your files are `foo.py` and `bar.py`, I would recommend to do the following:

```python
import foo
import bar
import pdoc

for mod in [foo, bar]:
    x = pdoc.doc.Module(foo)
```

No imports of variable values. :)

**Comment by abubelinha** [comment]
I guess you meant `x = pdoc.doc.Module(mod)`

For a handful of scripts, that would indeed be simpler. 
But my number of files is rather long, so I guess a list is easier to control (no risk to forget an `import` call, or to forget its name in the loop).
I think I'll put the pdoc loop code in a function and pass the files list and output folder as parameters.

Thanks a lot anyway!

**Comment by abubelinha** [comment]
The script I had described [above](https://github.com/mitmproxy/pdoc/issues/327#issuecomment-1005600421) has been running OK, with some more code which I show here:
```Python
import pdoc
myscripts = ["./myscript.py", "./path2/myscript.py", "myscript3.py"]
for script in myscripts:
    modulename = script.split(".py")[0].split("/")[-1]
    foo = __import__(modulename)
    doc = pdoc.doc.Module(foo)
    # ... I guess now I can access doc.own_members list, to find out start/end lines of each function
    for memb in doc.own_members: # iterate functions inside script module, and creates links for them
	    print ("  *  ",memb.name, memb.fullname, str(memb.source_lines))
	    link=memb.fullname.replace(".",".html#")
	    row = memb.fullname.split(".") # adds module name and function name to my row
	    row.extend(list(memb.source_lines)) # Line 187: adds function's start/end lines to my row
            # code continuates ... I will output each row to a .csv file containing all my functions
```
But today I added a new file (diff.py) to `myscripts` list, and this caused an error on last line of the above code:

```
 pdoc.doc.Module(diff.py) is a  <class 'pdoc.doc.Module'>
  *   compara diff.compara None
Traceback (most recent call last):
  File "abu_pdoc.py", line 487, in <module>
    create_docs()
  File "abu_pdoc.py", line 187, in create_docs
    row.extend(list(memb.source_lines))
TypeError: 'NoneType' object is not iterable
```
I looked at `diff.py` source code but there was nothing odd in it, other than this was an ANSI encoded file.
I changed it to UTF8 and then the above error disappeared.
@mhils any idea about why did this happen?  
Is there anything wrong with using pdoc on ANSI encoded files, or should I open an issue just in case this might be some kind of pdoc's bug?

Thanks!

**Comment by mhils** [comment]
@abubelinha: If you look at pdoc's own implementation you can see that we just call `inspect.getsourcelines` internally. If there is a bug it's a bug upstream, it's not a pdoc issue.  https://github.com/mitmproxy/pdoc/blob/5747b240b6829b6f9a2be287acb3eda684dba427/pdoc/doc.py#L155-L166

**Comment by abubelinha** [comment]
Sorry, but I don't understand what you mean by "a bug upstream".  
Does that answer whether pdoc can or cannot handle files with different encodings?

It is clear to me that both `memb.name` and `memb.fullname` had content, but `memb.source_lines` is empty (2nd `print` line):
```Python
print ("  *  ",memb.name, memb.fullname, str(memb.source_lines))
```
`  *   compara diff.compara None` 

So it looks like to me that pdoc was able to read a module and a function, but not the source code inside that function.
I don't understand why this happens, but it is something related to file encoding.

FYI some of the strings inside the function source code contain accented vowels.
Perhaps related to #21 somehow?

**Comment by mhils** [comment]
pdoc uses [`inspect.getsourcelines`](https://docs.python.org/3/library/inspect.html#inspect.getsourcelines) from Python's standard library to implement this functionality. If pdoc is unable to get the source lines, it's a limitation of Python's stdlib. It's nothing we can change in pdoc.

**Comment by abubelinha** [comment]
I know you already said this is not a pdoc's bug.  But please read again what I said.  
I wasn't / am not asking you to change pdoc in any way.

I don't want to bother either. 
I am just reporting an issue that happens, and _asking_ whether pdoc is supposed to be able to create documentation from ANSI encoded files, or not.   
I tried to look for this particular info in pdoc's documentation, but I think there is nothing said about this.
So that's the reason I am asking it again. I hope you have an answer.

I am a Python newbie and I don't know how frequent it is people using files in different encodings.
But I am pretty sure it is not uncommon people using accented characters inside source code.

Thanks a lot in advance

**Comment by mhils** [comment]
> asking whether pdoc is supposed to be able to create documentation from ANSI

Probably? I don't know. I've never checked it, but I also don't consider it to be a particularly interesting or relevant question. You should really just be using UTF-8, which is the default encoding and supports all the accents/emojis/... you want.

> I am a Python newbie and I don't know how frequent it is people using files in different encodings.

I haven't seen a single non-UTF8 Python source code file since switching to Python 3, and I also can't think of a good reason to pick something else.

**Comment by abubelinha** [comment]
I don't "pick" non-UTF8 files on purpose. I am just documenting a bunch of files I have.

Some are newly created, most are old, some are mine, most are not.
Actually I don't know where my problematic ANSI file came from, but most probably I downloaded it from github or I re-used a .py file to create a new one ... so I bet that's not so odd to find a non-UTF8 file.

Well, maybe you have an editor which shows encoding in a different color or something alike, but as for me, I had really no idea about this file encoding until I hit this problem.

Even if you know having an ANSI file hapens <0.1% of users, I think answering "don't use ANSI files" is the best answer you could have given me to not spending your time (that was my question, which you didn't answer until now).

Bye

**Comment by abubelinha** [comment]
I don't "pick" non-UTF8 files on purpose. I am just documenting a bunch of files I have.

Some are newly created, most are old, some are mine, most are not.
Actually I don't know where my problematic ANSI file came from, but most probably I downloaded it from github or I re-used a .py file to create a new one ... so I bet that's not so odd to find a non-UTF8 file.

Maybe you have an editor which warns you about non-utf8 encoding in a different color or something alike? 
As for me, I had really no idea about this file encoding until I hit this problem (I was assuming it was utf8 because that's the default encoding of my Notepad++ editor).

If you know having an ANSI file occurs to less than 0.1% of users, and you expect all pdoc-submitted files to be utf8 encoded, then I think "don't use ANSI files" should have been your 1st answer to stop spending your time -and mine- (that was my question, and nothing else).

> I haven't seen a single non-UTF8 Python source code file since switching to Python 3, and I also can't think of a good reason to pick something else.

So now we have 1. For our statistics.

> I also don't consider it to be a particularly interesting or relevant question

I just knew about issues. I didn't know you had a ranking of "interesting or relevant questions". 
But thanks for letting me know.
