### ISSUE TITLE
Force pdoc to generate documentation for __get__?

### ISSUE THREAD

**Issue by leotrs** [mitmproxy/pdoc#33]
Attached is a simple example where pdoc doesn't generate documentation for the `__get__` method of a class. My guess is this method is considered not public, which seems reasonable.
Is there a way to force pdoc to process it still?

```
class Base(object):
    def __init__(self):
        """Constructor."""
        self.x = 1

    def __get__(self, instance, owner):
        "Set method."
        return self.x
```

And the output:

```
leo@lily:~/$ pdoc test.py
Module test
-----------

Classes
-------
Base 
    Ancestors (in MRO)
    ------------------
    test.Base
    __builtin__.object

    Instance variables
    ------------------
    x

    Methods
    -------
    __init__(self)
        Constructor.
```

**Comment by mhils** [comment]
I'm closing this as a wontfix, see #24 for a possible workaround. If this request becomes more popular, we may make a variant of `_is_exported` part of the public API. :)
