### ISSUE TITLE
Please remove the allegation about Nazi symbolism from the README

### ISSUE THREAD

**Issue by saifkhichi96** [mitmproxy/pdoc#330]
In the README, it is suggested that @kernc has associated this project with Nazi symbols by including a swastika on the fork of this project. As has already been addressed in this [comment](https://github.com/pdoc3/pdoc/issues/64#issuecomment-489370963), that is not true.

Despite most strongly being associated with the Nazi Party today, the swastika was and remains an important symbol in many religions and cultures. There are two types of swastikas, a right-facing and a left-facing one. The Nazis used the right-facing swastika as their emblem. In Buddhism, a left-facing swastika symbolises the footprints of the Buddha. You can learn more about this [here](https://en.wikipedia.org/wiki/Swastika#Historical_use).

I am not going to include the symbol itself or any screenshots or images here, but if you look closely, [`pdoc3`'s website](https://pdoc3.github.io/pdoc/) clearly uses the Buddhist swastika in its footer, and your suggestion that it has something to do with Nazism is disgusting and offensive to the people who follow Buddhism. Not to mention to other Asian cultures and religions like Hinduism which use and have used both left- and right-facing swastikas for thousands of years in ways that has nothing to do with what happened in Europe less than a century ago.

It is understandable that you are upset, and rightly so, on the illegal and wrong way in which your project was impersonated, relicensed and removed from Wiki, but your continued assertion that the Buddhist swastika is a Nazi symbol is causing hurt to millions of people around the globe. I would like to request that you remove that particular accusation from the README, and instead highlight any ethical misconduct perpetrated by the `pdoc3` team.

**Comment by mhils** [comment]
If you look closely, you will see that the pdoc3 website does also include a right-facing swastika. The maintainer's avatar old GitHub avatar used to be a big right-facing swastika as well, https://pypi.org/project/pdoc3/ still features it. 

I know that the maintainer claims that they don't intend for it to be offensive, and I'm aware of the use of this symbol in many eastern spiritual traditions. That being said, they must be aware of the unpleasant connotations that this will have for people, and not everyone is going to dig in to see what the claimed intent behind their use is.

**Comment by FergusInLondon** [comment]
I’m sorry, but that’s a really disappointing response @mhils. If anything it’s even _more offensive_.

I’m struggling to understand how you can claim to understand the cultural significance of the symbol (not to mention the maintainers true intentions):

> I know that the maintainer claims that they don't intend for it to be offensive, and I'm aware of the use of this symbol in many eastern spiritual traditions.

Yet continue to purposefully conflate the symbol with something quite evil and abhorrent:

> That being said, they must be aware of the unpleasant connotations that this will have for people, and not everyone is going to dig in to see what the claimed intent behind their use is.

All I have taken from the above is that (a) despite an awareness of the significance that this symbol has for millions of people, you’re  (b) willing to continue reinforcing connotations of evil.

Perhaps you’ve made the most pertinent point yourself:

> and not everyone is going to dig in to see what the claimed intent behind their use is.

Quite right in that many people are not going to dig in to the specific details of this situation; and with that in mind it’s precisely the reason why some caution should be employed when making the kind of accusations seen here, and why effort should be made not to equate culturally significant symbols with ones of hatred.

Whilst this issue has been closed, I’d still urge you to reconsider the points that @saifkhichi96 so respectfully made. The conduct of the maintainer in question may have been poor, but with perspective the conduct here is also very poor.

**Comment by saifkhichi96** [comment]
Thank you for saying this, @FergusInLondon. I rather myself felt a bit offended by the response, and disappointed at how the issue was closed immediately with a comment without having any meaningful discussion about it. But I figured that it was clear that @mhils was not interested in considering perspectives other than their own, and that they felt that the default interpretation of the symbol should be the most evil one (probably because that evil interpretation is most closely related to their own geography or culture).

Even though the original author who posted those symbols has explained that he is from a Buddhist culture and for him, the symbol has a different meaning, just like it does in many other cultures too. I think that the continued publication of this allegation is unfair and rather insulting to Buddhism and all other cultures that use swastikas in any form. I feel like this is because of resentments stemming from attempted impersonation and attempted theft of `pdoc`, which is a completely separate issue and should be treated as such.

I didn't say anything before because it was made clear by how the issue was unceremoniously closed that my concern was not welcomed here .

**Comment by FergusInLondon** [comment]
> f you look closely, you will see that the pdoc3 website does also include a right-facing swastika. The maintainer's GitHub avatar used to be a big right-facing swastika as well, https://pypi.org/project/pdoc3/ still features it.

I think you’re showing a bit of naïveté here, as I don’t think that means what you think it does. Otherwise this UK council would be very embarrassed:


![](https://ichef.bbci.co.uk/news/976/mcs/media/images/73201000/jpg/_73201579_swastika.jpg)

**Comment by FergusInLondon** [comment]
> Thank you for saying this, @FergusInLondon. I rather myself felt a bit offended by the response, and disappointed at how the issue was closed immediately with a comment without having any meaningful discussion about it.


No worries @saifkhichi96. The response you received to this issue was very disappointing, but hopefully @mihls will reconsider - his attitude on other issues is generally brilliant, appearing more helpful than most. It’s a real shame as the solution you presented - namely amending the README to present the facts, and not to cause offence by wilfully conflating the two symbols - would solve everything.

In the 7 years I’ve been a member of GitHub I don’t think I’ve ever reported a single thing, so it was surprising to report a project that I actually use this evening. Without meaningful dialog I don’t see any other option though.

I’m fortunate enough that I see this kind of symbolism regularly - despite living in the UK it’s common ([examples](https://www.bbc.com/news/uk-england-26369329)). I get the impression that it’s very different in parts of the US and Central Europe, which is where the misunderstandings happen - and as a result there’s a complete lack of awareness/sensitivity. 

> I feel like this is because of resentments stemming from attempted impersonation and attempted theft of pdoc, which is a completely separate issue and should be treated as such.

Originally I think it began from a place of [cultural ignorance](https://archive.is/xsJhm), I’m not sure whether it continued out of embarrassment or vindictiveness, but there was some pretty awkward ~lying~ avoidance [even when directly called out](https://archive.is/0IMwY). Whichever reason was behind it, the end result is the same - reinforced negative connotations for something sacred, and further erasure of a something significant for many.

Either way, there’s no excuse to enter 2022 refusing to do the right thing. I’d like to think that perhaps having read your issue again, and having had a chance to reconsider the facts and wider context, then the README can be updated.

As a gesture of sincerity and goodwill I’d be more than happy to open a Pull Request tomorrow that amends the README to remove the references to nazism, and focuses on the actual issues - a hostile fork which relicensed the codebase, and then falsely masqueraded as the original project.

**Comment by mhils** [comment]
Look - our point here is to foster an inclusive atmosphere. I strongly believe that prominently featuring a swastiska is at odds with this goal. The same would be true for any other symbol that has unpleasant connotations for a large part of the audience, no matter how well-intended it is.

I think it's absolutely fair to call him out for associating the project with symbols that many understand as Nazi symbols. 
Here's [Wikipedia](https://en.wikipedia.org/w/index.php?title=Fascist_symbolism&oldid=1068944800) (emphasis mine):

> Although the swastika was a popular symbol in art prior to the regimental use by Nazi Germany and has a long heritage in many other cultures throughout history - and although many of the symbols used by the Nazis were ancient or commonly used prior to the advent of Nazi Germany - because of association with Nazi use, **the swastika is often considered synonymous with Nazism** and some of the other symbols still carry a negative post-World War II stigma **in Western countries**, to the point where some of the symbols are banned from display altogether.

With all due respect, the pdoc3 author is not from a region where Buddhism is prevalent, he's from Central Europe. All evidence points in the direction that his use of swastiskas is just another means to troll (["Made you look. 😁"](https://archive.ph/cJjve)). I don't want to be associated with that form of trolling.

That being said, I appreciate your concerns. We will discuss this with the rest of the @mitmproxy folks internally, and I will also gather some more international opinions. For now I will lock things here as the discussion is getting too heated. I know this may be frustrating for you, sorry about that.
