### ISSUE TITLE
Function return-type links are not clickable in Chrome or Edge

### ISSUE THREAD

**Issue by ginty** [mitmproxy/pdoc#332]
#### Problem Description
The links in the return-type from functions are not clickable in the Chrome and Edge browsers.

Here is an example of the generated HTML and the "signature" span contains the link that doesn't work:

```html
<div class="attr function">
  <a class="headerlink" href="#MemoryMap.callback">#&nbsp;&nbsp;</a>
  <span class="def">def</span>
  <span class="name">callback</span>
  <span class="signature">(self) -&gt; <a href="#RegisterHandler">pgf.model.memory_map.RegisterHandler</a></span>:
</div>
<details>
   <snip>
</details>
```

I don't know enough about CSS to say exactly what the problem is, but the details tag seems to be overlapping the function signature such that the browser doesn't recognize that you're hovering over the link.

It does work OK in Firefox and this may be a result of a recent change in Chrome behavior.

#### Steps to reproduce the behavior:
Just generate some docs where a function returns a type that is defined in the same project.

#### System Information
pdoc: 8.2.0
Python: 3.7.12
Platform: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-Ubuntu-20.04-focal

**Comment by ginty** [comment]
Hi @mhils, yep I can confirm that it looks good to me too on latest main branch.

Thanks a lot for your work on Pdoc, it's great!

**Comment by mhils** [comment]
Excellent, let's get this out for everyone then! CI is running, 8.3.0 should be out of the door in a few minutes. :)
