### ISSUE TITLE
Edit link has wrong label

### ISSUE THREAD

**Issue by dAnjou** [mitmproxy/pdoc#333]
#### Problem Description
I'm hosting my repo on GitLab, but the edit link says GitHub.

#### Steps to reproduce the behavior:
1. Configure edit url:
```python
pdoc.render.configure(
    edit_url_map={
        "codefs": "https://gitlab.com/dAnjou/fs-code/-/blob/main/src/codefs/",
    },
)
```
2. Generate docs

#### Expected behavior

Edit link says `Edit on GitLab`.

#### Actual behavior

Edit link says `Edit on GitHub`.

**Comment by mrossinek** [comment]
Hi @dAnjou! The button label is not being inferred automatically from the URL which you provide. Instead, you can customize the text by using a custom `module.html.jinja2` template including a section like the following:
```html
{% block edit_button %}
    {% if edit_url %}
        <a class="pdoc-button git-button" href="{{ edit_url }}">Edit on GitLab</a>
    {% endif %}
{% endblock %}
```

I am doing the same [here](https://gitlab.com/mrossinek/cobib/-/blob/master/html/module.html.jinja2#L50). Hope this helps!

**Comment by dAnjou** [comment]
Thanks, it does. But I'd consider it a hack-around :P

**Comment by mhils** [comment]
Hi fellow Maxes,

I'd be happy to merge a PR that adds a simple conditional here to pick a proper string:
https://github.com/mitmproxy/pdoc/blob/88d3b88049d90498420fc305e8ed06999241c04a/pdoc/templates/default/module.html.jinja2#L780-L784

My suggestion would be we display "Edit on GitHub" if `edit_url` contains `github.com`, "Edit on GitLab" if `edit_url` contains gitlab.com, and simply "Edit Source" for everything else.

**Comment by dAnjou** [comment]
> Hi fellow Maxes,

That's awesome 😂

> adds a simple conditional 

I'd keep it simple and as generic as possible. I also have some doubts that "edit" is the best term here, because most people who read the documentation probably have no permission or even intention to edit the code.

I know there has been some friction with that project but I kinda like the phrasing in pdoc3: "Browse Git", but even that assumes Git. So maybe "Browse source" or "Browse repo" would be good.

**Comment by mhils** [comment]
The "Edit on GitHub" phrasing originates from `sphinx-rtd-theme`, see for example on https://docs.readthedocs.io/en/stable/. 
The motivation for this button is that people can use it to propose changes to the page they are currently viewing with little effort. For example, here's a PR where someone read the mitmproxy docs, spotted a typo, and immediately proposed a fix: https://github.com/mitmproxy/mitmproxy/pull/5062/. Having "GitHub" in the message signals to the reader that this will be a familiar and low-effort process (assuming they have a GitHub account). Long story short, I think there's strong precedent for the "Edit [on GitHub]" wording and I would like to keep it that way. 

I feel that a "Browse repo" button should much rather point to the repo root and not to individual files. The full source code is also already available as part of the pdoc page. I would be happy to also accomodate GitLab users here, but we want to optimize for the common case (GitHub), where I think the "Edit on GitHub" wording is better.

**Comment by dAnjou** [comment]
> The motivation for this button is that people can use it to propose changes to the page they are currently viewing with little effort.

I remember/realize now 🙈  I was a bit confused because pdoc3's idea and implementation is kinda similar but also different.

Anyway, looking at it less confused now, I can see how "Edit on ..." makes sense.

I still think it'd make sense to make the label configurable, because there's already configuration needed for the button to show up.

**Comment by mhils** [comment]
> I still think it'd make sense to make the label configurable, because there's already configuration needed for the button to show up.

I think @mrossinek already shared a good way how you can configure the label in https://github.com/mitmproxy/pdoc/issues/333#issuecomment-1013763332, and this approach will continue to work. I've set a relatively high bar for adding new CLI configuration switches to pdoc, my goal is to keep things simple where we can (you may be familiar with the German term *Eierlegende Wollmilchsau* — we try to avoid that here). 

a20bee8 adds the "Edit on GitLab"/"Edit Source" wording, which should hopefully fix things for 99% of the use cases. Thank you two again for the feedback and for sharing your approaches! :) 🍰
