### ISSUE TITLE
Ignored module still shows up in submodules

### ISSUE THREAD

**Issue by dAnjou** [mitmproxy/pdoc#334]
#### Steps to reproduce the behavior:
1. Have a project like this:
![Screenshot 2022-01-16 at 00 35 21](https://user-images.githubusercontent.com/117147/149641133-b74fd4b9-e7cc-484c-9e47-065eec5ad51e.png)
2. Run pdoc like this:
```python
pdoc(
    "codefs",
    "!codefs.core",
    output_directory=Path("foo"),
)
```

#### Expected behavior

Docs don't mention ignored module at all.

#### Actual behavior

It still shows up in the submodules list, just not as a link.
![Screenshot 2022-01-16 at 00 29 43](https://user-images.githubusercontent.com/117147/149641076-f1a9c441-cea0-4c54-9c3f-b5835d40f7b9.png)

#### Additional info

It correctly doesn't show up in the module index.
![Screenshot 2022-01-16 at 00 29 51](https://user-images.githubusercontent.com/117147/149641075-08e505da-609a-43d9-9da3-cbe498f434f4.png)

**Comment by mhils** [comment]
Thanks! Technically pdoc is behaving as expected here - the module still exists (as a submodule), you've just chosen not to document it. I absolutely do see where you are coming from though, I need to think a bit about how we can solve this best. In the meantime, one workaround is to define `__all__` in `codefs/__init__.py`.

**Comment by dAnjou** [comment]
Thanks for the quick response!

I've tried that workaround before, but then there's quite some duplication on the `codefs` module page then. The modules show up twice in the sidebar and again at the bottom of the page:

![Screenshot 2022-01-16 at 17 35 52](https://user-images.githubusercontent.com/117147/149669048-a63cebc0-2ea2-4715-8687-e2e3c94cf92a.png)
![Screenshot 2022-01-16 at 17 36 03](https://user-images.githubusercontent.com/117147/149669052-67523b22-f331-4cd0-a6a7-c490410d7aec.png)

**Comment by dAnjou** [comment]
Found another fix, I renamed `core.py` to `_core.py`, which is acceptable for me because the module content shouldn't be public anyway for now.

**Comment by mhils** [comment]
This is fixed on main now! Submodules that are not included in the submodules list if they are not part of the documentation. The only reason why a submodule may not be part of the documentation is because a user has explicitly excluded it via specs, so that's nothing that should come as unexpected.
