### ISSUE TITLE
Linked identifiers are overwritten and produce empty links

### ISSUE THREAD

**Issue by jstriebel** [mitmproxy/pdoc#335]
#### Problem Description
Already linked identifiers are linked again in `linkify`, leading to an empty link with the original href, and the text is linked to the source-code as identified by pdoc.

https://github.com/mitmproxy/pdoc/blob/main/pdoc/render_helpers.py#L168-L172

I don't wont to deactivate the linkify behaviour globally, just some specific occasions are linked manually via Markdown.

#### Steps to reproduce the behavior:
1. In a docstring, add link to a valid identifier, e.g. `[MyClass](some_link)`.
2. The result is hmtl similar to`<a href="some_link"></a><a href="#MyClass">MyClass</a></p>`.

PS: It's worse if the link includes backticks, since the additional link is visible then, e.g. \[\`MyClass\`](some_link)

#### System Information
Paste the output of "pdoc --version" here.
```
pdoc: 7.4.0
Python: 3.7.3
Platform: Linux-4.19.0-18-amd64-x86_64-with-debian-10.11
```
I believe this is still the same in newer pdoc versions.

**Comment by mhils** [comment]
Thanks for the report! I've just fixed this in 3d45349, at least for the cases where we can fix it easily. Somewhat pathologic cases like 
```
[foo `MyClass` bar](https://example.com)
```
would still produce nested links, but we can live with that.
