### ISSUE TITLE
Help with html customization

### ISSUE THREAD

**Issue by zaino** [mitmproxy/pdoc#336]
Sorry for abusing the issue tracker, but I don't know where else to get support from after 2 days of trying.

I want to customize the html layout and contents, and I read the documentation about custom jinja files and the -t command line option.
That's all good, but unfortunately I'm very ignorant when it comes to this tech stack, I need a couple of hints to get going.

The main thing that I'd like to accomplish right now is customizing the list of modules in the index page. I created my custom jinja, but I don't understand how to access modules list and hierarchy. I see in the default that `all_modules` is available, but that's only a list of strings. I thought I could access `doc_objects`, but that doesn't seem to be available.

How do I know what underlying python objects are available and how do I access them to create my own population logic?

Thanks in advance for any help!

**Comment by mhils** [comment]
pdoc < 7.1 used to have a feature where, if invoked without arguments, it would render the module index with _all_ installed Python packages. That posed tricky performance issues while not being particularly useful, so it is now removed. One leftover of that feature is that `all_modules` still only is a list of strings (importing all installed modules would have been too costly). Now that we don't have to worry about this particular performance issue anymore, I'd totally support changing `all_modules` to a `dict[module_name, doc.Module]` dict. IIRC someone asked about this a few days ago as well, let me see if I can quickly cook something up. :)

**Comment by zaino** [comment]
Yeah that would be great.
Can you give me a couple of pointers to understand how variables are made accessible in jinja?
For example, how is `all_modules` available and how is it set? I look at all the default templates searching for something like `{% set all_modules...}` but couldn't find anything. I'd like to learn :)

**Comment by mhils** [comment]
It's passed into the template on the Python side:

https://github.com/mitmproxy/pdoc/blob/3d45349c8812bdae38c4ac864df7caf071bd7e28/pdoc/render.py#L77-L100

**Comment by zaino** [comment]
Ok then getting the dictionary you suggested (I see the value is none now) does require a change to render.py.
I just wanted to make sure I wasn't missing already available entry points, basically :)
I'll be eagerly waiting for something to test!

**Comment by mhils** [comment]
I have a prototype at https://github.com/mhils/pdoc/tree/all-modules. I'm still not sure if the changes will make it in as-is, but please feel free to play around with it:
```
pip install https://github.com/mhils/pdoc/archive/all-modules.zip
```

**Comment by zaino** [comment]
That was fast @mhils!
And I'm happy to report it works.
Granted, I just tested:
` {% for name, mod in all_modules.items() %}
     {% if mod.is_package %}`
but I'm gonna do more tests tomorrow!

Thanks a bunch, hopefully this will make it in soon in one form or another, so I don't have to diverge.

**Comment by mhils** [comment]
This works on main now and will be part of the next pdoc release! 😃
