### ISSUE TITLE
Change list appearance in style_content

### ISSUE THREAD

**Issue by franciszekjuras** [mitmproxy/pdoc#338]
I successfully tweaked documentation style by modifying `module.html.jinja2`, however I cannot figure out how to modify list appearance in documentation, specifically, how to reduce spacing before a list.

**Comment by mhils** [comment]
Could you please clarify what you would like to modify, maybe with a screenshot?

**Comment by franciszekjuras** [comment]
Sure:
![screenshot](https://user-images.githubusercontent.com/29258901/150788463-17bdf1f3-ac53-4974-b71d-64dbae1f002e.png)
e

**Comment by franciszekjuras** [comment]
Here's corresponding docstring:
```
"""
Series object represents ordered one-dimensional data.\n
    `y` property stores data (of any type accepted by `np.ndarray`), while `x` property stores equidistant, ascending
    ordering values (e.g. time or frequency).
    It supports `+`, `-`, `*`, `/`, `+=`, `-=`, `*=`, `/=` operators with some restrictions:
    - Series object must be left-hand side (lhs)
    - On right-hand side (rhs) either another `Series` object can be used
    or any type that is supported by underlying numpy array (eg. another numpy array or a single number)
    - If operation is performed on two `Series` objects, their x arrays must match,
    if numpy array is on rhs, its size must match with lhs `Series` object y array size
"""
```

**Comment by mhils** [comment]
So I don't think this is much of a pdoc question and more of a CSS question. By default each paragraph has a `margin-bottom` of `1rem`. I would not recommend reducing that, but adding a simple
```css
.pdoc p {
    margin-bottom: 0.5rem;
}
```
style rule to the template should be enough. Alternatively you could specify a negative `margin-top` for `ul` elements.
