### ISSUE TITLE
Possible issue with `|` operator

### ISSUE THREAD

**Issue by patchwork-systems** [mitmproxy/pdoc#339]
We just picked up pdoc recently, so I am sorry if this is something answered elsewhere. I spend the day reading through the docs, but we could not find a specific answer.

We have the following code we are trying to document in Python 3.9.5 and pdoc 9.0.0:

```py
# test.py
from future import __annotations__

async def myfunc(
    member: hikari.InteractionMember | hikari.Member
):
    ...
```
When we attempt to use `pdoc test.py`, pdoc produces the following error:

>  Error parsing type annotation hikari.InteractionMember | hikari.Member for code_path: unsupported operand type(s) for |: 'ABCMeta' and 'ABCMeta' (~/.pyenv/versions/3.9.5/envs/vegas2/lib/python3.9/site-packages/pdoc/doc_types.py:112)

If we modify the code to only use `typing.Union`:

```py
# test.py
import typing

async def myfunc(
    member: typing.Union[hikari.InteractionMember, hikari.Member]
):
    ...
```
pdoc is able to parse the file properly with no warnings.

---

Our only thought is that pdoc is not reading/respecting the `from future import __annotations__`.  We were unsure if this was intended, or if it is possible at all. If it is possible, we think it could be a very useful feature, as we know many devs who greatly prefer the future static type hinting.

Thanks for any time or guidance on this!

Note: Using the `|` does not cause the doc generation to fail. It just produces a warning for every instance.

**Comment by patchwork-systems** [comment]
Our current simple solution is just to use nox and set that specific task to run in Python3.10.1 virtualenv. That does completely remove the warning and is only a very minor change.

**Comment by mhils** [comment]
Hi there! This is a duplicate of #326. In short, `X | Y`-style type annotations are not supported on Python < 3.10, `from future import __annotations__` only postpones the evaluation. The next pdoc release will feature a better warning message:

https://github.com/mitmproxy/pdoc/commit/5e13cf99b0c48d4a1eb672cdd94860540dc52625#diff-883332efefaa434ebc8764bb59e8894cdebd6e45785423dcff9fabcfc31359d4R115-R121

Please take a look and let me know if there'y anything unclear after that. :)

**Comment by patchwork-systems** [comment]
Nope! That answers everything perfectly! Thank you very much.
