### ISSUE TITLE
Code snippet interferes with latex expressions

### ISSUE THREAD

**Issue by franciszekjuras** [mitmproxy/pdoc#340]
To reproduce bug, create docstring:
```
"""
$n \\leq 0$. 
`l` is interfering.
"""
```
Result:
![image](https://user-images.githubusercontent.com/29258901/151351896-b64db90a-0259-44f8-a226-d176c2351eae.png)
It appears that processing `l` somehow eats escape characters in `\\leq` as one possible workaround is to write `\\\\leq`
If `l` is changed to something different, equation is rendered properly:
```
'''
$n \\leq 0$. 
`k` is not interfering.
'''
```
![image](https://user-images.githubusercontent.com/29258901/151352693-9b7f4541-88f3-4e97-a2cb-c2bfbf2c0e23.png)
Similarly:
```
"""
$n \\geq 0$. 
`g` is interfering.
"""
```
![image](https://user-images.githubusercontent.com/29258901/151352821-04c32e12-954e-4a95-a5b8-f2b749dd1296.png)

**Comment by mhils** [comment]
https://pdoc.dev/docs/math/math_demo.html#using-math-in-docstrings. :-)

**Comment by mhils** [comment]
Sorry, read too quickly. Let me take a look. 🙈

**Comment by mhils** [comment]
Looks like this is a bug in markdown2, the markdown parser we use:
```python
>>> import markdown2
>>> markdown2.markdown('$n \\leq 0$.\n`l` is interfering.')
'<p>$n leq 0$.\n<code>l</code> is interfering.</p>\n'
>>> markdown2.markdown('$n \\leq 0$.\n`xl` is interfering.')
'<p>$n \\leq 0$.\n<code>xl</code> is interfering.</p>\n'
```

**Comment by franciszekjuras** [comment]
Thanks. I'll open an issue upstream.

**Comment by mhils** [comment]
pdoc includes a vendored copy at `pdoc.markdown2`, but this also affects the latest markdown2 release.

**Comment by mhils** [comment]
This is tracked at https://github.com/trentm/python-markdown2/issues/412.

**Comment by mhils** [comment]
Thanks for fixing this, @Crozzers! 🍰
