### ISSUE TITLE
Link-targets are linkified but shouldn't

### ISSUE THREAD

**Issue by jstriebel** [mitmproxy/pdoc#342]
#### Problem Description
If an identifier is part of a link-target it is re-linked by linkify, breaking the original a-tag.
This is similar to #335, but concerns the target instead.

#### Steps to reproduce the behavior:
1. In a docstring, add link a valid identifier (e.g. `mymodule`) is part of the target, e.g. `[my link](https://mymodule.org)`.
2. The result is hmtl similar to `<a href="[https://<a href=](https://%3Ca%20href%3D/)"../../mymodule.html#org">mymodule.org</a>">my_link</a>`.

#### System Information
pdoc: 9.0.1
Python: 3.7.3
Platform: Linux-4.19.0-18-amd64-x86_64-with-debian-10.11

**Comment by mhils** [comment]
Could you provide a full repro please?

**Comment by mhils** [comment]
I may have fixed that with 4688086b4936380f34f261c76636c9ecdd7fec2d, but it depends a bit on what your actual URL looks like. :)

**Comment by jstriebel** [comment]
Thanks! I tried your newest commit, but it does not fix my case unfortunately. Running `pdoc mymodule` on the unpacked [mymodule.zip](https://github.com/mitmproxy/pdoc/files/7996230/mymodule.zip) yields:
![Screenshot from 2022-02-03 17-18-06](https://user-images.githubusercontent.com/7216331/152382987-92f70d18-a4eb-475d-81cb-73fea8c19dd4.png)
```
<p><a href="[http://<a href=](http://%3Ca%20href%3D/)"#org">mymodule.org</a>">some link</a></p>
```

**Comment by mhils** [comment]
After unzipping mymodule.zip, I get a page that looks correct:

![](https://uploads.hi.ls/2022-02/2022-02-03_19-04-22.png)

**Comment by jstriebel** [comment]
@mhils Indeed, this issue is fixed, I messed up installing the correct version first. Sorry for this and the late reply! And thank you very much for your responsiveness and maintaining this great project :pray:
