### ISSUE TITLE
Tiny enhancement: make favicon an option

### ISSUE THREAD

**Issue by denised** [mitmproxy/pdoc#345]
#### Problem Description

You can currently replace the favicon for a site by modifying the default frame template.  IMO, users are unlikely to need to modify this template for other reasons, but likely to want to have a custom favicon.

#### Proposal
Make favicon an option ala logo.

I would be happy to do this work, if it seems worthwhile to do so.

**Comment by mhils** [comment]
I agree on making the favicon configurable via a CLI switch, not sure what's the best way to address it and what the default value should be[^1]. A couple of options:

1. A binary `--favicon`/`--no-favicon` switch. Folks can then turn off the default favicon and just place something in the default location (`/favicon.ico`) if they want to override it.
2. A `--favicon path` switch. This would then insert `<link rel="icon" href="$path">` into the HTML. The user would still need to place the file at the correct location.
3. A `--favicon filename` switch. We would then inline the file, as we do currently.
4. A `--favicon filename` switch. We would then copy the file to the documentation root and add `<link rel="icon" href="$path">`s.


Happy to hear what others are thinking!

[^1]: I don't think we need to show the pdoc logo by default.

**Comment by denised** [comment]
I vote for (2) as the simplest to understand, and also matching the behavior of the existing logo option.  
Leaving favicon as a block as it is now also gives users the option of implementing it a different way, if they choose.  

Default value is a good question.  You could just leave it blank, and let the browser show its 'no icon' value in that case.

**Comment by mhils** [comment]
I didn't consider the consistency with `--logo`, that's a very strong argument indeed. I think I am convinced. 👍

Leaving it blank by default sounds good to me as well. Please feel free to send a PR! 😃

**Comment by denised** [comment]
I will be happy to do that!

**Comment by mhils** [comment]
This is now fixed in pdoc 10, thanks again! 🍰
