### ISSUE TITLE
Parsing Epytext

### ISSUE THREAD

**Issue by biomadeira** [mitmproxy/pdoc#35]
Sorry the ignorance. Is there a way of 'forcing' pdoc to parse docstrings in Epytext format as the example below:

``` python
def load_config(filename, option):
    """
    Loads and tests input parameters.

    @param filename: input filename
    @param option: option name
    @return: returns a valid config value
    """
```

Thanks

**Comment by BurntSushi** [comment]
No, but you could modify the templates to do whatever you want pretty easily: https://github.com/BurntSushi/pdoc/blob/master/pdoc/templates/html.mako#L66

**Comment by biomadeira** [comment]
Nice. Thanks!

**Comment by johnyf** [comment]
I am also interested in this. Being an `epydoc`user myself, for some time now I have been using Epytext with markdown formatting. Though I am not aware of a suitable doc tool, I was planning to write one. The closest thing is to adapt `pdoc` for recognizing `@param, @type, @return, @rtype`, and also link automatically `Name`, replacing the Epytext `[Name]`, if `Name` is found to be an existing class/function/etc somewhere in the package.

**Comment by peterjc** [comment]
I missed this issue when I filed #111 for the wider issue of supporting some of the markup languages as supported in epydoc (which does not support markdown).

**Comment by cortesi** [comment]
Please see #153 for a unified discussion ticket about docstring flavors.
