### ISSUE TITLE
is it possible to run pdoc on an external venv?

### ISSUE THREAD

**Issue by ms-lolo** [mitmproxy/pdoc#355]
I'm wondering if pdoc is able to parse a directory of python files without being installed in the same venv. I have a repo with many python packages in it as separate poetry projects. I would love to have a single venv with pdoc and all other documentation packages and be able to run `pdoc` on all the other packages from the "outside". This would greatly speed up and simplify our CI pipelines. Is this possible? Are there any hard blockers to making this possible? Here's an example directory structure of my repo:

```
├── app1
│   ├── src
│   │   ├── python
│   └── test
│       └── python
├── app2
│   ├── src
│   │   └── python
│   └── test
│       └── python
├── devtools (with pdoc and mkdoc)
│   ├── src
│   │   └── python
│   └── test
│       └── python
```

**Comment by mhils** [comment]
Hi there! 😃 

This sounds like an interesting problem. I'm afraid there's no way around pdoc needing to import all modules, but maybe you can do some [PYTHONPATH](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) shenanigans. It might be enough to just add the other venv there so that imports work. Are you invoking pdoc from the command line or via Python scripting?

**Comment by ms-lolo** [comment]
I'm using the command line but if the only way to document code is by importing it, then my ask isn't possible. I was hoping you were parsing the contents of the files instead of importing them.

**Comment by ms-lolo** [comment]
After some googling, looks like this was asked before and deemed not possible :( https://github.com/mitmproxy/pdoc/issues/82

**Comment by mhils** [comment]
@ms-lolo: depending on what you are doing, just setting `PYTHONPATH` to the correct venv seems to work fine. Example:

```console
λ python -m venv repro  # create demo venv, install a python package into it
λ repro/bin/pip install arxiv
[...]
Successfully installed arxiv-1.4.2 feedparser-6.0.8 sgmllib3k-1.0.0

λ python -c "import arxiv"  # the arxiv package is still unavailable in the current environment
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'arxiv'

λ pdoc arxiv -o ./render  # pdoc also still does not work
Warn: Cannot find spec for arxiv (from arxiv):
[...]

λ PYTHONPATH=repro/lib/python3.10/site-packages/ pdoc arxiv -o ./render # but setting PYTHONPATH works
🎉
```
