### ISSUE TITLE
Enabling mock imports

### ISSUE THREAD

**Issue by bkemmer** [mitmproxy/pdoc#359]
#### Problem Description

I want to use pdoc to generate the documentation for a library that runs inside Databricks. The databricks runtimes already have some modules installed, and there is one that is proprietary and exists only in their clusters.

So, it would be nice to mock some imports that will always be present in runtime. I saw that Sphinx has this option [here](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports).

#### Proposal
Be able to mock imports from the configuration.

#### Alternatives
I could run pdoc as a library and mock the import using `from unittest import mock`, but this isn't ideal.

**Comment by mhils** [comment]
I think you have a reasonable use case, but it's too much complexity for an edge case that affects very few users. I think running pdoc as a library here is really the correct call. :)
