### ISSUE TITLE
Pdoc seems to not follow `__wrapped__`

### ISSUE THREAD

**Issue by Hibou57** [mitmproxy/pdoc#36]
_Pdoc_ seems to not follow [the `__wrapped__` attribute](https://docs.python.org/3.4/library/functools.html#functools.update_wrapper), to keep track of functions wrapped by a decorator. All decorated functions (which is all functions for me personally), are documented with something like `def fun(*args, **kargs)`.

Function annotations seems to be ignored too, both with decorated and non-decorated functions.

By the way, thanks for the idea of using Markdown ;-) .

**Comment by Hibou57** [comment]
Under investigations…

**Comment by Hibou57** [comment]
Done in pull-request.

**Comment by peterjc** [comment]
See pull request #37.

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. This should be fixed with the latest release. 😃
