### ISSUE TITLE
Links to modules are not generated in 10.0.2

### ISSUE THREAD

**Issue by vlad-nn** [mitmproxy/pdoc#360]
#### Problem Description
Links to modules are not generated in 10.0.2. They are generated as `<code>`, instead of `<a>`.
Was working in 10.0.1.

#### Steps to reproduce the behavior:
1. Create pkg directory
2. In pkg directory create `__init__.py` file with the following contents:
```
"""
This should be a link: `pkg.mod1`

This link is correct: `pkg.mod1.mod1_f1`
"""
import pkg.mod1
```

3. Also create `mod1.py` file with the following contents:
```
def mod1_f1():
	""" Some function """
	pass
```
4. Install pdoc 10.0.2
5. Run pdoc:
`pdoc pkg -o out`
6. Look `out/pkg.html`:
```
<div class="docstring"><p>This should be a link: <code>pkg.mod1</code></p>
<p>This link is correct: <code><a href="pkg/mod1.html#mod1_f1">pkg.mod1.mod1_f1</a></code></p>
</div>
```
Problem:
`<code>pkg.mod1</code></p>` is not a link anymore. Used to be a link in 10.0.1 and below.

#### System Information
pdoc: 10.0.2
Python: 3.8.12                                                                                                                                                                     Platform: Windows-10-10.0.19042-SP0

**Comment by mhils** [comment]
Thanks for the clear repro! f179a08ee170031f85b4a376e1b6471f175d0f7b is the first bad commit, I'll take a look.

**Comment by mhils** [comment]
Thanks again for catching this! 10.0.3 is going through CI right now and should be out in about 10mins. :)
