### ISSUE TITLE
Question: how to reference pdoc index folder from jinja2 templates (link a root .js from all ./...subpath.../module.html)

### ISSUE THREAD

**Issue by abubelinha** [mitmproxy/pdoc#362]
#### Problem Description
I come from the situation described in #325 , where I am documenting a list of .py scripts which are distributed in different folders. Once @mhils explained I need to add `__ini__.py` files inside each folder, that works perfectly well, and all my scripts are shown in the pdoc index.

Now I have improved it with some javascript, to have a selectable and sorted list of modules as summarized in #356.
But for my sorting purposes, I preferred to use an external `mycustomjavascript.js` file, which I linked using a custom `frame.html.jinja2` like this:
```jinja2
{% block body %}
    {{ super() | safe }}
<script type="text/javascript" src="./mycustomjavascript.js"></script>
{% endblock %}
```

The problem is that this .js file is not being loaded by those modules which are located in subfolders, where the "./" path is not valid any more.
I guess the same will happen when documenting ordinary python packages organized in subfolders.

#### Proposal
Is there any way to specify the outside script's path in a way that pdoc is available to adapt it to the location of the .py file being documented? 

So, if pdoc knows the .py file is inside "`subfolder`", the generated .html module should try to load "`../mycustomjavascript.js`" instead of "`./mycustomjavascript.js`"
And if it is inside "`subfolder1/subfolder2`", it should load "`../../mycustomjavascript.js`"

#### Alternatives
Remote served .js is not an option because I want my documentation to work offline.

I could just put all javascript content inside my custom `jinja2.frame.html` module. But that has several problems:
1. If I want to touch some of the javascript code, I have to regenerate all documentation to see it working.
2. If my javascript code is too long or complex (i.e., jquery plugins or whatever), it's much easier to maintain it in as indepent file(s)
3. It would increment the file size of every single .html file generated.

I could also have copies of all .js files inside each subfolder, but that would be quite messy to maintain, plus have the same problems 2 & 3.
__________________________________
Of course, I know this is not a bug.  I am just asking for help on how to do it.  
I guess this is about jinja2 programming stuff, but I couldn't figure it out.

**Comment by mhils** [comment]
You already list the alternative of inlining the file. Alternatively, you can do what pdoc does for the search index:

https://github.com/mitmproxy/pdoc/blob/d0bd886c73efd6f5b5b0f0ee915401a8bddd84b2/pdoc/templates/search.html.jinja2#L2

```jinja2
<script type="text/javascript" src="{{ rootprefix }}mycustomjavascript.js"></script>
```

**Comment by abubelinha** [comment]
Thanks @mhils , much better your solution IMHO.
I put that `{{ set rootprefix ... }}` line in my frame.html.jinja2 extension template and it works like a charm.
:+1: :+1: :+1:
