### ISSUE TITLE
Aliases for parameterized types of standard collections

### ISSUE THREAD

**Issue by hriebl** [mitmproxy/pdoc#363]
Since Python 3.9, the standard collections work as generics. I sometimes like to create aliases for parameterized types of standard collections to facilitate typing other objects. Unfortunately, the output of pdoc is very verbose in this case. It's much more sparse if I use the "old" generics from the typing module. See the following example:

``` python
from typing import Dict

FirstDict = dict[str, str]
"""Shows as a class in pdoc with all methods of a dictionary."""

SecondDict = Dict[str, str]
"""Shows as a variable in pdoc with no methods."""
```

Is there a way to make pdoc render the version with the `dict` just as the version with the `Dict`?

By the way, thank you for reviving pdoc! :rose:

**Comment by mhils** [comment]
Thanks for pointing this out! `dict[str, str]` should of course behave as you describe, I fixed this on main. :)

**Comment by hriebl** [comment]
Thank you for the quick fix!
