### ISSUE TITLE
Docstrings of imported variables are not rendered

### ISSUE THREAD

**Issue by hriebl** [mitmproxy/pdoc#365]
#### Problem description

Docstrings of imported variables that are included in the `__all__` dunder are not rendered, while docstrings of imported classes are rendered.

#### Steps to reproduce the behavior

Create a file `foo.py`:

``` python
hello = "hello"
"""This docstring is rendered with `pdoc foo` *but not* `pdoc bar`."""

class HelloWorld:
    """This docstring is rendered with `pdoc foo` *and* `pdoc bar`."""
```

And a file `bar.py`:

``` python
from foo import hello, HelloWorld

__all__ = ["hello", "world", "HelloWorld"]

world = "world"
"""This docstring is rendered with `pdoc bar`."""
```

Now, run `pdoc foo` and `pdoc bar`.

#### System information

```
pdoc: 10.0.3
Python: 3.10.2
Platform: Linux-5.16.13-200.fc35.x86_64-x86_64-with-glibc2.34
```

In fact, I have commit a283aa88107a2a12d5e520b903ae721aced9c13c installed.

**Comment by mhils** [comment]
Thanks for the superb report. Fixing this is very tricky unfortunately. For classes and functions we can inspect where they come from (`cls.__module__`), but no such functionality exists for variables (it's just a plain string after all). We would need to perform static analysis to determine imports and then resolve them, which is somewhat outside of pdoc's domain. I'm afraid this is a wontfix for now. 

As a workaround, you could use pdoc as a library and then manually update the importing module's `_var_docstrings` attribute with the source module. Sorry for the potentially unsatisfactory answer. 🙃

**Comment by thrau** [comment]
@mhils could you give an example of how that workaround would look like?
