### ISSUE TITLE
edit index page

### ISSUE THREAD

**Issue by talnagar** [mitmproxy/pdoc#367]
#### Problem Description
I am trying to generate docs for code that has the following structure:
src
- module a
- module b
- module c

Generating docs creates an index with the namespace src. 
I don't understand how to add some general information about the project and place it in the index page. 
I'll appreciate any insight on this.

**Comment by mhils** [comment]
If all your modules have one common parent module (e.g. `mycompany.module_a`, `mycompany.module_b`, etc.), then pdoc's index page will redirect to the `mycompany` module and you can customize the docstring there.

If your modules don't share a common parent module (your example indicates that is the case), then you could [use a custom template](https://pdoc.dev/docs/pdoc.html#editing-pdocs-html-template) and modify the index template to your liking. Here's an example for a custom `index.html.jinja2`:

```jinja2
{% extends "default/index.html.jinja2" %}

{# Redefine content #}
{% block content %}
    <main class="pdoc">
    Hello World
    </main>
    {% include "search.html.jinja2" %}
{% endblock %}

{# Optional: Add search bar to the navigation. #}
{% block nav %}
    <input type="search" placeholder="Search..." role="searchbox" aria-label="search" pattern=".+" required>

    {{ super() }}
{% endblock %}
```

Looking at the default template definition (https://github.com/mitmproxy/pdoc/blob/main/pdoc/templates/default/index.html.jinja2) might be useful.
