### ISSUE TITLE
line breaks on multi line docstring

### ISSUE THREAD

**Issue by talnagar** [mitmproxy/pdoc#368]
#### Problem Description
I have a docstring for method params, when I run pdoc they all appear as a one line sentence. 
Is there a way to control this?
#### Steps to reproduce the behavior:
doc sctring is:
```
def send_email(subject: str, email: str, content: str, files: List[str] = []) -> None:
"""
    send an email
    :param subject: email subject line
    :param email: email address of recipient
    :param content: content of the email
    :param files: list of file paths to be attached to email
"""
```
after generating pdoc html this is the result:
![image](https://user-images.githubusercontent.com/7373236/160867208-0065dab0-8846-450f-9568-0a1fadbfd709.png)

#### System Information
==0.10.0

**Comment by mhils** [comment]
I think the main problem is that we don't properly support `:param` yet (#275). pdoc treats the docstring as plain Markdown where line breaks are only considered if the previous line ends with two or more spaces. So the three workarounds are (1) adding spaces, (2) adding empty lines, or (3) using a different documentation format. That being said, I've had a few folks ask about `:param` support, so maybe this is just something we should start tackling. 😃
