### ISSUE TITLE
Use shortened submodule names by default

### ISSUE THREAD

**Issue by jacksund** [mitmproxy/pdoc#374]
#### Problem Description

For packages that have long or verbose import names, the html sidebar can become difficult to read for lower-level modules.

A live example of this is with some documentation in my own package (see [here](https://jacksund.github.io/simmate/simmate/database/base_data_types.html), the "Submodules" list in the sidebar is difficult to read).

#### Proposal
Regardless of the length for full import path, the submodule list can be clear with just a terminal ending. I suggest pdoc uses the submodule name in the sidebar, rather than the full import path. 

As arbitrary example, and sidebar link such as  ...

```
example.path.to.my.submodule1
```

... would be changed to ...

```
submodule1
```

#### Alternatives
But for those that still want the full path visible, an option to incorporate this might be worth considering. Alternatively, the Submodule heading in the html could also list a subheader with the full import path such as...
``` html
<div>

    <h2>Submodules</h3>
    <h4>path.to.parent.module</h4>
    
     <!-- then iterate through submodule list per usual -->
     <p>submodule1</p>
     <p>submodule2</p>

</div>
```

#### Additional context

I know my import paths can be shortened (e.g. changing `base_data_types` to `base`), but I keep them verbose to help with my users -- which have typically never coded or used python before. So this feature change would be super helpful to my project!

**Comment by mhils** [comment]
I think your rationale makes a ton of sense, thanks for the suggestion. :) Do you want to send a PR?

**Comment by jacksund** [comment]
Sure, I can take a stab at it. I'm wrapping up for the day, but will open a pull-request for this tomorrow. :smile:
