### ISSUE TITLE
Installation of version 11.1.0 fails with: No matching distribution found for pygments>=2.12.0

### ISSUE THREAD

**Issue by JenniferHem** [mitmproxy/pdoc#386]
#### Problem Description
Trying to install Version 11.1.0 of pdoc fail with "ERROR: No matching distribution found for pygments>=2.12.0"

#### Steps to reproduce the behavior:
1. Set up environment with python 3.8.12
2. pip install pdoc

Or: 
have pdoc < 11.0.0 installed and use "pip install pdoc --upgrade" : The upgrade only installs version 11.0.0

#### System Information
pdoc: 11.0.0
Python: 3.8.12
Platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.10

pdoc: 11.0.0
Python: 3.9.10
Platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31

I could not find any requirements for a python version for pygments so I tested it with python 3.8 and 3.9 and I received the same Error message. I am not sure if this is really a pdoc issue but I thought it probably should be noted here first. Happy to also post the issue with pygments

**Comment by mhils** [comment]
Thanks for the report. I do get pygments 2.12 just fine on my system, and I also see it available on PyPI for Python 3.6 and above: https://pypi.org/project/Pygments/

Are you using some PyPI mirror, maybe from your company?
