### ISSUE TITLE
Reason for no module internal link?

### ISSUE THREAD

**Issue by Hibou57** [mitmproxy/pdoc#39]
I would like to know about the reason for not having module internal links in the generated documentation. My guess is that is may not always be easy, when as an example, a documentation string refers to a function parameter which is of the same name as an item defined in the module (PyLint warns about it, by the way).

Is this guess indeed the reason or is there another reason?

I “patched” my `html.mako` to display internal links, and am asking this question to know if it's relevant to propose this patch here.

I'm also actually to display references to function parameters in function documentation strings, with a specific class (I mean, HTML class), if feasible (under investigation).

**Comment by Hibou57** [comment]
With mt patched `html.mako` and `css.mako` I can display reference to function parameters, with as `<span class="arg"><code>fn-arg</code></span>` instead of as `<code>fn-arg</code>`. It requires to pass a context parameter around. It's handled in `linkify` although it does not generate a link.

I will wait an answer to the question before I propose this patch (for two things: internal module links and distinguished display of reference to function parameter in function documentation strings).

**Comment by mhils** [comment]
Hi there,

I'm not sure if correctly understand the question, but pdoc's linking behavior is described at https://pdoc.dev/docs/pdoc.html#link-to-other-identifiers. Looking at the issue date - if this problem still persists please open a new one. 😄
