### ISSUE TITLE
The code is executed, as shown in the figure

### ISSUE THREAD

**Issue by Pactortester** [mitmproxy/pdoc#393]
#### Problem Description
The code is executed, as shown in the figure

#### Steps to reproduce the behavior:
![image](https://user-images.githubusercontent.com/29191106/168244972-895768f0-3a8f-46a1-a9f2-1701cf720a11.png)
<img width="774" alt="image" src="https://user-images.githubusercontent.com/29191106/168245268-c5323e2f-9a72-4c24-aa65-438093756f90.png">

#### System Information
pdoc: 10.0.4
Python: 3.9.1
Platform: macOS-12.1-x86_64-i386-64bit

**Comment by mhils** [comment]
I think that's unfortunately a fundamental limitation on how pdoc works. pdoc processes the final evaluated value and not the abstract syntax tree. We could conceivably think about extracting such information from the AST, but then again it's unclear in other cases which representation is preferrable. Sorry, but I'm afraid this can't/won't be fixed!
