### ISSUE TITLE
Function return-type links are not clickable

### ISSUE THREAD

**Issue by ginty** [mitmproxy/pdoc#399]
Hi,

I see a previous issue with the function return type links not working is back again, see #332 for details.

I see this on Chome and Firefox with 12.0.0, however 11.2.0 is fine.

Thanks!

**Comment by mhils** [comment]
Thanks for the heads-up! 😃

**Comment by mhils** [comment]
This is now live in pdoc 12.0.1. :)

**Comment by ginty** [comment]
Thanks a lot for the quick turnaround, I confirm that this is fixed in 12.0.1
