### ISSUE TITLE
support wavedrom in docstrings markdown quoted code to document communication protocol

### ISSUE THREAD

**Issue by PyroTom** [mitmproxy/pdoc#406]
#### Problem Description

When writing some low level driver stuff it would ease the documentation if I would be able to just
do the protocol diagram/description using wavedrom directly in the python docstring

#### Proposal
Add the support of wavedrom in the markdown quoted code. Similar to mermaid
```python
    def send_cmd(self, cmd: str or bytes or List[int]):
        """ send_data method:
        packs the data according to the API specification

        ```wavedrom
        {
        signal: [
            { name: "SEND", wave: "x2345" }
        ]
        }
        ```
```

#### Alternatives
As alternative I do something really weird!

I add this in the docstring:
<API_HEADER_CMD><NO_OF_BYTES = 2><CMD_BYTE1><CMD_BYTE2><LSB_CHECKSUM>

#### Additional context
- [link to wavedrom](https://wavedrom.com/) is using java script
- [python abstraction](https://github.com/wallento/wavedrompy)
- [implementation for python markdown](https://github.com/MaximilianKoestler/markdown-wavedrom)

**Comment by mhils** [comment]
I think this is out of scope for pdoc, as long as it is not supported by the Markdown library we use (markdown2). You should be able to implement this with custom client-side JavaScript though. :-)

**Comment by mhils** [comment]
Awesome, thank you for sharing! 😃

**Comment by PyroTom** [comment]
They finally implemented the support 😄 
https://github.com/trentm/python-markdown2/pull/477
