### ISSUE TITLE
How can I create a title page for a project with multiple modules?

### ISSUE THREAD

**Issue by MiguelGuthridge** [mitmproxy/pdoc#410]
#### Problem Description

One of my projects consists of multiple modules, which due to design constraints cannot be merged under one umbrella. PDoc handles this very well, with a clear list of modules being shown in the left-hand panel on the landing page. However, since there is no main `__init__.py` file that I can include some markdown within (refer to the "include markdown files" section of the docs), it doesn't seem like I can take any action to customise the site's landing page.

#### Proposal
If there is a way to do this without employing any hacks or workarounds which would mess up my project's hierarchy, then add some more clear documentation to help users find info on it.

Otherwise, add support for a command line flag that lets you specify a markdown file to be included on the landing page for documentation of projects that use many modules.

#### Alternatives
I can't think of any

#### Additional context
Lots of empty space, which could benefit from adding a nice readme file.
![image](https://user-images.githubusercontent.com/31365175/177307645-f9e47af3-ccf2-4d2c-aa0d-f46745730037.png)

**Comment by MiguelGuthridge** [comment]
Cool, thanks for the explanation! Do you think it could be worthwhile updating the documentation for it to make it more clear?

**Comment by vivek87799** [comment]
Hi,
First I would like to thank you for the simple and a wonderful documentation tool. 

I have a similar requirement for my project. I have created a custom-template dir with index.html.jinja2 file to override 

pdoc -t .\demo_poc\custom-template\ .\demo_poc\ 

Unfortunately nothing changes. Can you kindly help me with this.

**Comment by javiortizmol** [comment]
Hi, the steps that you suggested in the documentation didn't work
