### ISSUE TITLE
Generate documentaton for python project with "src layout"

### ISSUE THREAD

**Issue by rmuller** [mitmproxy/pdoc#417]
I try using `pdoc` for a basic python project using the "src layout", like

    .
    ├── pyproject.toml
    ├── README.md
    ├── setup.py
    ├── src
    │   ├── dep.py
    │   ├── main.py
    └── tests
        └── test_dep.py

environment:

    pdoc: 12.0.2
    Python: 3.8.10
    Platform: Linux-5.15.0-41-generic-x86_64-with-glibc2.29

`setup.py`:

    setup(
    ...
    packages=find_packages(where='./src'),
    package_dir={'': 'src'},
   ...

Now i want  to generate documentation for the modules in the `src` directory.  From the root of the project i execute the following command:

    pdoc --docformat markdown --output-directory docs/ src/

However, this lists the modules `src.main` and `src.dep`. This is not correct, `src` is not a package, but the root dir for the source files ("src layout" paradigm). Note: removing the top level help does not help either.

If executing

    cd src
    pdoc --docformat markdown --output-directory ../docs/ *.py

the expected module names appear in the generated documentation. However, i have no possibility to include top level documentation, because the __init__.py is gone and afaik it is needed for this.

Is this the correct way to deal with pdoc in this use case or am i missing something?

**Comment by mhils** [comment]
I would recommend to use pdoc in a virtualenv with your package installed and then call `pdoc module_name` instead of specifying a directory path. Does that work for you?

**Comment by rmuller** [comment]
I am am using a virtualenv. But this project has no package(s) defined. So nothing to install.

**Comment by mhils** [comment]
Looking at your project layout again - you do have a `__init__.py` in `src/`, which by my understanding means that you mark `src` as a package. Could you share some resources that describe such a src layout with top-level `__init__.py` files?

**Comment by rmuller** [comment]
Initially, I had no `__init__.py` file. I read somewhere that this would probably resolve the issue.
So forget this, I also updated my question.

**Comment by mhils** [comment]
Ah, sorry for reading your question a bit superficially in the first place. You are perhaps looking for the second invocation you're mentioning together with https://pdoc.dev/docs/pdoc.html#add-a-title-page?

**Comment by rmuller** [comment]
Yes, seen that. That would be a bonus, but not really necessary. With and without the `__init__.py`, the issue originally reported remains the same.

**Comment by mhils** [comment]
Your initial posts states that using that approach, "the expected module names appear in the generated documentation.". That seems to contradict your last message, or am I misunderstanding you here?

**Comment by rmuller** [comment]
Sorry for making it more unclear than needed. I've tried a few things and come to the following conclusion:

1. If using the "src layout" you must run pdoc from within the `src` directory. Otherwise `src` is seen as package. Correct?
2. If executing pdoc from the `src` directory you need to explicitly list all modules in the simple setup as described above (so no explicit packages), otherwise artifacts like `__pycache__.py` are also processed: `pdoc ../docs main.py dep.py`. Correct?
3. In the last scenario, there is no possibility of an overview page. Correct?

**Comment by GrammAcc** [comment]
Hi, I just started experimenting with pdoc for api documentation in a library I've been working on (not public... yet), and I happened across this issue and thought I'd give my two cents since I've had to deal with similar headaches recently.

It sounds like you don't intend to publish your project as a package, but you need to have a top-level landing page above all of the individual modules in the documentation without having a package name prepended to each module's FQN. Is this correct?

As far as I understand it, api doc generators like pdoc follow the module structure of the source code, and whether there is an `__init__.py` file or not, any directory in a python source tree will be considered a package.

If an `__init__.py` file is present, it is an explicit package, and if no `__init__.py` file is present, it is a [Namespace Package](https://peps.python.org/pep-0420/), so I believe that pdoc will treat it as a package regardless and prepend the name of the directory to everything in the generated docs, so if you want to have a top-level landing page without an actual package (and a prefix on your module names), I think the only option is to edit the jinja2 template like @mhils suggested, but I just started using pdoc, so I could be missing a feature or something. :)

I hope this helps.

**Comment by mhils** [comment]
> 1. If using the "src layout" you must run pdoc from within the `src` directory. Otherwise `src` is seen as package. Correct?

No. That depends on whether you have an `__init__.py` or not. `pdoc src/*.py` or `cd src; pdoc *.py` should not make a difference. Here's an example:

```
mkdir src
touch src/foo.py src/bar.py
pdoc src/*.py
```

![image](https://user-images.githubusercontent.com/1019198/181496158-2d495172-5ecf-4fe2-8a4a-8f99306aedc7.png)


> 2. If executing pdoc from the `src` directory you need to explicitly list all modules in the simple setup as described above (so no explicit packages): `pdoc ../docs main.py dep.py`. Correct?

Yes, you need to list all top-level modules. On most Linux shells, something like `*.py` will work (see above).

> 3. In the last scenario, there is no possibility of an overview page. Correct?

There is, see https://github.com/mitmproxy/pdoc/issues/417#issuecomment-1195372062.

**Comment by rmuller** [comment]
@GrammAcc

> It sounds like you don't intend to publish your project as a package, but you need to have a top-level landing page above all of the individual modules in the documentation without having a package name prepended to each module's FQN. Is this correct?

Yes!

> As far as I understand it, api doc generators like pdoc follow the module structure of the source code, and whether there is an __init__.py file or not, any directory in a python source tree will be considered a package

Yes, that is my understanding too. Ignoring the setting of my config.py (package tree starts at `src`; pytest for example respects these settings)

> I think the only option is to edit the jinja2 template like @mhils suggested

I missed that suggestion. And yes, seems to be the case

@mhils 

Thanks for your thanks for your patience, clear. The comment of @GrammAcc summarizes my concerns very well. His conclusion is correct?

**Comment by mhils** [comment]
pdoc won't treat it as a namespace package and won't prepend the directory name (we insist on `__init__.py` for detection), but yes you do need to edit the template if you have multiple top level modules. Everything else is correct as well. :)

**Comment by GrammAcc** [comment]
@mhils said:
> pdoc won't treat it as a namespace package and won't prepend the directory name (we insist on `__init__.py` for detection),

Ah, my apologies for adding a bit of confusion with my earlier comment. I should have investigated more before making this assumption about namespace packages.

> yes you do need to edit the template if you have multiple top level modules. Everything else is correct as well. :)

Thank you for clarifying!
