### ISSUE TITLE
Could pdoc do recursive documentation generation for single files?

### ISSUE THREAD

**Issue by jt0dd** [mitmproxy/pdoc#418]
#### Problem Description

When I run pdoc on my project treating `main.py` (my entrypoint) as a module, like: `pdoc main -p 37163`, I get the error `ValueError: No modules found matching spec: main` so I have to run it like `pdoc main.py -p 37163` and then none of the requirements get rendered at all, just whatever classes are written directly in main.py. The imports with classes are ignored.

#### Proposal

Compare this to running the native Pydoc module (`python -m pydoc -w main -p 1234`), the resulting CSS/HTML isn't customizable like pdoc but it does recursively document all the imported modules. Edit: maybe it doesn't. I'm re-testing and not seeing the outcome I thought I saw before.

I wish pdoc would document things recursively so any imported modules are recursively included in the documentation.

**Comment by mhils** [comment]
Thanks for the suggestion! pdoc only documents the module(s) you pass it on invocation. If you want your dependencies to be included, you would need to pass them there. Changing the documented dependencies at runtime incurs too much complexity for me to maintain, and unconditionally documenting all modules does not work performance-wise. Long story short, I'm afraid this won't make it. Sorry!

**Comment by jt0dd** [comment]
Nevermind, `sphinx-apidoc` has the feature I needed.
