### ISSUE TITLE
Docstrings for TypedDict not rendered

### ISSUE THREAD

**Issue by slhck** [mitmproxy/pdoc#419]
#### Problem Description

I have a `TypedDict` class with a general docstring and docstrings for each attribute.

When rendered with pdoc, no output is shown except for the class name.

#### Steps to reproduce the behavior:

```python
from typing import Dict, List, TypedDict, Union

class VmafOptions(TypedDict):
    """
    VMAF-specific options.
    """

    """Use a specific VMAF model file. If none is chosen, picks a default model."""
    model_path: Union[str, None]
    """A list of params to pass to the VMAF model, specified as key=value."""
    model_params: List[str]
    """Number of threads to use. Defaults to 0 (auto)."""
    n_threads: Union[int, None]
    """Subsampling interval. Defaults to 1."""
    n_subsample: Union[int, None]
    """List of features to enable in addition to the default features. Each entry must be a string beginning with name=feature_name, and additional parameters can be specified as key=value, separated by colons."""
    features: List[str]
```

#### System Information

```
pdoc: 12.0.2
Python: 3.9.10
Platform: macOS-12.4-arm64-arm-64bit
```

**Comment by mhils** [comment]
You incorrectly have the docstrings above the variables, but you should see some docstrings nonetheless. Here's how the file you posted renders for me:

![image](https://user-images.githubusercontent.com/1019198/181792732-16d205f9-a7f1-440f-8b8d-df9421bb22fe.png)

```
pdoc: 12.0.2 (+6, commit d444b88)
Python: 3.10.5
Platform: Linux-4.4.0-22621-Microsoft-x86_64-with-glibc2.31
```

**Comment by slhck** [comment]
Hm! Thanks for the quick check. The full branch is here. Do you see anything obvious? 

https://github.com/slhck/ffmpeg-quality-metrics/tree/vmaf-2.0

I am just calling pdoc for the module name with Google format enabled.

The other classes are exported/documented correctly.

**Comment by mhils** [comment]
What does your output look like? A screenshot could help.

**Comment by slhck** [comment]
Never mind, a user error on my end. It all works now.

Thanks for providing this package!
