### ISSUE TITLE
Permission errors when using pdoc action

### ISSUE THREAD

**Issue by jacksund** [mitmproxy/pdoc#425]
#### Problem Description

I'm unable to get the pdoc action to run for my repo due to permission errors. Has anyone ran into this before?

I'm using almost the exact same script from pdoc, but can't seem to figure this out -- even when I remove the permissions for the action template.

Links:
- [repo home](https://github.com/jacksund/simmate)
- [pdoc action](https://github.com/jacksund/simmate/blob/main/.github/workflows/docs.yml)
- [pdoc script](https://github.com/jacksund/simmate/blob/main/docs/make_docs.py)
- [PR where this is attempted](https://github.com/jacksund/simmate/pull/205) (main branch is also failing with the same error)
- [example error from action](https://github.com/jacksund/simmate/runs/7661251660?check_suite_focus=true)

**Comment by jacksund** [comment]
maybe this is related to #414 ?

**Comment by jacksund** [comment]
This command helped me fix it: [here](https://github.com/orgs/community/discussions/26239). Might be something other's run into.

Separately, I also ran into the issue from 414 (linked above). So it might be useful to (i) add a warning to the docs [here](https://pdoc.dev/docs/pdoc.html#deploying-to-github-pages) and (ii) have an issue that tracks this until github UX accommodates this action with default settings

**Comment by mhils** [comment]
The file permissions are now documented in the workflow file, and I've also updated the instructions to emphasize setting the Pages source correctly. The workaround in #414 shouldn't be necessary anymore. :)
