### ISSUE TITLE
one of the pytest doctests in a docstring not rendered correctly

### ISSUE THREAD

**Issue by tmeyier** [mitmproxy/pdoc#429]
#### Problem Description
One of the doctests in the example below isn´t rendered correctly. The behavior depends on indentation and on the --docformat command argument: see example below.

#### Steps to reproduce the behavior:

test script doctest_google.py:
```python
def bla():
    """Print bla.

    Examples:
        >>> bla()
        blu

        >>> bla()
        bla
    """
    print("bla")

def bli():
    """Print bli.

    Examples:
    >>> bli()
    bli

    >>> bli()
    blo
    """
    print("bli")
    
bla()
bli()
```
Apply:

```bash
pdoc doctest_google.py
```
or

```bash
pdoc doctest_google.py --docformat restructuredtext
```

And get this:
![20220810_155256](https://user-images.githubusercontent.com/95271082/183918904-b4f1314d-7df1-4df2-beea-6c468d227b5b.png)

Or apply

```bash
pdoc doctest_google.py --docformat google
```

and get this:
![20220810_160505](https://user-images.githubusercontent.com/95271082/183921691-4447ee7a-1f5e-4151-addf-59badb04b068.png)

#### System Information
pdoc: 12.0.2
Python: 3.9.13

**Comment by mhils** [comment]
`pdoc doctest_google.py --docformat google` should be fixed in https://github.com/trentm/python-markdown2/pull/462/commits/f1634cc0b1e1de6015050860e684eccea06f0f5c. I'll revisit the other case once the changes upstream have landed. :)

**Comment by tmeyier** [comment]
Thanks for your super quick response - and for your dedication to free software. :-) Am 11.08.2022 16:10 schrieb Maximilian Hils ***@***.***>:
pdoc doctest_google.py --docformat google should be fixed in ***@***.*** I'll revisit the other case once the changes upstream have landed. :)
