### ISSUE TITLE
Built-in theme support

### ISSUE THREAD

**Issue by gaby** [mitmproxy/pdoc#435]
#### Problem Description
Currently there's no built-in way to specify a theme when generating documentation with `pdoc`. Ideally `pdoc` would incorporate a few built-in theme's from which the user can choose.

#### Proposal
The example provided by this repo for using a dark-theme works out of the box. Ideally `pdoc` could add a `--theme=dark` flag to specify which of the built-in theme's to use.

As an initial solution provide two theme's: Light (current/default) and Dark (https://github.com/mitmproxy/pdoc/tree/main/examples/dark-mode)

#### Alternatives
My current solution was to download the css files from this repo and host them in a `static` folder of my module. This works fine for one module, once I start adding pdoc support to all my modules, it will become a mess of css files on each git repo.

**Comment by mhils** [comment]
Paraphrasing Henry Ford: You can have any theme, as long as it's the default theme. 

There are no plans to add theme support to pdoc, the complexity outweighs the benefits. You can place your desired template in `$XDG_CONFIG_HOME/pdoc`, or pass `--template-directory` when invoking pdoc. If you build your docs on CI, you can add a step to download your styles from a common location. This way you don't have to maintain multiple copies. :)

**Comment by gaby** [comment]
Using `--template-directory` should solve my issue! Thanks!
