### ISSUE TITLE
malformed \N character escape

### ISSUE THREAD

**Issue by abubelinha** [mitmproxy/pdoc#437]
#### Problem Description
I am getting errors when my code contains an "\N" substring
This uses to happen to when using windows-style file paths.

#### Steps to reproduce the behavior:

```Python
def sample_function(output_file = 'C:\Temp\NUMBERS.txt'): # 1. This fails
	""" 
	Pass your output file path:
	i.e. output_file = 'your\path\no_problem\NOT_WORKING\To\temp\file.txt'  # 2. This fails
	"""
	string_variable = "start ... \N ... end" # 3. This fails
	pass
```
Then, when calling pdoc from a script (as described in #325) I get this error (any of the three lines in the example will make it fail):

`SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 5-6: malformed \N character escape
`

#### System Information
pdoc: 11.1.0
Python: 3.8.7
Platform: Windows-7-6.1.7601-SP1

Thanks
@abubelinha

**Comment by mhils** [comment]
This is not a pdoc bug, your example code simply has syntax errors in it. See https://stackoverflow.com/a/53495814/934719 for example.
