### ISSUE TITLE
pdoc could (should?) ignore __main__.py

### ISSUE THREAD

**Issue by mfrigerio17** [mitmproxy/pdoc#438]
#### Problem Description

I have a package which contains a command line tool. Thus, for convenience, I have a `__main__.py` module, to allow to "execute" my package with `python -m`. That module simply runs the `main()` function defined elsewhere.

Because pdoc imports all the modules to extract documentation, it actually executes my main function (which starts the tool), obviously causing errors.

#### Proposal
I suggest that pdoc skips all the `__main__.py` modules. Or, even better, that an option to choose is added.
The `__main__.py` modules are added for the sole purpose of making a package "excutable", therefore are not likely to contain useful API documentation.

#### Alternatives
The issue could probably be circumvented with the guard `if __name__ == "__main__"` in `__main__.py`
However, that "if" is not necessary for the regular usage of the package, and the [docs](https://docs.python.org/3/library/__main__.html) also suggest that.

We should not need to change working source code in order to make pdoc work.

Thank you

**Comment by mhils** [comment]
Thanks for the pointer to the official docs, I somehow thought that `__main__.py` files should also have `if __name__ == "__main__"` guards. If the docs say that's not necessary we should absolutely respect that and ignore those files by default.

**Comment by mhils** [comment]
#439 fixes this. If you explicitly want `__main__` to be documented, you can include it when invoking pdoc like so:
```
pdoc my_module my_module.__main__
```
