### ISSUE TITLE
Nested classes with annotation feature

### ISSUE THREAD

**Issue by Dliwk** [mitmproxy/pdoc#440]
#### Problem Description
Seems like pdoc can't handle references to nested class when annotations feature is enabled.

#### Steps to reproduce the behavior:
```python
from __future__ import annotations

class Foo:
    class Bar:
        pass

    def __init__(self, bar: Bar):
        self.bar = bar
```
2. `pdoc module.py`
3. `Warn: Error parsing type annotation Bar for module.Foo.__init__. Import of Bar failed: name 'Bar' is not defined`

#### System Information
pdoc: 12.2.0
Python: 3.10.5
Platform: Linux-5.18.13-200.fc36.x86_64-x86_64-with-glibc2.35

**Comment by mhils** [comment]
Thanks for the concise description! Fixed in #441.
