### ISSUE TITLE
Customizable module vs submodule nesting?

### ISSUE THREAD

**Issue by bigpick** [mitmproxy/pdoc#446]
👋 not particular bug or feature request (per-se) but doesn't look like there's any other recommended place for discussion/question on pdoc related things; Apologies if this should be somewhere else.

### Info / Question

I've been looking at trying to create a site that would serve as the single/top level location for a set of modules that are common to a user or org, say

```
module_a
module_b
module_c
```

where each module is its own published package; rather than having a site for each of the individual packages, I wanted to try to have a top-level meta repo/package that contains the above as children, and then generate a single site with nested structure to each module's appropriate API documentation; i.e

```
meta-package
  src
    meta-package
      __init__.py

 (then as dependency.txt/pyproject.toml w.e python deps)
    module_a = *
    module_b = *
    module_c = *
```

From what I've tried, `pdoc` seems to be the nicest thing for doc generation, but the problem I have is that since I'm trying to do this in a way that each of the children modules is actually just a dependency, they don't end up as submodules in the pdoc output.

```
pdoc meta-package
```

Expectedly generates only the meta-package's `__init__.py` docs.

```
pdoc meta-package module_a module_b module_c
```

Generates all of the code docs as top-level "Available Modules" with a blank index page; i.e.

```
Available Modules
meta-package
module_a
module_b
module_c
```

What really I'm looking for something like the following, which wouldn't be able to be achieved (IIUC? I've read through the pdoc code and doesn't seem to be any thing related to this) unless there was a way to specify directly if a given module is supposed to be treated like a sub or not:

```
Contents
<meta-package __init__ rendering> as top level index page

Submodules
module_a
module_b
module_c
```

.. Is what I'm looking to do an anti-pattern/not really something that should ever be done that way? If so, sorry for the noise -- just was curious if anyone had tried/thought of/achieved something similar. 

The only thing I've been able to find that sort of gets at what I am looking for is instead of including as proper python deps, including the module_*'s actual code repo as git submodules then doing some crazy `mv`'ing and logic to stuff each child modules source code as a fake-submodule in the meta-package's source dir before running `pdoc meta-package`, but this is not really nice to do IMO.

**Comment by mhils** [comment]
You can pass multiple packages to pdoc to have them documented in one single invocation:
```shell
pdoc module_a module_b module_c
```
This generates a top-level `index.html`, which you can customize by [overriding](https://pdoc.dev/docs/pdoc.html#edit-pdocs-html-template) the [`index.html.jinja2`](https://github.com/mitmproxy/pdoc/blob/main/pdoc/templates/default/index.html.jinja2) template. Would that satisfy your use case?

**Comment by bigpick** [comment]
hey, thanks for the quick response! 

Hrm, that may be enough.

Though, one problem that I could see with that, maybe, is

> ```
> If there is one common parent module for all documented modules, redirect there immediately.
> This makes a package's `__init__.py` the main entrypoint by default.
> A custom template could override this by setting root_module_name to false before `{% extend ... %}`.
> #}
> ```

... so the problem with doing `pdoc module_a module_b module_c` and then customizing the `index.html.jinja2` to organize accordingly is that there's still no top level content index page (the `meta-package`'s `__init__.py` file's contents) since there's no top-level package across all them, technically; the meta-package doesn't technically own them still, since they're just imported deps:

```
pdoc meta-package module_a module_b module_c
```

I guess though maybe could stuff that into the custom index jinja template too? would need to do something to try to rip out the `meta-pkg` module from `all_modules` I suppose?

**Comment by mhils** [comment]
I'm not sure if I understand the role of your metapackage. I'd just invoke pdoc with your individual modules and then stuff your top-level content into `index.html.jinja2`. The comment in the default template only explains that if only one package is documented, the index page is skipped and we redirect to the oackage's `__init__.py`. In your case you'd have actual content in index.html.

**Comment by bigpick** [comment]
After playing around with this a bit, the above solution looks like it should be enough for what I'm trying to do I think, yeah.

```python
    render.configure(docformat="google", template_directory= ... / "pdoc-template")
    pdoc(*modules, output_directory=out)
```

with a custom `index.html.jinja2` thats a mix of basically the module page + a list of hardcoded values to render into the sidebar (which matches those populated in `modules` in the py code that renders the pages to the local dir) seems to be what I need

Thanks!

**Comment by mhils** [comment]
Excellent, thanks!
