### ISSUE TITLE
Integrating pdoc / using it as a library - usage of template macros

### ISSUE THREAD

**Issue by vsajip** [mitmproxy/pdoc#453]
#### Problem Description

In the [documentation about integrating with other systems](https://pdoc.dev/docs/pdoc.html#integrate-pdoc-into-other-systems), it's recommended to use a custom `frame.html.jinja2` template. However, my use case is to make use of `pdoc` to generate tooltips, so I need to use the functionality which is in `module.html.jinja2` - for example, the `member` macro. However, I can't use just the macros in another template without redefining both `frame.html.jinja2` (to get rid of the standard HTML header/body etc.) and then inheriting `module.html.jinja2`. However, if the macros were separated out into their own template, I could just include that in my custom template.

#### Proposal
Separate out the macros from `module.html.jinja2` into their own template, which is then included by `module.html.jinja2`.

#### Alternatives
It works to just copy the macros from `module.html.jinja2` to my custom template, of course.

#### Additional context
None.

**Comment by mhils** [comment]
This is a very cool use case! However I would recommend to just copy the macros into your custom template. Generally speaking we have a stable public Python API (https://pdoc.dev/docs/pdoc/doc.html), but the template may receive breaking changes going forward. I wouldn't want others to depend on it too much. :)

**Comment by vsajip** [comment]
OK, fair enough - I've already done that :smile:

And thanks very much for your work on `pdoc` :clap:

**Comment by vsajip** [comment]
In case you're interested how the tooltips look (from [here](https://docs.red-dove.com/python-gnupg/index.html)):

![ss13a](https://user-images.githubusercontent.com/130553/200948606-63cd7828-d731-4d83-948f-2f9fc101421b.png)

**Comment by mhils** [comment]
Awesome, thanks for sharing! 🍰
