### ISSUE TITLE
Enumeration Members Without Docstring Do Not Get Rendered Anymore Since v12.2.0 

### ISSUE THREAD

**Issue by lovetheguitar** [mitmproxy/pdoc#455]
#### Problem Description
With pdoc==12.1.0 enumeration members are rendered nicely, with and without a docstring.
After upgrading to 12.2.0 all the enumarations get rendered as "empty classes", when not every single item has a docstring.

I saw https://github.com/mitmproxy/pdoc/issues/411 which seems to improve dataclass documentation but IMHO broke enumeration documentation.

**Comment by mhils** [comment]
Thanks for the report! 🍰 I'll ship a patch release with a fix. :)

**Comment by lovetheguitar** [comment]
> Thanks for the report! 🍰 I'll ship a patch release with a fix. :)

Very welcome. Thanks for the blazingly fast fix! 🎉
