### ISSUE TITLE
Documentation in the presence of an `__init__.py` with imports

### ISSUE THREAD

**Issue by Hibou57** [mitmproxy/pdoc#46]
Please, how exactly is supposed to be documented, a package with an `__init__.py` containing imports? Is _pdoc_ supposed to document the imported items in-place? It seems to not do it, and just listing sub-modules, and I wonder if it's the expected behaviour or not.

**Comment by BurntSushi** [comment]
Here's an example: https://github.com/BurntSushi/nfldb/blob/master/nfldb/__init__.py

And the docs: http://pdoc.burntsushi.net/nfldb

I don't know what "document the imported items in-place" means. All you need to do is follow the rules for public identifiers described here: http://pdoc.burntsushi.net/pdoc

**Comment by rgaduput** [comment]
Is there any issue with documentation site ? some can't access http://pdoc.burntsushi.net/nfldb .

**Comment by BurntSushi** [comment]
@rgaduput Why are you commenting in an issue that is completely unrelated to pdoc.burntsushi.net? Please make new issues for new problem.

The answer is that I took the site down. It's not coming back.
