### ISSUE TITLE
Better formatting for parameter descriptions

### ISSUE THREAD

**Issue by tez4** [mitmproxy/pdoc#467]
#### Problem Description

At the moment, the pdoc generates documentation that looks like this:
![image](https://user-images.githubusercontent.com/76485075/203059948-4211d6ef-7884-41e4-aa18-65cecb90a68e.png)

I would like my documentation to be formatted in a more readable way. This looks more like what I want:
![image](https://user-images.githubusercontent.com/76485075/203060014-2f634038-a339-4c8c-9177-a08e90a012bd.png)

#### Proposal

Can an option be added that allows users to easily customize the look and feel of the documentation?

#### Alternatives

Is it already possible to create the kind of documentation I would like using pdoc?

#### Additional context

I just love how easy it is to create a documentation using pdoc and would love it, if this kind of customization would be possible. Thanks for developing open source.

**Comment by mhils** [comment]
You can 

1. customize the pdoc HTML/CSS: https://pdoc.dev/docs/pdoc.html#edit-pdocs-html-template
2. change how pdoc converts Google-style docstrings (?) into Markdown: https://github.com/mitmproxy/pdoc/blob/main/pdoc/docstrings.py#L90-L106

My personal (subjective) take is that type information belongs into type annotations, at which point you can probably just use CSS hackery to get from something that looks like the first screenshot to something that looks like the second one. :)

**Comment by tez4** [comment]
Thanks for helping. It's much better now :)
