### ISSUE TITLE
KeyError: "__slots__"

### ISSUE THREAD

**Issue by kamakazikamikaze** [mitmproxy/pdoc#47]
This is more likely to be package-specific but I'm not sure if this has to do with the target package or an internal bug in pdoc.

I've successfully run pdoc on several instances for various packages and individual modules. However, when trying to run it against the `impacket` package (http://corelabs.coresecurity.com/index.php?module=Wiki&action=view&type=tool&name=Impacket) it will run into an error in a subdirectory. The stacktrace eventually leads to "KeyError: '**slots**'".

**Comment by mhils** [comment]
This may be late, but this is fixed now! 😄
