### ISSUE TITLE
Adding documentation of subfolders

### ISSUE THREAD

**Issue by Benji377** [mitmproxy/pdoc#471]
#### Problem Description
It's not really a bug, I'm just not able to figure out how I could generate the documentation of my project.
I have a project structure like this:
```
RASPIRUS
|   .gitattributes
|   .gitignore
|   LICENSE
|   main.py
|   README.md
|   requirements.txt
|   tests.py
|           
+---backend
|   |   .env
|   |   BigHash.db
|   |   file_module.py
|   |   file_scanner_module.py
|   |   hash_api_module.py
|   |   main.py
|   |   
|   +---SignatureLists
|   |       VirusShare_00000.md5
|   |       VirusShare_00001.md5
|   |       VirusShare_00002.md5
|   |       ...
|   |       VirusShare_00442.md5
|   |       
|   +---temp
|   |       test.json
|           
+---Diagramme
|       MaturaAktivitaet.drawio
|       MaturaBOM.drawio
|       MaturaUseCase.drawio
|       
+---frontend
|   |   utility.py
|   |   
|   +---images
|   |   |   success_image.png
|   |   |   
|   |   \---icons
|   |           back_arrow.png
|   |           cancel_sign.png
|   |           check_mark.png
|   |           expand_arrow.png
|   |           logs_book.png
|   |           refresh_icon.png
|   |           
|   +---pages
|   |   |   ClearPage.py
|   |   |   InfoPage.py
|   |   |   LoadingPage.py
|   |   |   MainPage.py
|   |   |   SettingsLogPage.py
|   |   |   SettingsPage.py
|   |   |   VirusPage.py
|   | 
|   |           
|   +---popups
|   |   |   DoubleButtonDialog.py
|   |   |   SingleButtonDialog.py
|           
+---testing
|   \---files
|       |   dummy1.txt
|       |   dummy2.txt
|       |   dummy3.txt
|       |   
|       \---subfolder
|               dummy1.txt
|               dummy2.txt
|               dummy3.txt
```

And I would like to create the documentation of it by including all files ending with `.py`. Following the [documentation I found online](https://pdoc.dev/docs/pdoc.html), I executed the command `pdoc .\Raspirus\ -o .\Raspirus\docs ` from the parent-directory of the project. But this only generated documentation for two files: `main.py` and `tests.py`. How can I instead create the documentation of all files? Can I create some sort of config file somewhere, or should I put all file-paths as command-line parameters? Or is there a better way of doing this?

#### System Information
pdoc: 12.3.0
Python: 3.9.13
Platform: Windows-10-10.0.22621-SP0

**Comment by mhils** [comment]
I think the best approach here is to build Python modules (with `__init__.py` files) instead of arbitrary file collections. Alternatively, you can of course pass all files individually.
