### ISSUE TITLE
Methods are reported as Static Methods with Python 3

### ISSUE THREAD

**Issue by achille-roussel** [mitmproxy/pdoc#48]
Hello,

First of all thanks a lot for pdoc which is a wonderful tool and a pleasure to work with.

I noticed that if I generate documentation with Python 3, simple methods are reported as static methods. I tried to play a bit with the source code to fix it but it didn't seem trivial (forcing method=True when creating Function objects).

It may be that the semantics of `inspect.ismethod` and `inspect.isfunction` have changed between Python 2 and Python 3 and method in types are not reported as methods anymore because they haven't been bound yet.

Is this a known issue?

I'll try to dig more into the code when I have some free time.

**Comment by achille-roussel** [comment]
May be related: http://stackoverflow.com/questions/8408910/detecting-bound-method-in-classes-not-instances-in-python-3

**Comment by nawab36085** [comment]
Hi,
Did you get it fixed. I have observed the same issue while generating the document with python3.
