### ISSUE TITLE
Custom templating with control over functions descriptions / parameters 

### ISSUE THREAD

**Issue by songololo** [mitmproxy/pdoc#480]
#### Problem Description

At the moment it doesn't appear possible to use templating to determine the html structure and class naming for function descriptions and related parameters / returns. It would help if this type of templating were possible, because then styling and structure can be set from a downstream static site generator via CSS.

#### Proposal
For example, a parameter is currently generated per below (I don't see a way to change this at present?):
```html
<ul>
  <li><strong>param_a</strong> (int): A <em>test</em> _param_.</li>
</ul>
```
Whereas it would be nice to be able to control the templating to render something like this:
```html
<div class="elem-container">
  <div class="elem-def">
    <div class="elem-name">param_a</div>
    <div class="elem-type">int</div>
  </div>
  <div class="elem-desc">A <em>test</em> _param_.</div>
</div>
```

This makes it possible to control the composition of the elements (e.g. flexbox) from downstream static site generators. e.g.

<img width="706" alt="Screenshot 2022-12-29 at 17 00 21" src="https://user-images.githubusercontent.com/4347878/209985224-08d02f2e-c901-4c6c-8f18-880177815867.png">

**Comment by mhils** [comment]
Thanks for raising this! This is a perfectly valid feature request, but I'm afraid it's out of scope for pdoc. The Google/Numpy-style docstring to HTML conversion in [pdoc.docstrings](https://github.com/mitmproxy/pdoc/blob/main/pdoc/docstrings.py) is already a bit of a regex mess, and I don't want to extend that to allow any customizability.

@pawamoy's fantastic https://github.com/mkdocstrings/griffe may be a better fit here. pdoc's philosophy is that docstrings are really just plain Markdown.

**Comment by pawamoy** [comment]
@songololo if you give a try to mkdocstrings (and Griffe, by extension), I would very much welcome any feedback or suggestions about the HTML structure and the CSS classes that are used, as they are not my cup of tea!

**Comment by songololo** [comment]
Thanks @mhils and @pawamoy - appreciate the heads-up re: `griffe`.

I've given it a go in [yapper](https://github.com/benchmark-urbanism/yapper) (more specifically in the [parser](https://github.com/benchmark-urbanism/yapper/blob/main/yapper/parser.py)) and it has made things a fair bit easier than using AST and `docstring_parser`. I'm sure there's a better way to do things but it works for now. (`yapper` is born out of desperation of just trying to pull markdown docstrings out of python files and piping straight to downstream markdown static generators.)

What would be ideal from here is to have a hybrid of a templating language like used in `pdoc` and a python module parser such as `griffe` as it then becomes possible to do things with minimal fuss...

**Comment by pawamoy** [comment]
Hmmm that sounds like mkdocstrings! mkdocstrings is a plugin for MkDocs that uses Griffe to collect data about your Python package, and then renders these data using Jinja templates. The templates are over ridable, so you can fully customize the output.
If I misunderstood your last comment though, just ignore mine :)
