### ISSUE TITLE
pdoc doesn't find methods of cython extension types

### ISSUE THREAD

**Issue by jswhit** [mitmproxy/pdoc#49]
Ran into this when trying to use pdoc to generate html docs from docstrings in my project (netcdf4-python).  If you have a Cython extension type, for example

```
cdef class Shrubbery:
   """A class of Shrubbery"""
   cdef int width, height
   def __init__(self, w, h):
        self.width = w
        self.height = h
   def describe(self):
        """descibe the shubbery"""
        print "This shrubbery is", self.width, \
            "by", self.height, "cubits."
```

pdoc will generate the documentation for the class, and it's instance variables, but not it's methods.  Is this a known issue?  If so, are there workarounds?

**Comment by jswhit** [comment]
To demonstrate, create a package Shrubbery with

setup.py
Shrubbery/__init__.py
Shrubbery/_Shrubbery.pyx

setup.py:

    from distutils.core  import setup, Extension
    from Cython.Build import cythonize
    extensions = [Extension("Shubbery._Shrubbery",["Shrubbery/_Shrubbery.pyx"])]
    ext_modules = cythonize(extensions)
    setup(name = "Shrubbery",
      cmdclass = {},
      version = "0.0.1",
      long_description = "fake module",
      packages = ['Shrubbery'],
      ext_modules = ext_modules)

Shrubbery/__init__.py:

    from ._Shrubbery import Shrubbery, __doc__
    __all__ = ['Shrubbery']

Shrubbery/_Shrubbery.pyx:

    """
    The Shrubbery Module
    """
    cdef class Shrubbery:
       """A class of Shrubbery"""
       cdef int width, height
       def __init__(self, w, h):
            self.width = w
            self.height = h
       def describe(self):
            """descibe the shubbery"""
            print "This shrubbery is", self.width, \
                "by", self.height, "cubits."

After installation, `pdoc Shrubbery` produces:

    Module Shrubbery
    ----------------
    The Shrubbery Module

    Classes
    -------
    Shrubbery
        A class of Shrubbery

        Ancestors (in MRO)
        ------------------
        Shrubbery.Shrubbery
        __builtin__.object

Note that the `describe` method is missing.

**Comment by jswhit** [comment]
Here's my workaround, in case it helps 

    diff --git a/pdoc/__init__.py b/pdoc/__init__.py
    index d0ec24f..9b7cfdb 100644
    --- a/pdoc/__init__.py
    +++ b/pdoc/__init__.py
    @@ -570,7 +570,7 @@ class Module (Doc):
                 # modules and module level variables.
                 if inspect.isfunction(obj) or inspect.isbuiltin(obj):
                     self.doc[name] = Function(name, self, obj)
    -            elif inspect.ismethod(obj):
    +            elif inspect.ismethod(obj) or inspect.ismethoddescriptor(obj):
                     self.doc[name] = Function(name, self, obj)
                 elif inspect.isclass(obj):
                     self.doc[name] = Class(name, self, obj)
    @@ -912,6 +912,9 @@ class Class (Doc):
                 if inspect.ismethod(obj):
                     self.doc[name] = Function(name, self.module, obj.__func__,
                                               cls=self, method=True)
    +            elif inspect.ismethoddescriptor(obj):
    +                self.doc[name] = Function(name, self.module, obj,
    +                                          cls=self, method=False)
                 elif inspect.isfunction(obj):
                    self.doc[name] = Function(name, self.module, obj,
                                                cls=self, method=False)

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. This should be fixed with the latest release. 😃
