### ISSUE TITLE
Broken links for inherited methods 

### ISSUE THREAD

**Issue by medecau** [mitmproxy/pdoc#490]
#### Problem Description
I subclassed a class from the standard library.
The inherited methods at the bottom of the documentation is trying to link to non-existing method documentation.

#### Steps to reproduce the behavior:
1. subclass a class from any standard library module
2. run pdoc on the module with the subclass
3. scroll down to the inherited methods listing

#### System Information
pdoc: 12.3.0
Python: 3.11.0
Platform: macOS-13.1-arm64-arm-64bit

**Comment by mhils** [comment]
Could you please provide a minimal, self-contained example?

**Comment by mhils** [comment]
Could you please provide a minimal, self-contained example?

**Comment by medecau** [comment]
@mhils I noticed it as I worked to document `sched2`.

See: https://medecau.github.io/sched2/

**Comment by mhils** [comment]
Thanks! This showed up here because your subclass has the same name as the parent class. Fixed in #493.

**Comment by mhils** [comment]
Thank you for sponsoring me on GitHub, really appreciate it! 😄❤️
