### ISSUE TITLE
pdoc.help(thing)

### ISSUE THREAD

**Issue by hhoppe** [mitmproxy/pdoc#494]
I like the documentation formatting of `pdoc` and sometimes would like to use it on individual objects rather than modules.

In jupyter notebooks, one can use `help(thing)` or `%pinfo thing` (which is the same as `?thing`) but these output plain colored text which is unattractive.

Would it be feasible to offer `pdoc.help(thing)` for nice HTML-formatted documentation of an object?

A quick prototype using the existing `pdoc` API is something like:

```python
import pdoc

def pdoc_help(thing: Any) -> None:
  import IPython.display
  original_module = thing.__module__
  try:
    module_name = 'dummy_tmp_module'
    module = types.ModuleType(module_name)
    sys.modules[module_name] = module
    setattr(module, thing.__name__, thing)
    thing.__module__ = module_name
    doc = pdoc.doc.Module(module)
    pdoc.render.configure(docformat='google', math=True, search=False, show_source=True)
    html_text = pdoc.render.html_module(module=doc, all_modules={module_name: module})
    IPython.display.display(IPython.display.HTML(html_text))
  finally:
    thing.__module__ = original_module
    del sys.modules[module_name]

pdoc_help(pdoc.render.configure)
```

This seems promising in that it already looks quite nice.  There are of course some issues:
- The temporary modification of `sys.modules` and `thing.__module__` might be unwise.
- Annotation types are unrecognized in the new context, e.g., "UserWarning: Error parsing type annotation Literal['markdown', 'google', 'numpy', 'restructuredtext']".
- The HTML includes a confusing `dummy_tmp_module` header.
- There is a large padding=400 on the left side.

Is this an interesting direction, or is it too far beyond the current module-oriented focus of `pdoc`?

**Comment by mhils** [comment]
I think that's really a nice application, but a bit beyond what pdoc is meant to do. I would be happy to see this exist as a project built on top of pdoc though! :)

It looks like you can add "magic commands" to IPython: https://ipython.readthedocs.io/en/stable/interactive/magics.html. So one could write a `jupyter_pdoc` package which (once installed via pip) provides `%pdoc` in notebooks. That'd be a nice user experience.

I've played around with your example a bit, here's a slightly revised version:

```python
from typing import Any
import inspect
from pathlib import Path

import pdoc
import IPython.display

template_dir = Path(".")
(template_dir / "frame.html.jinja2").write_text("""
<div>
    {% block content %}{% endblock %}
    {% filter minify_css %}
            <style>{% include "syntax-highlighting.css" %}</style>
            <style>{% include "theme.css" %}</style>
            <style>{% include "content.css" %}</style>
    {% endfilter %}
</div>
""")
(template_dir / "module.html.jinja2").write_text("""
{% extends "default/module.html.jinja2" %}
{% macro is_public(doc) %}
    {% if doc.qualname.startswith(show_only) or show_only.startswith(doc.qualname) %}
        {{ default_is_public(doc) }}
    {% endif %}
{% endmacro %}
{% block module_info %}{% endblock %}
""")


def pdoc_help(thing: Any) -> None:
    module = inspect.getmodule(thing)
    doc = pdoc.doc.Module(module)
    pdoc.render.configure(
        docformat='google', 
        math=True, 
        show_source=True,
        template_directory=template_dir,
    )
    pdoc.render.env.globals["show_only"] = getattr(thing, "__qualname__", "")
    html_text = pdoc.render.html_module(module=doc, all_modules={})
    IPython.display.display(IPython.display.HTML(html_text))

pdoc_help(pdoc.render.configure)
```

The main change is that this uses the existing module and instead filters the module contents by redefining `is_public`. :) The padding/nav stuff is removed by redefining `frame.html.jinja2`. The top-level module information is removed by redefining `module_info`. :)

**Comment by hhoppe** [comment]
This is wonderful; staying in the same module makes everything much simpler!

I experimented with a few changes:

- Put the creation of `template_dir` files inside `pdoc_help` and used `tempfile` for cleanup:
```python
    with tempfile.TemporaryDirectory() as temp_dir:
      template_dir = pathlib.Path(temp_dir)
      ...
```
- Modified `html_text` just a bit (I don't know `jinja2` -- maybe that's a better place to do this):
```python
    html_text = pdoc.render.html_module(module=doc, all_modules={})

    # Limit the maximum width.
    html_text = '<style>main.pdoc {max-width:784px;}</style>' + html_text

    # The <h6> tags would appear in the Jupyterlab table of contents, so change to <div>.
    style = 'font-size: 14px; font-weight: 700;'
    html_text = html_text.replace('<h6', f'<div style="{style}"').replace('</h6>', '</div>')

    IPython.display.display(IPython.display.HTML(html_text))
```

Please feel free to take ownership of this; I am still a newbie at the full release process.

**Comment by hhoppe** [comment]
- I also changed the comparison to:
```
          {% if doc.qualname == show_only %}
```
(I didn't understand the motivation for `startswith()`, and for my use cases that would show more than one function.)

**Comment by mhils** [comment]
Very nice! 😃 

> (I didn't understand the motivation for `startswith()`, and for my use cases that would show more than one function.)

The point with `startswith` is that you may want to document `Foo.bar`, but if `Foo` is not included in the documentation, its children are not rendered either. The correct way to do this is probably something like this (untested):
```python
if all(
  x == y 
  for x, y in zip(
    doc.qualname.split("."),
    show_only.split(".")
  )
)
```

> Please feel free to take ownership of this

I do appreciate it, but I don't have a horse in the jupyter notebook race here - feel free to take this further, I need to cut back on the number of side projects. 😅 Happy to help out with pdoc-related questions where they arise.

**Comment by hhoppe** [comment]
Your last suggestion was again perfect; many thanks for all your help!
For completeness, here is the final version that I put into my [toolbox](https://github.com/hhoppe/hhoppe-tools):
```python
def pdoc_help(
    thing: Any,
    /,
    *,
    docformat: Literal['markdown', 'google', 'numpy', 'restructuredtext'] = 'google',
) -> None:
  """Display `pdoc` (HTML) documentation for a function or class.

  >>> import IPython.display
  >>> htmls = []
  >>> with unittest.mock.patch('IPython.display.display', htmls.append):
  ...   pdoc_help(dataclasses.dataclass)
  >>> (html,) = htmls
  >>> assert 'View Source' in html.data, html.data
  """
  # Adapted from https://github.com/mitmproxy/pdoc/issues/494.
  import pdoc

  with tempfile.TemporaryDirectory() as temp_dir:
    template_dir = pathlib.Path(temp_dir)
    (template_dir / 'frame.html.jinja2').write_text(
        """\
      <div>
          {% block content %}{% endblock %}
          {% filter minify_css %}
                  <style>{% include "syntax-highlighting.css" %}</style>
                  <style>{% include "theme.css" %}</style>
                  <style>{% include "content.css" %}</style>
          {% endfilter %}
      </div>"""
    )
    (template_dir / 'module.html.jinja2').write_text(
        """\
      {% extends "default/module.html.jinja2" %}
      {% macro is_public(doc) %}
          {% if should_show(doc.qualname) %}
              {{ default_is_public(doc) }}
          {% endif %}
      {% endmacro %}
      {% block module_info %}{% endblock %}
      """
    )
    module = inspect.getmodule(thing)
    if module is None:
      raise ValueError(f'Cannot identify module for {thing=}.')
    doc = pdoc.doc.Module(module)
    pdoc.render.configure(
        docformat=docformat, math=True, show_source=True, template_directory=template_dir
    )

    def should_show(qualname: str) -> bool:
      thing_name = getattr(thing, '__qualname__', '')
      return all(x == y for x, y in zip(qualname.split('.'), thing_name.split('.')))

    pdoc.render.env.globals['should_show'] = should_show
    html = pdoc.render.html_module(module=doc, all_modules={})

  # Limit the maximum width.
  html = '<style>main.pdoc {max-width: 784px;}</style>\n' + html

  # The <h6> tags would appear in the Jupyterlab table of contents, so change to <div>.
  html = '<style>.myh6 {font-size: 14px; font-weight: 700;}</style>\n' + html
  html = html.replace('<h6', '<div class="myh6"').replace('</h6>', '</div>')

  display_html(html)
```

**Comment by mhils** [comment]
Awesome, thanks for sharing! 😃 🎉
