### ISSUE TITLE
Enum members not displayed if their name begins with an underscore

### ISSUE THREAD

**Issue by jamesbcd** [mitmproxy/pdoc#496]
#### Problem Description
Pdoc doesn't seem to display Enum members if their name begins with an underscore.

#### Steps to reproduce the behavior:
1. In a new project directory, create the following file `underscore_enum_test.py`
```python
from enum import Enum, auto

class MyEnum(Enum):
    ENUM_A = auto()
    _ENUM_B = auto()
    ENUM_C = auto()
```
3. Install pdoc, and launch it: `pdoc underscore_enum_test.py'
4. The documentation in the browser displays ENUM_A and ENUM_C, but not _ENUM_B, due to its initial underscore.

#### System Information
pdoc: 12.3.1
Python: 3.10.9
Platform: macOS-13.1-arm64-arm-64bit

**Comment by mhils** [comment]
This is intentional, see https://pdoc.dev/docs/pdoc.html#control-what-is-documented.
