### ISSUE TITLE
Support in VS Code

### ISSUE THREAD

**Issue by rani-pinchuk** [mitmproxy/pdoc#503]
#### Pdoc allows markdown in docstrings, but in VS Code the markdown is not supported in documentation shown when hovering over the code

I guess that this is a suggestion for extension in VS Code, or for patching one of VS Code existing extensions.

When creating documentation that is pdoc compliant while editing the code using VS Code, the documentation is shown nicely when hovering the over the code.

Consider the following example.
![pdoc_in_vscode](https://user-images.githubusercontent.com/33353578/216561437-8c5b1dd6-6174-4ad3-a26a-889f4affaa40.png)
When hovering over the method `my_method` in VS Code, we get a rendered documentation, but not all markdown hints are renedered. The back-ticks are renedered correctly but the two astericks are not.

So I wonder if anyone is aware of an extension to VS Code that fixes this behavior, or if anyone is planning to write such an extension.

**Comment by mhils** [comment]
That sounds interesting, but it's definitely out of scope for pdoc at the moment! I'm happy for third-party extensions to show up of course. The big benefit of Markdown is that it remains human-readable even if unrendered. If you want a preview during editing, pdoc's webserver does livereload. :)
