### ISSUE TITLE
"Cannot determine where X is coming from" with TypedDict inheritance

### ISSUE THREAD

**Issue by slhck** [mitmproxy/pdoc#504]
#### Problem Description

I cannot get annotations to work with inherited TypedDics.

#### Steps to reproduce the behavior:

Consider the following TypedDicts in `api.py`

```python
class GeneralApiParams(TypedDict):
    start_time: NotRequired[str]
    """The start time of the measurement in ISO-8601 format."""
    end_time: NotRequired[str]
    """The end time of the measurement in ISO-8601 format."""
    measurement_id: NotRequired[int]
    """The measurement ID."""
    client_uuid: NotRequired[str]
    """The client UUID."""
    tags: NotRequired[List[str]]
    """The tags of the client."""


class MeasurementsApiParams(GeneralApiParams):
    type: NotRequired[
        Literal[
            "VideoMeasurement",
            "WebMeasurement",
            "SpeedtestMeasurement",
            "NetworkMeasurement",
        ]
    ]
    """The type of the measurement."""
```

Which I import in `__init__.py` like so:

```python
from .api import (
    GeneralApiParams,
    MeasurementsApiParams,
)

__all__ = [
    "GeneralApiParams",
    "MeasurementsApiParams",
]
```

Running pdoc gets me:

```
➜ pdoc -d google -o docs ./measurement_api
Warn: Cannot determine where measurement_api.MeasurementsApiParams.start_time is taken from, assuming current file. (.../lib/python3.11/site-packages/pdoc/doc.py:647)
Warn: Cannot determine where measurement_api.MeasurementsApiParams.end_time is taken from, assuming current file. (.../lib/python3.11/site-packages/pdoc/doc.py:647)
Warn: Cannot determine where measurement_api.MeasurementsApiParams.measurement_id is taken from, assuming current file. (.../lib/python3.11/site-packages/pdoc/doc.py:647)
Warn: Cannot determine where measurement_api.MeasurementsApiParams.client_uuid is taken from, assuming current file. (.../lib/python3.11/site-packages/pdoc/doc.py:647)
Warn: Cannot determine where measurement_api.MeasurementsApiParams.tags is taken from, assuming current file. (.../lib/python3.11/site-packages/pdoc/doc.py:647)
```

The resulting documentation shows:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/582444/216657917-ef57d2ca-cb66-497e-acc4-b84641cb0158.png">

So it shows as inherting from a builtin dict, which it should not, because it inherits from the other TypedDict.

#### System Information

```
pdoc: 12.3.1
Python: 3.11.0
Platform: macOS-12.6.3-arm64-arm-64bit
```

**Comment by mhils** [comment]
Thanks for the nice report. This is a relatively fundamental problem because `TypedDict` botches its `__mro__`, which means we normally cannot determine the base class via dynamic analysis. @krassowski came up with a nice workaround in https://github.com/sphinx-doc/sphinx/issues/9290, which I've adapted for pdoc. If you add `TypedDict` as a second base class for `MeasurementsApiParams`, things should now work as expected. It would be nice if we wouldn't have to do this, but that requires an upstream fix in CPython. :)

**Comment by slhck** [comment]
Thanks for the quick response and fix! 🎉
