### ISSUE TITLE
Folding large constants?

### ISSUE THREAD

**Issue by woodruffw** [mitmproxy/pdoc#507]
First of all, thanks for `pdoc`! I'm a very happy user, both on my hobby projects and professionally.

#### Problem Description

I'm working to port a handful of repositories away from `pdoc3`, for well-trodden reasons. Most of the differences between the two are minor, but one that I'm currently running into is how `pdoc` renders large constants: it renders the entire constant, rather than either truncating or folding it.

For example, this render:

![](https://thing-in-itself.net/u/pnrXNJLfNhk.png)

...becomes this in `pdoc`:

![](https://thing-in-itself.net/u/RPVnXTfGjvk.png)

(it goes on for quite a bit after that :slightly_smiling_face:)

#### Proposal

It'd be nice to have either a default or a configurable option for truncating or folding large constants! I'm not sure if there's a great heuristic for this, so offering folding (i.e., requiring the user to click a `<details>` element to unfurl) might be slightly better for UX.

#### Alternatives

I assume I could do this with some template hackery on my own, but I figured this would be a reasonable thing to raise upstream!

#### Additional context

No other context. If this is functionality that you'd be interested in, I'd be willing to make an attempt at implementing it. Thanks again!

**Comment by mhils** [comment]
Hi @woodruffw! Thank you for the kind words. I absolutely agree this is something we should fix. I'd be happy with either truncation and folding, both are clear improvements. Please shoot a PR with whatever you think works best, and let me know if I can help with anything!

**Comment by woodruffw** [comment]
Opened #508 with my attempt!
