### ISSUE TITLE
video tutorials

### ISSUE THREAD

**Issue by QuantFreedom1022** [mitmproxy/pdoc#512]
hey i am very very very new to pdoc and it is super confusing for me to understand how any of this works.

i am using mkdocs and i am looking at the example but still pretty confused because there doesn't seem to be that many examples in general using a python file to generate the docs ... most of the exmaples seem to be simple examples using the terminal 

i tried to search youtube and could only find one video but they use pdoc3

so i am wondering does anyone know a good website or youtube video that explains how to use pdoc ?

all i am trying to do is read the doc strings in each one of my files and turn them into .md so i can use it for mkdocs but there seems to be no simple example of that

**Comment by mhils** [comment]
> so i am wondering does anyone know a good website or youtube video that explains how to use pdoc ?

pdoc's documentation lives at https://pdoc.dev/. There's a quickstart example in the docs. I'm not aware of any videos. :)

> all i am trying to do is read the doc strings in each one of my files and turn them into .md so i can use it for mkdocs but there seems to be no simple example of that

pdoc only outputs HTML, not Markdown. If you are using mkdocs you many want to check out https://mkdocstrings.github.io/ or https://github.com/mitmproxy/pdoc/tree/main/examples/mkdocs.

**Comment by QuantFreedom1022** [comment]
@mhils ... huh ... in my question i said i have already visited those places you have linked and its not giving me the info i need ... so not really sure what you linked me to those things 

do you know of any other resources that teach people how to generate api documentation using pdoc from a python file like the make.py in the mkdocs examples

**Comment by mhils** [comment]
> @mhils ... huh ... in my question i said i have already visited those places you have linked and its not giving me the info i need ... so not really sure what you linked me to those things

I'm sorry, but I couldn't infer from your questions which things you already looked at.

> do you know of any other resources that teach people how to generate api documentation using pdoc from a python file like the make.py in the mkdocs examples

There are a whole bunch of pdoc tutorials out there, but they are about generating HTML, not Markdown. I don't think pdoc is the tool you are looking for.

**Comment by QuantFreedom1022** [comment]
@mhils also can you please keep this open because someone out there might know of a place that shows what i am looking to do.

**Comment by mhils** [comment]
There's nothing actionable for pdoc here, so this will stay closed. Others can still comment if they find this issue via search.
