### ISSUE TITLE
include readme.md

### ISSUE THREAD

**Issue by chanansh** [mitmproxy/pdoc#513]
#### Problem Description
I don't see away to add manually typed documentation in the project/package level.

#### Proposal
I would like to include README.md of the main path (and maybe all others) to include manual entered documentation rather than just the automatic one

#### Alternatives
?
#### Additional context
 trying to build a python package

**Comment by mhils** [comment]
Have you seen https://pdoc.dev/docs/pdoc.html#include-markdown-files? :)
