### ISSUE TITLE
Pdoc commandline script name conflict

### ISSUE THREAD

**Issue by karimbahgat** [mitmproxy/pdoc#52]
When using pdoc for the first time I encountered an error with the commandline script that got placed into Python27/Scripts. First off, the file did not have the .py extension, so I had to add it. Secondly, when the commandline script tried importing pdoc from site-packages it just ended up importing itself (because the commandline script had the same name as the site-packages pdoc), resulting in a nameerror when trying to run the `import_module()` function. Changing the name of the commandline script fixed this error. 

I am surprised noone else have gotten this error? Should be a quick fix anyway. I am on Windows 8, 32 bit Py27.

**Comment by marcos-alfredo** [comment]
Had the same issue where after installing pdoc, it created a script without extension.
Using Python 2.7 and Windows 7.

**Comment by cortesi** [comment]
Pdoc now targets Python 3.6 and later. Please let us know if you still see this issue there. Thanks!
