### ISSUE TITLE
Button to show module constants is  too small on qutebrowser

### ISSUE THREAD

**Issue by adigitoleo** [mitmproxy/pdoc#523]
#### Problem Description

Aesthetic issue, the button to show module constants is too small. See screenshots, in this case it is a dictionary.

![pdoc_enum_show](https://user-images.githubusercontent.com/34595875/226773536-eec01cab-2061-48ef-aafa-73bab7690a70.png)
![pdoc_enum_show_expanded](https://user-images.githubusercontent.com/34595875/226773547-5414c050-a091-4bc0-bb8a-e30a9e6b5ccc.png)

version:
```
pdoc: 13.0.1
Python: 3.10.10
Platform: Linux-6.2.7-arch1-1-x86_64-with-glibc2.37
```

Maybe the expanded view can also be pretty-printed somehow?

Everything else looks great. Is there a way to tweak the CSS here?

**Comment by mhils** [comment]
They render properly for me [here](https://pdoc.dev/docs/pdoc/render_helpers.html#markdown_extensions), so we'd need more info on your configuration:

![image](https://user-images.githubusercontent.com/1019198/226774353-02ab33e9-e659-49b9-885b-1e91dfac65f9.png)

**Comment by adigitoleo** [comment]
Must be a browser thing, for me on [qutebrowser](https://github.com/qutebrowser/qutebrowser) (QtWebEngine based, Linux), the buttons on the page you linked also look small. It seems like these are called `view-value-button` in the CSS, I'll see if I can tweak that CSS to get something that works on qutebrowser as well.

**Comment by mhils** [comment]
To manage expectations, I don't think I want to make qutebrowser an officially supported target. If we can get it to work without introducing any additional complexity I'm happy to merge a fix, but this will neither be tested going forward nor will we accomodate for it in any particular way.
