### ISSUE TITLE
Error parsing Literal using typing_extensions

### ISSUE THREAD

**Issue by thearchitector** [mitmproxy/pdoc#526]
#### Problem Description

I'm using `pdoc` with a Python 3.7 project that relies`typing_extensions` for the `Literal` type. When creating the documentation, I get the error:

`Warn: Error parsing type annotation typing.Union[typing_extensions.Literal['strict', 'lax', 'none'], NoneType] for ....Import of strict failed: name 'strict' is not defined`.

I'd guess this is related to [this line](https://github.com/mitmproxy/pdoc/blob/main/pdoc/doc_types.py#L164-L165) being false when it should be true, but I'm not sure.

#### Steps to reproduce the behavior:

Using the following example triggers the error message:

```python
# foobar/__init__.py
from typing import Optional
from typing_extensions import Literal

class Foo:
    def __init__(self, literal_arg: Optional[Literal["strict", "lax", "none"]] = None):
        pass

__all__ = ["Foo"]
```

#### System Information

```plain
pdoc: 13.0.1
Python: 3.7.9
Platform: Windows-10-10.0.19041-SP0
```

**Comment by mhils** [comment]
Could you check if the following patch fixes it for you?
```diff
diff --git a/pdoc/_compat.py b/pdoc/_compat.py
index 5f4b90e..312ae06 100644
--- a/pdoc/_compat.py
+++ b/pdoc/_compat.py
@@ -109,8 +109,11 @@ else:  # pragma: no cover

     # There is no Literal on 3.7, so we just make one up. It should not be used anyways!

-    class Literal:
-        pass
+    try:
+        from typing_extensions import Literal
+    except ImportError:
+        class Literal:
+            pass

     # get_origin is adapted from
     # https://github.com/python/cpython/blob/863eb7170b3017399fb2b786a1e3feb6457e54c2/Lib/typing.py#L1474-L1515
```

**Comment by thearchitector** [comment]
That does look like it fixes it the problem, yes. The docs show the type as `typing_extensions.Literal` vs `Literal` but I'm not sure how much can be done about that.

**Comment by mhils** [comment]
> The idea here is to try typing_extensions and fallback to Literal if it's not available?

On Python 3.8+ we use `typing.Literal` directly (that logic sits right above the diff), for 3.7 we have so far made up a `Literal` class to simplify the logic in some places. This now tries `typing_extensions.Literal` first on 3.7.

> The docs show the type as typing_extensions.Literal vs Literal but I'm not sure much can be done about that.

3.7 is almost EOL, so I'm not going to invest any further resources here. :-)
