### ISSUE TITLE
Add support for exporting PDF files

### ISSUE THREAD

**Issue by hsiangjenli** [mitmproxy/pdoc#543]
#### Proposal
I'd like to request support for exporting documentation in PDF format in pdoc. PDF export would make it easier for users to view documentation on different devices without having to rely on an internet connection or install additional software.

**Comment by mhils** [comment]
We previously had a discussion here on adding support for Markdown export, which I decided not to declare as out of scope for the reason mentioned in https://github.com/mitmproxy/pdoc/issues/308#issuecomment-1232124627. The same arguments also apply to PDF export, so I'm sorry to say that there are no plans to add PDF export either.

That being said, the HTML files produced by pdoc are fully standalone, you can distribute a copy of pdoc's rendered output for offline viewing. It works perfectly fine without any extra software if you open them in your browser! 😃
