### ISSUE TITLE
Variable.is_classvar incorrect for classvars without type hints

### ISSUE THREAD

**Issue by yushiyangk** [mitmproxy/pdoc#545]
#### Problem Description
In `doc.py`, in the Variable class, currently the property [`is_classvar`](https://github.com/mitmproxy/pdoc/blob/986edc33d852ddd8c26a384c5d16f7e783473811/pdoc/doc.py#L1077) returns True only when the typing.ClassVar type-hint has been added.

However, by my understanding, any variable declared without `self.*` is treated as a class variable in Python, even without type-hinting or with type-hinting that does not specify typing.ClassVar. For example:

```python
class MyClass:
    class_var = 1
    also_class_var: int = 2
    explicit_class_var: ClassVar = 3

    def __init__(self):
        self.not_class_var = 4
```

The first three above should return True for `is_classvar`, and only the last should return False.

#### System Information
pdoc: 13.1.1
Python: 3.11.2
Platform: Windows-10-10.0.19044-SP0

**Comment by mhils** [comment]
> However, by my understanding, any variable declared without `self.*` is treated as a class variable in Python, even without type-hinting or with type-hinting that does not specify typing.ClassVar. 

Do you have a source for this understanding? I know that some projects follow this convention, but it's certainly not a hard rule I think. After all there wouldn't be a need for `typing.ClassVar` if this were universally agreed upon.

**Comment by yushiyangk** [comment]
[The Python docs seem to say so as well.](https://docs.python.org/3/tutorial/classes.html#class-and-instance-variables)

I think it can get quite confusing, because you could do the following, where it looks as if `my_var` behaves like an instance variable:
```python
class MyClass:
    my_var = 0
    def __init__(self):
        self.my_var = 1
```
but the assignment in `__init__` actually defines a brand new instance variable `my_var` that masks the class variable `my_var`.

You can observe this behaviour with the following script (using MyClass above):
```python
assert MyClass.my_var == 0
instance = MyClass()
assert instance.my_var == 1
del instance.my_var
assert instance.my_var == 0  # the instance variable has been deleted, so the class variable is surfaced
```

**Comment by mhils** [comment]
Yes, thanks - I'm painfully aware of the subtleties here. :) I think my point is that unconditionally treating all class-level assignments as "class variables" creates false-positives (e.g. what happens for dataclasses? Or attrs? Or pydantic?), whereas relying on `ClassVar` is unambiguous. So I actually prefer the current behavior. Is there a reason why you don't want to annotate with ClassVar?

**Comment by yushiyangk** [comment]
In my view, false negatives are no better than false positives, because you end up with variables that are documented as instance variables, but that behave as class variables, which leads to incorrect behaviour. Since type annotations explicitly optional, in an ideal scenario I believe pdoc should give the correct result regardless if it is used.

Is the problem because pdoc currently identifies member variables by parsing the AST? I can see why that would be an issue with the examples you raised. I had originally imagined that the member variables would be identified through introspection alone, which should have always given the correct interpreted result regardless of any added syntactical sugar.

**Comment by mhils** [comment]
> In my view, false negatives are no better than false positives, because you end up with variables that are documented as instance variables, but that behave as class variables, which leads to incorrect behaviour.

The benefit of false-negatives is that you can fix them with a `ClassVar` type annotation, whereas you can't easily fix false-positives (there is no `NotAClassVar`/`InstanceVar` annotation). In practice, I think we will run into significant issues with dataclasses/attrs/pydantic here. Long story short, I think expecting users to annotate with `ClassVar` if they want to make that distinction makes sense. Maybe we should just extend the docstring to mention that. :)
