### ISSUE TITLE
Allow heading level beyond 2 to show in the table of contents

### ISSUE THREAD

**Issue by revolutionisme** [mitmproxy/pdoc#547]
#### Problem Description

Currently the rendering only allows upto Markdown heading level 2 to generate the table of contents. 
For example: in the official documentation, this is (probably erroneously) marked as heading level 3 and this doesnt show in the table of contents in the sidebar. 

https://pdoc.dev/docs/pdoc.html#exclude-submodules-from-being-documented

#### Proposal
Allow customization regarding how many heading levels are allowed in the table of contents

**Comment by mhils** [comment]
You can customize heading levels by using pdoc as a library, and modifying `pdoc.render_helpers.markdown_extensions["toc"]["depth"]` before rendering. I don't think it quite crosses the bar to add a dedicated option for it. Thank you very much for pointing out the docs inconsistency! 😃
