### ISSUE TITLE
support for mermaid themes?

### ISSUE THREAD

**Issue by cpomsoft** [mitmproxy/pdoc#572]
Hi,

It's great that you support mermaid diagrams. I just wonder if 
there is any way of including support for changing the mermaid diagram theme within a docstring
when using pdoc?

For example, adding the line below (which doesn't seem to work) within a mermaid diagram:
(I've removed the triple quotes so it doesn't render here)
mermaid
...
%%{init: {'theme':'dark'}}%%

Thanks

**Comment by mhils** [comment]
Any extended Mermaid support would have to come from [markdown2](https://github.com/trentm/python-markdown2/issues/471#issuecomment-1225375172), our fantastic Markdown library. :)
