### ISSUE TITLE
readthedocs template

### ISSUE THREAD

**Issue by HananInfiniGrow** [mitmproxy/pdoc#576]
#### Problem Description

it's not clear to me how can I format the output to look in the style and feel of readthedocs. 

#### Proposal
I am looking for something similar to sphinx_rtd_theme.
so if I install pdoc[rtd] I will be able to change the theme. 

#### Alternatives
I tried mkdocs but it does not support auto-discovery properly (you have to explicitly mention things you would like to document). 

#### Additional context
pdoc rocks. sphinx the mkdocs requires too much setup. pdoc is the only to work out of the box with no hassle.

**Comment by mhils** [comment]
I appreciate that you like pdoc, but the only supported template is the default one. There is no readthedocs-like template, and we do not plan to officially support any additional templates. :)

**Comment by HananInfiniGrow** [comment]
Bummer
