### ISSUE TITLE
top level header is the same as folder name

### ISSUE THREAD

**Issue by HananInfiniGrow** [mitmproxy/pdoc#577]
#### Problem Description
my top level folder under the project root is src, e.g.

```
/root
   /src
   /tests
   /docs
```
#### Steps to reproduce the behavior:
If I run pdoc src the title of the documentation is `src`

#### System Information
pdoc: 13.1.1
Python: 3.10.4
Platform: macOS-13.4-arm64-arm-64bit

**Comment by mhils** [comment]
I guess you have an `__init__.py` file in src?

**Comment by HananInfiniGrow** [comment]
Well according to docs that's the way to add readme.md of the root level
root/readme root/src/__init__.py

**Comment by mhils** [comment]
This is not a pdoc bug, this is how Python packaging works – if you have a `__init__.py` in your root folder, that folder becomes the top-level package.
