### ISSUE TITLE
Add 1st line of docstring to submodule listing

### ISSUE THREAD

**Issue by patnr** [mitmproxy/pdoc#579]
#### Problem Description

Modules sometimes have cryptic names.

#### Proposal

It'd be nice to (as an option?) include a brief description of the submodule after its link in the index/listing.

The description should be taken from the 1st line of the submodule's docstring. [Example implementation](https://github.com/pdoc3/pdoc/blob/3ecfbcfb658c5be9ee6ab572b63db2cb5e1c29e1/pdoc/html_helpers.py#L48C1-L48C1)

**Comment by mhils** [comment]
I appreciate the suggestion, but that's not a feature I want to include into pdoc by default or as an option. You can probably do this with a custom template though. :)

**Comment by patnr** [comment]
Thanks for the prompt reply! Indeed I can do it by including this snippet in my custom `module.html.jinja2`:

```jinja2
    {% if module.submodules %}
        <h2>Submodules</h2>
        <ul>
            {% for m in module.submodules %}
            <li>{{ m.taken_from | link }}: {{ m.docstring.split('\n')[0] }}</li>
            {% endfor %}
        </ul>
    {% endif %}
```

But this does not work for `index.html.jinja2` which has no `module`. Do you have any idea how to circumvent this?

**Comment by mhils** [comment]
`all_modules` is a mapping from module name to `pdoc.doc.Module`. Without having tested it, you should be able to iterate over `all_modules.values()` in your template. :)

**Comment by patnr** [comment]
Thank you, worked like a charm!
