### ISSUE TITLE
Disable "Ancestors" for only Certain Classes

### ISSUE THREAD

**Issue by lgnashold** [mitmproxy/pdoc#595]
I am generating PDoc documents for a few enum classes. I do not want to include the "Ancestors (in MRO)" output for enum classes, since its clearly an enum. 

The recommended way to do this is: 
```
{% extends "default/module.html.jinja2" %}
{% block inherited_members scoped %}{% endblock %}
```
However, this would block all inherited members. I just want to block them for certain classes -- i.e., we don't need to display it if inherits from a built-in Python object. 

Is there an existing way to accomplish this?

**Comment by mhils** [comment]
This is a bit hacky, but you could use a custom template like this:
```jinja2
{% extends "default/module.html.jinja2" %}
{% macro inherited(doc) %}
  {% if "enum.Enum" not in doc.bases.__repr__() %}
    {{ default_inherited(doc) }}
  {% endif %}
{% endmacro %}
```
