### ISSUE TITLE
Docs do not explain how to further divide submodules

### ISSUE THREAD

**Issue by kg583** [mitmproxy/pdoc#596]
#### Problem Description
The generated docs found [here](https://ti-toolkit.github.io/tivars_lib_py/tivars/types.html) lop every file in the submodule into a single page, which is very cumbersome to read. It is possible to have `pdoc` not do this, as evidenced by [the Mephisto docs](https://mephisto.ai/python_api/mephisto.html). However, the user guide gives no indication on how to do this (or if its even default behavior or not), and manually inspecting the deployment config for Mephisto gives no light to the source of the difference either.

The only difference I can observe between the *code* that is being document is that Mephisto doesn't actually import anything into their `__init__.py`'s, and simply only specifying `__all__` (which I didn't even know was legal). If this difference is causing the described behavior, I would argue it should be changed. Otherwise, I would appreciate some closure on what _is_ causing the difference, and an update to the user guide if need be to reflect it.

**Comment by mhils** [comment]
In https://github.com/TI-Toolkit/tivars_lib_py/blob/main/tivars/types/__init__.py you explicitly import all members and expose them in the parent namespace as `__all__`. pdoc respects that. If you wouldn't do that, pdoc would document the individual submodules. Hope that helps!

**Comment by kg583** [comment]
Sure; that's done to make `from tivars import *` as convenient as possible. It then leads to an absolutely bloated doc page. Surely this should be configurable?

**Comment by mhils** [comment]
There is no configuration option for this. If you have more elaborate documentation needs, take a look at mkdocstrings or Sphinx! :)
