### ISSUE TITLE
Dynamic docstrings for variables

### ISSUE THREAD

**Issue by mdaeron** [mitmproxy/pdoc#597]
#### Problem Description

I'm writing a class (`Foo`) including some class variables (`Foo.bar`) which may be changed by the user but have a default value of `0.123`. Currently the doctring for `Foo.bar` is:

```
"`bar` (default: 0.123) does this or that."
```
This may cause problems later as I need to manually sync the default value and the docstring.

#### Proposal
I would like the option to use an "f-docstring" which would dynamically reflect the true default value:

```
f"`bar` (default: {Foo.bar}) does this or that."
```

#### Alternatives
Any other construct allowing to dynamically redefine variable docstrings would also solve the problem, but I couldn't find a way to achieve this currently.

**Comment by mhils** [comment]
From pdoc's end that would work fine, but since f-strings can have side effects they are only evaluated when the method runs and not assigned to `__doc__`. You can work around this by setting `__doc__` manually:

```python
def foo():
    pass

foo.__doc__ = f"The answer is {41 + 1}."
```

**Comment by mdaeron** [comment]
Excellent, thanks! I thought there might already be a way but couldn't figure it out.
