### ISSUE TITLE
Decorated class gets documented as a function

### ISSUE THREAD

**Issue by kmaasrud** [mitmproxy/pdoc#610]
#### Problem Description

I am using a decorator to reuse class instances based on arguments. The decorated is written like this:

```python
from functools import wraps

def singleton(cls):
    """
    Thread-safe singleton class decorator where uniqueness is based on arguments.
    """

    instances = {}

    @wraps(cls)
    def get_instance(*args, **kwargs):
        idx = (cls, tuple(args), tuple(kwargs.items()))

        # check-lock-check for fast thread-safety
        if idx not in instances:
            with lock:
                if idx not in instances:
                    instances[idx] = cls(*args, **kwargs)

        return instances[idx]

    return get_instance
```

I have taken care to use `functools.wraps`, as I've seen from other issues that that is necessary for pdoc to find the correct signature and docstrings. Here you can see an example usage of the decorator:

```python
@singleton
class SomeClass:
    """Some docstring"""

    some_attr: str
    """Some attribute docstring"""

    def __init__(self, some_attr: str):
        """Constructor docstring"""
        self.some_attr = some_attr
```

This produces the following doc entry:

<img width="803" alt="image" src="https://github.com/mitmproxy/pdoc/assets/54394333/a1274b8e-b4e0-44c0-bc29-f1969a5638b9">

and so you can see that the docstring is fetched correctly, but the fact that the item is a class is not---and thus the attributes/methods are not documented either.

#### System Information

```
pdoc: 14.0.0
Python: 3.9.17
Platform: macOS-13.4-arm64-arm-64bit
```

**Comment by mhils** [comment]
From the `functools.wraps`/`functools.update_wrapper` documentation (emphasis mine):

> Update a wrapper **_function_** to look like the wrapped **_function_**. 

The behavior here is about to be expected I think. Your decorator returns a function (and not a class), so SomeClass a function at runtime and gets documented as such.

From an API user point of view, this type of "singletonization" feels a bit unexpected. I'd recommend to just add an `get_instance(...)` `@classmethod` or so. Alternatively, you can probably do some shenanigans in `__new__`, but I really wouldn't recommend that.
