### ISSUE TITLE
Including a markdown file in a custom template and documentation of private functions

### ISSUE THREAD

**Issue by frytoli** [mitmproxy/pdoc#611]
Is there a way to include a markdown file in a custom index template?

I have a project with multiple, separated docker build modules and a custom pdoc index template that looks like this:
```
|-README.md
|-pdoc-template
|  |-index.html.jinja2
|-module1
|  |-build1
|  |  |-__init__.py
|  |  |-...
|-module2
|  |-build2
|  |  |-__init__.py
|  |  |-...
```
I'm attempting to include the top-level README in my custom `pdoc-template/index.html.jinja2` which looks like this:
```
{% extends "index.html.jinja2" %}
{% include "README.md" %}
```
And I'm generating docs with: `pdoc -t pdoc-template/ module1/build1/ module2/build2/`
However, I'm getting the error:
```
...
File "/Users/olivia/Code/Pipeline/venv/lib/python3.9/site-packages/pdoc/templates/default/module.html.jinja2", line 5, in block 'module_list_link'
    {% set parentmodule = ".".join(module.modulename.split(".")[:-1]) %}
  File "/Users/olivia/Code/Pipeline/venv/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'module' is undefined
```
I'm I doing something incorrectly? Is there a workaround for this?

Thank you in advance for your help!

**Comment by mhils** [comment]
Hi there, and sorry for missing this issue somehow!

The error you posted indicates an issue with your `module.html.jinja2` template, not so much `index.html.jinja2`. Do you have any customizations there as well?
