### ISSUE TITLE
How to generate all doc for the package test?

### ISSUE THREAD

**Issue by ray-sh** [mitmproxy/pdoc#62]
test
  **init**.py
  test1.py
  test2.py

I want to generate the python doc for the package test but the following command not work, anything wrong?
pdoc  --html  --html-dir /tmp/test/ --all-submodules  --overwrite   /test/

**Comment by BurntSushi** [comment]
Can you please provide more details? I can't help you unless you tell me what you've observed. When you run the `pdoc` command, what happens? Are no docs produced? Are docs produced but empty? Are docs produced but don't contain all items you expect to see?

I'd recommend reading the "Where does pdoc get documentation from?" section at http://pdoc.burntsushi.net/pdoc

**Comment by gvvka0327** [comment]
I tried this very scenario above, and same command

pdoc generated "test_support.m.html" file and when I open it, it has all wiered content apart from the two python modules test1.py and test2.py

not sure, if I need to use any other parameters in the command for it to work..

**Comment by mikecharles** [comment]
@gvvka0327 you need to provide a sample of the output produced or we'll have no idea what actually happened

**Comment by gvvka0327** [comment]
command uses: pdoc --html --html-dir test_docs --all-submodules --overwrite test
attached are few screenshots during this
![screenshot2](https://cloud.githubusercontent.com/assets/14827543/11047532/dc55e1f0-86e7-11e5-9fea-f2e8ad9810eb.png)
![screenshot1](https://cloud.githubusercontent.com/assets/14827543/11047533/dc5923ec-86e7-11e5-9954-20d7ef88db46.png)

 test,

**Comment by gvvka0327** [comment]
Hi Mike,

 I attached the screenshot of the output generated in github...  was
expecting documentation for test1.py and test2.py modules.. but instead got
some other output..

attaching here again...

[image: Inline image 1][image: Inline image 2]




Thank you,
Vijay

**Comment by gvvka0327** [comment]
I resolved this issue on my end, two things to take care of,
    - I need to define PYTHONPATH to the directory where this packages reside (export PYTHONPATH=/home/tests)
    - Start http server with --only-pypath set (pdoc --http --only-pypath)

**Comment by mikecharles** [comment]
Glad you fixed it @gvvka0327
