### ISSUE TITLE
[Failed method: `org.freedesktop.portal.Settings.Read` NotFound] -- Chrome freezes upon launching

### ISSUE THREAD

**Issue by joshiayush** [mitmproxy/pdoc#625]
#### Problem Description

Just like another day, I picked up my laptop, opened up my project, edited some of my docstrings but there was something new this time - a weird error - `[...object_proxy.cc] Failed method: org.freedesktop.portal.Settings.Read NotFound` and a never ending loading animation on the title bar with a blank screen.

Also, could someone please tell me how running `pdoc` results in an issue that is already referenced in https://github.com/google/mediapipe/issues/3017 because the following log kept me thinking for a while:

> INFO: Created TensorFlow Lite XNNPACK delegate for CPU

Although, there's a thread referencing the above issue but I did not want to loose my chrome profile so I did not use it! [thread](https://askubuntu.com/a/276466/1162343)

#### Steps to reproduce the behavior:

Believe me I still don't know what I did to invite the above issue! I just ran the `pdoc` command like I used to:

1. Changed the directory to the project's root directory
2. Activated the virtual environment
3. Ran the `pdoc` command

#### System Information

**pdoc:** 14.1.0
**Python:** 3.9.18
**Platform:** Linux-5.15.0-83-generic-x86_64-with-glibc2.31

Ask me for more clarity over the report :+1:

**Comment by joshiayush** [comment]
I posted the bug report after the issue got resolved itself. Again, just like before, I did not do anything but ran the `pdoc` command multiple times hoping that a fresh run might fix the issue and it seemed like it did.

**Comment by mhils** [comment]
This looks like a side effect from importing some Python modules. It's not a pdoc bug.

**Comment by joshiayush** [comment]
> This looks like a side effect from importing some Python modules. It's not a pdoc bug.

At the time of writing I'm using the following modules:

```
pdoc
numpy
pytest
bs4
```

and I'm really curious about knowing the culprit...
