### ISSUE TITLE
Trouble Documenting a Namespaced Package

### ISSUE THREAD

**Issue by aven-ghamut** [mitmproxy/pdoc#628]
### Problem Description
I have a package structure that includes namespaced sub-packages. Generating documentation for this project gives a lot of warnings and odd behavior. I'm not sure if these are bugs or if I'm doing something wrong - any pointers would be greatly appreciated!

### Steps to reproduce the behavior:
Here is my project structure, following the [guidelines](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) for constructing a namespaced package.
```
repository/
 ├── README.md
 ├── setup.py
 ├── my_package/  <-- my_package namespace
 │   └── sub_package_default/
 │       ├── __init__.py
 │       └── source_file.py
 ├── a/
 │   ├── README.md
 │   ├── setup.py
 │   └── my_package/  <-- my_package namespace
 │       └── sub_package_a/
 │           ├── __init__.py
 │           └── source_file.py
 └── b/
     ├── README.md
     ├── setup.py
     └── my_package/  <-- my_package namespace
         └── sub_package_b/
            ├── __init__.py
            └── source_file.py
```

In this structure, the package I am building is called `my_package`. When pip installed from github, it has a default sub-package, `my_package.sub_package_default`. Users can then optionally install the "extra" sub-packages, `my_package.sub_package_a` and `my_package.sub_package_b` using the square bracket syntax: `pip install "my_package[sub_package_a,sub_package_b]`.

Note that all the `__init__.py` files have an `__all__` directive listing items from their corresponding `source_file.py` that should be exposed and included in the documentation, which works as expected.

At this point, simply running `pdoc ./my_package` will only generate docs for `my_package.sub_package_default`, not capturing the two extra namespaced packages, which makes sense. In order to include those, I've found that I need to specify each one individually,
`pdoc ./my_package ./a/my_package ./b/my_package`, or pip install each sub-package locally. 

Both options work fine, generating the expected page shown below, albeit with a bunch of warnings of the form:
`The module specification './a/my_package' adds a module named my_package, but a module with this name has already been added. You may have accidentally repeated a module spec, or you are trying to document two modules with the same filename from two different directories, which does not work. Only one documentation page will be generated.`

![Screen Shot 2023-10-02 at 6 14 12 PM](https://github.com/mitmproxy/pdoc/assets/122910948/b5e8e9a5-de1f-49b8-a69a-69f7d1f49b6e)

I'd then like to add my README files, one at the top level package, and one at each sub-package. To start, if I add an `__init__.py` file at `repository/my_package/__init__.py` to include the README.md file with `.. include: ../README.md`, then running the pdoc command shown above results in the following image, now with an additional warning to those before:

` pdoc cannot load 'my_package' because a module with the same name is already imported in pdoc's Python process. pdoc will document the loaded module from <path_to_my_repo>/repository/my_package/__init__.py instead.`

![Screen Shot 2023-10-02 at 6 06 30 PM](https://github.com/mitmproxy/pdoc/assets/122910948/6e4e818d-5397-46b3-aeee-611d90b25ae1)

It seems that adding the `__init__.py` to include the markdown file prevents pdoc from getting to the other sub-packages somehow.

If I instead try to add the README.md files for each sub-package (adding the `.. include:: ../README.md` in the corresponding `__init__.py`), the sub-packages are properly included this time, but no markdown is shown at all.

### Summary

Notable behaviors described below:
- Generating the docs produces multiple warnings, even though results are expected.
- Cannot add an `__init__.py` file under main package namespace directory or all the namespaced sub-packages are ignored.
- Any included README.md files in the namespaced sub-packages aren't displayed at all.

Again, I may also be doing something wrong in which case I would appreciate some direction as to the correct way to achieve this.

Thanks!

### System Information
pdoc: 14.1.0
Python: 3.8.2
Platform: macOS-11.5.1-x86_64-i386-64bit

EDIT: spelling

**Comment by mhils** [comment]
When using namespace packages, you really want to invoke pdoc with module names and not with paths on the filesystem. I.e. do `pdoc foo.bar`, and not `pdoc ./foo/bar`.

**Comment by aven-ghamut** [comment]
> When using namespace packages, you really want to invoke pdoc with module names and not with paths on the filesystem. I.e. do `pdoc foo.bar`, and not `pdoc ./foo/bar`.

Hi - thanks for the (incredibly) fast reply!

I just tried this by first installing each sub-package locally, then calling `pdoc my_package`, which did correctly get the sub-packages, and also got rid of the warnings!

However, the issue persists where adding an `__init__.py` to the main namespace directory prevented pdoc from displaying the sub-packages, and this time without any warnings.

I also tried calling `pdoc my_package my_package.sub_package_a my_package.sub_package_b` with the same results.

**Comment by mhils** [comment]
> ModuleNotFoundError: my_package.sub_package_a

This indicates that you have a problem with your package setup, not so much a pdoc problem. If you can `import my_package.sub_package_b` in a Python interpreter, pdoc should be able to find that and document the submodules.

**Comment by aven-ghamut** [comment]
Ahh you're right - adding the `__init__.py` file also prevents `import my_package.sub_package_b` from working.

Given this, how can I add a markdown file to the landing page of the documentation?

**Comment by aven-ghamut** [comment]
To add onto my last comment, the python packaging user guide confirms that you shouldn't add the `__init__.py` file under the main namespace directory:

(from the [docs](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/))
```
setup.py
mynamespace/
    # No __init__.py here.
    subpackage_a/
        # Sub-packages have __init__.py.
        __init__.py
        module.py
```

Is there an alternative method of including markdown files in the generated HTML, since the `__init__.py` is not an option?

**Comment by mhils** [comment]
> Is there an alternative method of including markdown files in the generated HTML, since the __init__.py is not an option?

Not really. You could modify the template, but that's not very ergonomic...
