### ISSUE TITLE
allow non-alphabetical sorting in the sidebar 

### ISSUE THREAD

**Issue by fnrizzi** [mitmproxy/pdoc#630]
#### Problem Description

Looks like the sidebar has by default alphabetical sorting. 

#### Proposal
Allowing somehow to disable that

**Comment by mhils** [comment]
The sidebar sorts exactly like the page contents, that is in order of declaration in the Python file. What are you looking for?

**Comment by fnrizzi** [comment]
Thank you for the reply. 
I was referring to the submodules
These are alphabetical 


![image](https://github.com/mitmproxy/pdoc/assets/18708772/044dd3c6-1875-4e04-a566-a97ed498ba18)

**Comment by mhils** [comment]
How would you want them to be ordered?

**Comment by fnrizzi** [comment]
I would like to choose how to order them. for my case, alphabetical order does not make sense. There is a clear logical order , from basic to more advanced modules, so I would like to reflect that. 

I did try to customize the order by using the customization suggested and modifying the "submodules" jinja2 block but that did not work fully. Some submodules ended up with broken links. 

So I was just going to ask if there is a way or, if not, suggest to add such an option. I think in general it would be useful.

**Comment by mhils** [comment]
There is no way to customize the order at the moment, and I don't think that feature meets the bar of general applicability/usefulness unfortunately. Sorry!

**Comment by fnrizzi** [comment]
> I don't think that feature meets the bar of general applicability/usefulness unfortunately

I don't quite understand this. How is this feature not useful in general?

**Comment by fnrizzi** [comment]
if you don't want to support it, can you please at least point me to where in the pdoc source I can find the code that sorts the submodules in the sidebar?

**Comment by mhils** [comment]
Sure! The implementation is at https://github.com/mitmproxy/pdoc/blob/v14.1.0/pdoc/doc.py#L455. From a brief glance it looks like you may actually be able to add custom sorting by specifing `__all__`, so maybe that's a feature we actually have. :)

**Comment by fnrizzi** [comment]
it worked! https://github.com/Pressio/rom-tools-and-workflows/pull/30
