### ISSUE TITLE
Deploying pdoc to GH pages requires all dependencies

### ISSUE THREAD

**Issue by cwschilly** [mitmproxy/pdoc#634]
#### Problem Description
When deploying pdoc documentation to GitHub pages, why is it necessary to install all dependencies of a given library (since pdoc does not run code)? For example, in the [sample yaml](https://github.com/mitmproxy/pdoc/blob/main/.github/workflows/docs.yml):

```sh
# ADJUST THIS: install all dependencies (including pdoc)
- run: pip install -e .
# ADJUST THIS: build your documentation into docs/.
# We use a custom build script for pdoc itself, ideally you just run `pdoc -o docs/ ...` here.
- run: python docs/make.py
``` 

#### Steps to reproduce the behavior:
1. In above yaml, replace `pip install -e .` with `pip install pdoc`
2. Run the action -- it will fail because of missing dependencies

#### System Information
```
pdoc: 14.1.0
Python: 3.12.0
Platform: Linux-6.2.0-35-generic-x86_64-with-glibc2.35
```
@fnrizzi fyi

**Comment by mhils** [comment]
pdoc is heavily based on dynamic analysis, so pdoc needs to be able to import your code to inspect it. That typically requires your dependencies to be present. :)
