### ISSUE TITLE
Separate html page for each subsection inside `Contents`

### ISSUE THREAD

**Issue by joshiayush** [mitmproxy/pdoc#638]
#### Problem Description

The problem I'm struggling through right now is that the doc generated takes too long to load when the `Contents` is too long as everything is just bundled in the same page.

Also, clicking on the topics doesn't scroll through as the page is taking too long to load.

Check the contents here -> https://joshiayush.github.io/ai/ai.html

#### Proposal

Is there a way to serve the main sections of the contents in their own html pages just like for the `Submodules`. If there's already then please tell me because I can't find it in the docs.

**Comment by mhils** [comment]
Hi there! There does not exist any functionality to split individual modules into multiple pages, and such functionality is not planned. Sorry! :)

**Comment by cansik** [comment]
Would you be open for a PR about this or what is the reason for "not-planned"?

**Comment by mhils** [comment]
Splitting a single module into multiple pages is really at odds with pdoc's architecture right now. It's very unlikely that we can come up with a changeset here that I would be happy to merge. If you really want to split a single module's documentation across multiple pages, you're probably better off with Sphinx or mkdocstrings! :)
