### ISSUE TITLE
Markdown tables not rendered as tables

### ISSUE THREAD

**Issue by mikecharles** [mitmproxy/pdoc#64]
I'm using the following command:

```
pdoc test.py --html
```

to create an API doc for the following Python script:

``` python
#!/usr/bin/env python

def test():
    """
    Test function

    | Tables        | Are           | Cool  |
    | ------------- |:-------------:| -----:|
    | col 3 is      | right-aligned | $1600 |
    | col 2 is      | centered      |   $12 |
    | zebra stripes | are neat      |    $1 |
    """
    pass
```

 Here's the resulting HTML:

![issue](https://cloud.githubusercontent.com/assets/265620/9525492/5a1d03ae-4cb2-11e5-9ce8-c945ac461040.png)

Shouldn't pdoc handle any standard markdown syntax?

**Comment by mike-charles** [comment]
Sorry, nevermind, I didn't even realize tables were not a part of standard Markdown. Would it be easy to add it with [this](https://github.com/google/py-gfm)?

**Comment by BurntSushi** [comment]
I generally like Github's version of Markdown, so I wouldn't mind swapping what we have for that.

However, I think my strongest preference would be for CommonMark. Does that have tables?

**Comment by mike-charles** [comment]
Seems like [many people](http://talk.commonmark.org/t/tables-in-pure-markdown/81/84) don't think tables should even be part of the core spec for Markdown in version 1.0, so it's probably far off...

**Comment by robmoggach** [comment]
+1 for tables...

**Comment by cortesi** [comment]
Please see #153 for a unified discussion ticket about docstring flavors.
