### ISSUE TITLE
--link-prefix has no effect on links to other identifiers

### ISSUE THREAD

**Issue by mikecharles** [mitmproxy/pdoc#66]
When I use the `--link-prefix` option, all the links in the index, sub-modules list, etc. do have the link prefix, but links automatically generated from identifiers in backticks sit at the root of the server.

For example, if browse the documentation at www.example.com/example2, an identifier in the docstring like this:

``` python
"""
See `example1.file1`
"""
```

results in the link:

www.example.com/example1.file1.ext

These identifiers should have the same link prefix so that if you document multiple packages you can link to them.

**Comment by mhils** [comment]
Hi,

This should be fixed in the latest release, but please also note that the lastet release doesn't have `--link-prefix`. All interlinking URLs are relative now.
