### ISSUE TITLE
__pdoc_file_module__ is shown in documentation

### ISSUE THREAD

**Issue by cdown** [mitmproxy/pdoc#67]
![2015-09-19_231909_257213960](https://cloud.githubusercontent.com/assets/660663/9978415/f030b708-5f24-11e5-9fb2-46ac8b91742c.png)

I'm running `pdoc --html --html-dir /tmp/aur aur.py --html-no-source --overwrite` on this commit: https://github.com/cdown/aur/tree/cf715ac51c9542d5717da6b6570cbda76099e9b2

```
% pdoc --version
0.3.1
```

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. This should be fixed with the latest release. 😃

**Comment by cdown** [comment]
![](https://media0.giphy.com/media/PJoLp4gDIqjYs/giphy.gif)
