### ISSUE TITLE
add pre-commit support

### ISSUE THREAD

**Issue by MstWntd** [mitmproxy/pdoc#681]
#### Problem Description

Need to get this working with pre-commit

#### Proposal
create a .pre-commit-config.yaml file on root dir, fill it in with required config, you can use [this](https://github.com/pdoc3/pdoc/blob/master/.pre-commit-hooks.yaml) as an example.

**Comment by mhils** [comment]
I'm not too familiar with precommit, but happy to take a look at a PR! :)
