### ISSUE TITLE
A way to NOT inherit documentation for a specific class

### ISSUE THREAD

**Issue by stevenliebregt** [mitmproxy/pdoc#685]
First off, sorry, it's not a bug, rather a question

#### Problem Description
I'm generating documentation for classes based on Pydantic models, like:
```python
class MyClass(pydantic.BaseModel):
	"""Cool class"""

	file_id: int
    """Some cool prop"""
```
When I generate documentation for this I also see the following, which I'd like to hide for this specific class:
![image](https://github.com/mitmproxy/pdoc/assets/17197587/b9d8bd41-bfc5-42df-aa72-4f15de0f4a3f)

**Comment by mhils** [comment]
I don't have sample code, but generally speaking you can override `is_public` for the model_ attributes.

**Comment by stevenliebregt** [comment]
Where would I override that `is_public`? Is that a property on the attributes, I've been trying to hide those specifically but without any luck.

**Comment by 2justinmorgan** [comment]
@stevenliebregt this worked for me https://github.com/mitmproxy/pdoc/issues/15#issuecomment-1872614585

However, it only removed the "Inherited Members" portion of the html
![image](https://github.com/user-attachments/assets/90ccb5b8-1b55-4f6d-9f7e-fb564da0e46a)

**Comment by 2justinmorgan** [comment]
Since `is_public` is another macro like the macro `inherited` edited per https://github.com/mitmproxy/pdoc/issues/15#issuecomment-1872614585, you can redefine aka override it similarly in a template extension. Template extensions are exemplified here https://pdoc.dev/docs/pdoc.html#edit-pdocs-html-template
