### ISSUE TITLE
Including markdown is buggy and local images do not work

### ISSUE THREAD

**Issue by meghprkh** [mitmproxy/pdoc#691]
#### Problem Description

If you include a markdown and try to link a local image it does not work

#### Steps to reproduce the behavior:
1. Create `doc/img.png`
1. Create a `doc/include.md` with an image link `![img](./img.png)`
2. `.. include ../doc/include.md`
3. The image is a broken link
4. 4. It works if the link was `./doc/img.png` but that is incorrect markdown

#### System Information
Paste the output of "pdoc --version" here.
14.4.0

**Comment by mhils** [comment]
The logic for determining relative imports sits here: https://github.com/mitmproxy/pdoc/blob/1b36ea27abe9884c222b137d8132c3fb8c6af325/pdoc/docstrings.py#L376-L383

The `source_file` argument should be the path of the current Python file where the docstring is in. We may need an additional call to `embed_images` here, see further up in the file. I don't have the capacity to dive deeper, but PRs are welcome! 😃

**Comment by meghprkh** [comment]
IMO regex based workarounds are a very bad idea. I might create a patch to address the issue at hand.

While switching to an extensible commonmark compliant markdown parser is a big change, i will remove need of such hacks. [This link](https://github.com/commonmark/commonmark-spec/wiki/List-of-CommonMark-Implementations#python) lists some of them. Markdown-it is fairly extensible.

**Comment by mhils** [comment]
This is a matter of setting the relative path correctly, not a matter of regexes or the markdown engine we are using. :)

**Comment by meghprkh** [comment]
I have created #692. Its a minimal fix but should work for the meanwhile :)
