### ISSUE TITLE
PyPi upload of 14.5 seems to have failed

### ISSUE THREAD

**Issue by meghprkh** [mitmproxy/pdoc#693]
#### Problem Description

v14.5.0 is not on pypi https://pypi.org/project/pdoc/
From what I can see this failed https://github.com/mitmproxy/pdoc/actions/runs/9117938773/job/25070082002

Maybe re-running fixes it?

This is the most relevant issue I could find but dont think it is related? https://github.com/pypa/twine/issues/372

**Comment by mhils** [comment]
Thanks for the heads-up. This was an unintended side effect of a mhils/workflows update, should be fixed now.
