### ISSUE TITLE
Non-deterministic behavior with set literals

### ISSUE THREAD

**Issue by adollard-patreon** [mitmproxy/pdoc#694]
#### Problem Description
We have a `dataclass` with a `set` property. When we run `pdoc` on this code, the generated documentation includes a `<span>` element listing the values in the set. Unfortunately, the ordering of elements in the span changes every time we run `pdoc`, which makes it impossible to use as part of our pre-commit workflow.

Thanks for your help! pdoc is wonderful!

#### Steps to reproduce the behavior:
1. Create a python file with a top-level set literal containing several values
2. Run pdoc against the python file, and write the output to a new file
3. Run pdoc again, and observe that the order of the values has (most likely) changed

#### System Information
pdoc: 14.5.0
Python: 3.10.13
Platform: macOS-14.4.1-arm64-arm-64bit

**Comment by mhils** [comment]
Does setting the PYTHONHASHSEED environment variable fix this problem for you?

**Comment by adollard-patreon** [comment]
Looks like that worked. Thank you!
