### ISSUE TITLE
Set width on generated documentation

### ISSUE THREAD

**Issue by shner-elmo** [mitmproxy/pdoc#700]
#### Problem Description

Hello, firstly thank you for making this awesome project, its one of the simplest doc generator that produce nice documentation.
As you can see in the image attached below, the generated documentation uses less than half of the entire browser (I'm using a 16:9 FHD monitor), is there a way to make it larger (perhaps using 60-70% of the display)?

![image](https://github.com/mitmproxy/pdoc/assets/102916448/ae9a3707-f8d4-4b0d-88e0-59e26383bd20)

And btw it's not centered, so having an option that lets you configure how to align it would be nice as well.

#### Proposal

Make the width configurable along with the alignment (center, left, right)

**Comment by mhils** [comment]
You can accomplish this by modifying pdoc's HTML template:

https://pdoc.dev/docs/pdoc.html#edit-pdocs-html-template
https://github.com/mitmproxy/pdoc/blob/main/examples/custom-template/custom.css
