### ISSUE TITLE
Arbitrary documentation is generated for undocumented enum, with python 3.12

### ISSUE THREAD

**Issue by mfrigerio17** [mitmproxy/pdoc#701]
Hi,
With an undocumented enum like this

```
from enum import Enum

class MyEnum(Enum):
    one = 1,
    two = 2
```

pdoc 14.5.0 with python 3.12 generates html with some "default" documentation of a `Color` enum.

The same pdoc version with python 3.10 behaves as expected, i.e. the html docs do not say anything (besides "An enumeration").

Not a sever bug, a bit funny I would say :)

**Comment by mhils** [comment]
Thanks! Enums probably just need to be added here: https://github.com/mitmproxy/pdoc/blob/dea7fa02def9843a4c1ab6e37750aa1a60478140/pdoc/doc.py#L587-L598
