### ISSUE TITLE
Publish docs for multiple versions 

### ISSUE THREAD

**Issue by shner-elmo** [mitmproxy/pdoc#702]
Hey, was wondering if there any examples and if it's possible to publish the pdoc documentation for multiple versions of a package on GH pages.
Perhaps we can add a dropdown menu with the different versions?

**Comment by mhils** [comment]
That kind of feature is currently out of scope for pdoc. :)

**Comment by shner-elmo** [comment]
@mhils Is there a way that I can make sure all the generated `href` tags are pointing to:
`https://shner-elmo.github.io/repository/v1.0.1/index.html`
instead of:
`https://shner-elmo.github.io/repository/index.html`?

(this way I can generate the documentation multiple times: `pdoc -o docs/v1`, `pdoc -o docs/v2`, ... and let the user change URL for a different version)

**Comment by mhils** [comment]
AFAIK this does not work with GitHub Pages. You can do S3/... of course.

**Comment by shner-elmo** [comment]
If you publish GH pages from a branch it will simply upload everything inside the `docs` folder, so it should work.
I'll try it soon
