### ISSUE TITLE
Hidden values leak in search.js

### ISSUE THREAD

**Issue by aleneum** [mitmproxy/pdoc#706]
#### Problem Description
As discussed already in #621, some configuration and environment variable values should be omitted from the documentation. In my case I don't want my [pydantic-settings](https://docs.pydantic.dev/latest/concepts/pydantic_settings/) to appear with default values in the documentation. I can obfuscate critical values with `SecretStr` in the settings' object `__repr__` and can use the proposed workaround in #621 and use a custom jinja template. However, local path and other specific environment variables will be included in `search.js` even though they don't show up in the config documentation file.

#### Steps to reproduce the behavior:
1. create `config.py` in `mypackage` that loads environment variables from `.env`:
```python
from pydantic_settings import BaseSettings, SettingsConfigDict

class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        env_nested_delimiter="__",
    )
    
    app_name: str = "Awesome API"
    admin_email: str  # loaded from .env
    items_per_user: int = 50

my_global_settings: Settings = Settings()
```
2. Create a custom template `module.html.jinja2` in `./templates`:
```jinja2
{% extends "default/module.html.jinja2" %}

{% macro default_value(var) %}
    {% if var.modulename != "mypackage.config" %}
        {{ default_default_value(var) }}
    {% endif %}
{% endmacro %}
```
3. Create a `.env` in project root:
```dotenv
admin_email="dont_show@mail.com"
```
4. Create documentation `pdoc -t ./templates mypackage` from project root.
5. Output `mypackage/config.html` (okay):
<img width="603" alt="Screenshot 2024-07-01 at 18 31 33" src="https://github.com/mitmproxy/pdoc/assets/205986/6f7c696d-1742-45a4-aded-06eaa8d46416">

6. Output `search.js` (includes env values):
<img width="961" alt="Screenshot 2024-07-01 at 18 31 58" src="https://github.com/mitmproxy/pdoc/assets/205986/5c91b493-8a93-466c-b92c-7f4fa5c5235e">

#### System Information
Paste the output of "pdoc --version" here.
```
pdoc: 14.5.1
Python: 3.12.4
Platform: macOS-14.5-arm64-arm-64bit
```

**Comment by mhils** [comment]
Thanks for pointing this out! I've updated my advice in https://github.com/mitmproxy/pdoc/issues/621#issuecomment-1728496748, I think the best possible fix here for this customization is to use pdoc as a library.
