### ISSUE TITLE
Using Pdoc with PyO3

### ISSUE THREAD

**Issue by shner-elmo** [mitmproxy/pdoc#707]
#### Problem Description
Hey, so I'm trying to generate the docs for a [PyO3 library](https://github.com/shner-elmo/flashtext2/tree/pyo3), but idk how to include the README to the generated docs.

Usually I insert this in the `__init__.py`:
```
"""
.. include:: ../README.md
"""
```

But in this case I haven't defined the `__init__.py`, how can I include it? (using the `flashtext2.pyi` stub file)

#### System Information
pdoc: 14.5.1
Python: 3.11.4
Platform: Linux-6.5.0-41-generic-x86_64-with-glibc2.35

**Comment by mhils** [comment]
One option is to put it in the docstring of your module like this:
```rust
/// .. include:: ../README.md
#[pymodule]
pub fn your_module(py: Python, m: &Bound<'_, PyModule>) -> PyResult<()> {
    // ...
}
```

I don't know if relative paths work as expected, but generally speaking this is how it should work.

**Comment by shner-elmo** [comment]
Unfortunately that dosent work: 
```sh
Warn: Cannot include '../README.MD': [Errno 2] No such file or directory: '/home/shneor/Desktop/projects/python/personal/FlashText2.0/.venv/lib/python3.11/site-packages/flashtext2/../README.MD' (/home/shneor/Desktop/projects/python/personal/FlashText2.0/.venv/lib/python3.11/site-packages/pdoc/docstrings.py:413)
```
As the README isn't included here:
![image](https://github.com/mitmproxy/pdoc/assets/102916448/a33f0b92-c444-4070-a45e-e83d1d2c90a4)

Is there any other way I could do it?

**Comment by mhils** [comment]
You need to either include the README, or fiddle with the relative path. I'd suggest the former. :)

**Comment by shner-elmo** [comment]
How can I include it?

**Comment by mhils** [comment]
That's a Python packaging question, not a pdoc question.

(It depends on how you package - most things have some ways to include
arbitrary artifacts)
