### ISSUE TITLE
Option for monospace without linking.

### ISSUE THREAD

**Issue by SolidTux** [mitmproxy/pdoc#713]
#### Problem Description

I'm trying to typeset something in monospace that also by coincdence is a module name. This causes an automatic link to be generated even though the linked item is not meant. And example could be a shell command that has the same name as a module.

#### Proposal

Provide an option to disable automatic linking locally.

#### Alternatives

Not using monospace, but that would lead to inconsistencies.

**Comment by mhils** [comment]
We have the same problem in the pdoc documentation itself. You can achieve this as follows:

https://github.com/mitmproxy/pdoc/blob/8939754cbee82ad08b939bccfa7123d7bcb4fcc5/pdoc/__init__.py#L219-L220
