### ISSUE TITLE
When `@private` annotation is used to hide a member, it still appears in the 'View source' code extract.

### ISSUE THREAD

**Issue by elliot-100** [mitmproxy/pdoc#714]
#### Problem Description

[Docs](https://pdoc.dev/docs/pdoc.html#control-what-is-documented) says:
> If you want to override the default behavior for a particular item, you can do so by including an annotation in its docstring:
> `@private` hides an item unconditionally.

However I was surprised to find it still appears in the 'View source' code extract.

#### Steps to reproduce the behavior:

Create e.g. doc.py:
```python
"""Module docstring."""

MODULE_CONSTANT = "MODULE_CONSTANT"
"""@private member docstring."""

def my_func() -> None:
    """@private function docstring."""
    return None
```
2. Run `pdoc ./doc.py`
3. Generated `doc.html` doesn't initially show anything after 'Module docstring.', as expected. However if you open the 'View Source' dropdown, the entirety of the source is shown. 

#### System Information
```
pdoc: 14.5.1
Python: 3.10.11
Platform: Windows-10-10.0.22631-SP0
```

**Comment by elliot-100** [comment]
@aaronsteers it is not a Python decorator but an annotation in the docstring, and the example above does work for me in that it blocks generation of HTML text documentation for the constant and the function - but not in the source code snippet. I don't think it is intended to work for modules as there is separarate documentation on that.

Also to add `--no-show-source` does block generation of *all* source code snippets as expected.

**Comment by mhils** [comment]
> Generated doc.html doesn't initially show anything after 'Module docstring.', as expected. However if you open the 'View Source' dropdown, the entirety of the source is shown.

This is expected behavior, but I agree we can make it more clear in the documentation!

> Also to add `--no-show-source` does block generation of _all_ source code snippets as expected.

Can you clarify please?

**Comment by elliot-100** [comment]
Thanks @mhils - happy with a documentation amendment to make expected behaviour clear.

Re my comment on ```--no-show-source```: I was noting that it is possible to completely eliminate the item from the generated docs - at the expense of eliminating all source snippets. But that thought should have stayed in my head ... ;-)
