### ISSUE TITLE
`.__doc__` has no effect

### ISSUE THREAD

**Issue by savchenko** [mitmproxy/pdoc#722]
#### Problem Description
Setting `__doc__` on class instance has no effect.

#### Steps to reproduce the behavior:

```py
class Dog:
    """Woof"""

billy = Dog()
billy.__doc__ = "Bark!"
```
produces:
![image](https://github.com/user-attachments/assets/b1cc4b31-d35e-4ac2-9c58-df04603dee7e)
`billy`'s docstring is missing.

#### System Information
```
pdoc: 14.6.0
Python: 3.11.2
Platform: Linux-6.1.0-23-amd64-x86_64-with-glibc2.36
```

**Comment by mhils** [comment]
https://pdoc.dev/docs/pdoc.html#document-variables:

```python
class Dog:
    """Woof"""

billy = Dog()
"""Bark!"""
```
