### ISSUE TITLE
Support `#:` annotation

### ISSUE THREAD

**Issue by savchenko** [mitmproxy/pdoc#723]
#### Problem Description
Document variables in a compatible and terse way.

#### Proposal
Generate documentation from comments that start with `#:`

#### Alternatives
Triple-quote on a new line below the variable declaration. Which is rather confusing...

#### Additional context
This code:
```py
class Dog:
    """Woof"""

billy = Dog()  #: Barking dog
```

would generate:
![image](https://github.com/user-attachments/assets/746b818b-7dbb-4f43-8a4b-f6b6c1cf018a)

**Comment by mhils** [comment]
These comments don't show up in the AST, so this makes it exceptionally hard for pdoc to support them:

```python3
>>> import ast
>>> print(ast.dump(ast.parse('a = 1  #: Barking dog'), indent=4))
Module(
    body=[
        Assign(
            targets=[
                Name(id='a', ctx=Store())],
            value=Constant(value=1))],
    type_ignores=[])
```

Long story short, I'm sympathetic to the request, but this will be wontfix for now.

**Comment by mhils** [comment]
We're taking the contents of an entire Python file and parse it with `ast.parse`. There unfortunately is no place where we could easily call `.split()` or so.

**Comment by malthe** [comment]
From the AST you have the line no and that could be used to scan the specific line for a comment, extracting the annotation, similar to how typing tools would parse `# type: <annotation>` (somewhat deprecated now).

In addition, the preceding line(s) could also be used:
```python
class Dog:
    """Woof"""

#: Barking dog
billy = Dog()
```
