### ISSUE TITLE
Search Bar Yields No Results 

### ISSUE THREAD

**Issue by JLZ22** [mitmproxy/pdoc#724]
#### Problem Description
I am documenting a project, and typing anything into the search bar always yields no results. I am currently documenting three modules and not using any custom templates. You can find my current deployment [here](https://jlz22.github.io/Computer-Vision-for-FOD/index.html) (yes it is very very rough). I am running `pdoc -o docs/ src/[A-Z]*.py --no-show-source --footer-text "FOD Detection" --no-include-undocumented` in my Github Actions workflow when building. 

#### System Information
pdoc: 14.6.0
Python: 3.12.4
Platform: macOS-14.6-arm64-arm-64bit

**Comment by mhils** [comment]
This needs a minimal repro (or access to the source repository).

**Comment by JLZ22** [comment]
Sorry for not providing that in the initial bug report. I have narrowed down the issue to `--no-include-undocumented`. When I have that flag, all searches yield "No Search results for '[your query]'". However, when I do not have this flag, the search works fine. 
<img width="1820" alt="image" src="https://github.com/user-attachments/assets/5b01d7ed-d984-4927-99e8-e43df7d484ea">

<img width="1848" alt="image" src="https://github.com/user-attachments/assets/0c0ab72b-0c40-443a-a5ee-a8bca8cbf162">
 
<img width="643" alt="image" src="https://github.com/user-attachments/assets/5a103c8a-4249-4390-9c46-709a60907193">

**Comment by mhils** [comment]
Again, this needs a minimal repro. `pdoc --no-include-undocumented pdoc` works as expected, including search.

**Comment by JLZ22** [comment]
[Here](https://github.com/JLZ22/pdoc-search-issue-repro) is a repository that I made to demonstrate the issue. I hope this is a sufficient example. Apologies for the delay.

**Comment by mhils** [comment]
This made it easy to track down, thanks.
