### ISSUE TITLE
How to inlude HTML file

### ISSUE THREAD

**Issue by shner-elmo** [mitmproxy/pdoc#727]
#### Problem Description

Hey, I'm trying to include my own HTML files to the docs.

I saw the section in the docs about extending `module.html.jinja2` to add files to the navbar, and I'm able to link the raw HTML by adding an `href`...
The issue is that once you click on that href, there is no way to click back to the modules.

So my question is, how can I include the navbar in my HTML files?

#### Proposal
Perhaps we can add a function that you pass to it a list of all modules, it generates the navbar, and then you can include that in your own HTML files.

#### Additional context
I have a workflow that generates these HTML files every day (very big files with lists of values you can pass to an API), and want to be able to fit them nicely with the rest of the documentation (the actual docstrings)

**Comment by mhils** [comment]
#683 may have what you need, beyond that this is out of scope for pdoc. :)
