### ISSUE TITLE
Support for markdown reference-style links / link reference?

### ISSUE THREAD

**Issue by rudymatela** [mitmproxy/pdoc#738]
Is there support for reference-style links in pdoc?  If not, can these be added?

Consider the following minimal Python library `example.py`:

```py
#!/usr/bin/env python
"""
This is an example lib in [Python](https://python.org).

This is an example lib in [Python].

[Python]: https://python.org
"""

def hello():
    """
    This function prints Hello, World!
    """
    print("Hello, World!")
```

One can generate documentation for the above library with the following command:

```bash
$ pdoc example.py -o docs
```

The documentation is generated successfully at `docs/index.html`.  However, only the first link is rendered properly as a link to the Python website: "[Python](https://python.org)".  The second is literally rendered as "`[Python]`".  Please see the screenshot below.

![example](https://github.com/user-attachments/assets/1290388b-0e34-4b55-80e3-d634bb7b3318)

Is there a flag that I can pass to `pdoc` so that the second link is generated properly?  :thinking: :thought_balloon:   If not, can support for this be added?

Or maybe this is already supported but I found a bug?  :thinking: :lady_beetle: 

#### Further info

```bash
$ python --version
Python 3.12.4

$ pdoc --version
pdoc: 14.5.1
Python: 3.12.4
Platform: Linux-6.10.4-arch2-1-x86_64-with-glibc2.40
```

Btw, I find that pdoc is really nice and easy to use.  Thanks for providing it!  Much appreciated!   :smile:

**Comment by AmrElabbasy** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by mhils** [comment]
See https://pdoc.dev/docs/pdoc.html#markdown-support. Feature support is solely determined by markdown2. :)

**Comment by rudymatela** [comment]
@mhils Thanks for the prompt reply.

FYI, I actually reported this back to markdown2: https://github.com/trentm/python-markdown2/issues/597

Upon writing my report there, I discovered that `[Python]` is not "standard" markdown for links.  This is absent from the [syntax specification](https://daringfireball.net/projects/markdown/syntax#link).

However, one can get the same behaviour with `[Python][]`.  I tried that on `pdoc` and it renders correctly as:

> This is a link to the [Python][] website.

[Python]: https://python.org

... and that's exactly what I wanted from the outset!  :grin:

Thanks again.  :-)
