### ISSUE TITLE
Expanding an existing object with documentation fails

### ISSUE THREAD

**Issue by nxtlo** [mitmproxy/pdoc#744]
#### Problem Description
I'm trying to append a message with a decorator to an object `(class, method, function)`, but pdoc doesn't generate code for it.

#### Steps to reproduce the behavior:
take a look at this example

```py
def expand(text: str, /):
    """Expands `text` to a callable object's documentation."""
    def decorator(f):
        @functools.wraps(f)
        def wrapper(*args, **kwargs):
            return f(*args, **kwargs)

        m = f"# Exapanded\n" + text
        if wrapper.__doc__:
            # append a message to the existing docs
            wrapper.__doc__ += "\n"
            wrapper.__doc__ += m
        else:
            wrapper.__doc__ = m

        return wrapper

    return decorator

@expand("hint 1")
def func1():
    pass

@expand("hint 2")
def func2():
    """does something"""

print(func1.__doc__)
print(func2.__doc__)
```

The result for the print calls

```
# Expanded
hint 1
```
```
does something

# Expanded
hint 1
```
As we can see, Python does indeed append the `text` to the function's docs, but when pdoc generates it, it doesn't, what is preventing `text` from being appended to the existing documentation?

#### System Information
pdoc: 14.5.0
Python: 3.12.3
Platform: Windows-11-10.0.22631-SP0

**Comment by nxtlo** [comment]
I also tested something simpler, which resulted in working correctly.

```py
def unused(fn):
    """mark a function as unused."""
    m = "\n# Warning⚠️\nThis function is unused\n"
    if fn.__doc__:
        # append this message to an existing document.
        fn.__doc__ = inspect.cleandoc(fn.__doc__) + m
    else:
        fn.__doc__ = m

    return fn

@unused
def bleh():
    """..."""
# does indeed append a message
```

**Comment by nxtlo** [comment]
An image for proof

![image](https://github.com/user-attachments/assets/981bc39f-de37-4126-8e2c-59d1681df984)

**Comment by mhils** [comment]
This is a bit confusing, but working as intended. If pdoc detects that a function is wrapped by a decorator, it gets the docstring for the original method (and not for the wrapped method). This is because a lot of decorators (also in stdlib) have their own custom docstrings, which would otherwise mask the original function's docstring.

You can make this working by changing `f` instead of the wrapper:

```python
def expand(text: str, /):
    """Expands `text` to a callable object's documentation."""
    def decorator(f):
        @functools.wraps(f)
        def wrapper(*args, **kwargs):
            return f(*args, **kwargs)

        m = f"# Exapanded\n" + text
        if f.__doc__:
            # append a message to the existing docs
            f.__doc__ += "\n"
            f.__doc__ += m
        else:
            f.__doc__ = m

        return wrapper

    return decorator
```
