### ISSUE TITLE
pdoc does not document imported variables

### ISSUE THREAD

**Issue by sawatts** [mitmproxy/pdoc#752]
#### Problem Description

After much head scratching, we determine that **pdoc** does not publish documentation for a **variable** imported from another module.  This may be by design, but isn't mentioned in the **pdoc** documentation.

Our use case is that the variable is an instance of a callable class, but is presented as a function in the public API.  ...for reasons.

#### Steps to reproduce the behavior:
1.  Module `foo/bar.py` includes a variable with following documentation, which is included in its `__all__` list.
    ```py
    # foo/bar.py
    __all__ = [ 'barvar', ]
    barvar = 123
    '''Documentation for barvar...'''
    ```
2.  Module `foo/__init__.py` imports the variable and re-exports it in its `__all__` declaration:
    ```py
    # foo/__init__.py
    from .bar import barvar
    __all__ = [ 'barvar', ]
    ```
3.  Generate documentation for this source tree.

**Expected:**
> The documentation for `barvar` is included on the page for module "foo".

**Actual:**
> The variable `barvar` is listed, but not its documentation.

#### System Information

```
pdoc: 15.0.0
Python: 3.9.20
Platform: Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.17
```

#### Workaround

In our case, I exported the callable class to the `__init__.py` and create and document the variable there.  This is not desirable, as it does not scale; and fundamentally, a documentation system should not require changes to the runtime implementation.

**Comment by mhils** [comment]
This behavior is documented in https://pdoc.dev/docs/pdoc.html#document-variables. pdoc fundamentally relies on dynamic analysis, and that information is not available there.

(I agree that it would be really nice to have - just really hard to implement without massive scope creep)

**Comment by sawatts** [comment]
In our use-case, the "variable" was actually a complex generated function, while the generator is private.
