### ISSUE TITLE
Option to exclude certain parts of input files from being parsed by pdoc

### ISSUE THREAD

**Issue by dingetje** [mitmproxy/pdoc#756]
#### Problem Description

I'm trying to use pdoc on IronPython source code. Obviously pdoc doesn't understand some of the keywords in the source files. However, there seems to be no way to tell pdoc to skip those section an treat it like comment or skip it altogether.

#### Proposal
Copilot suggested that:

``` 
# pdoc exclude start
bla 
bla
# pdoc exclude end
```

could work, but it doesn't.

#### Alternatives
I've tried to import the offending code in another module and exclude that using:
```
# Exclude the entire module from pdoc
__pdoc__ = {}
__pdoc__['excluded_imports'] = False
```
but that too didn't work.

Currently the only workaround is to comment out the offending lines, run pdoc, and uncomment them again.

**Comment by mhils** [comment]
I don't have any experience with IronPython, but pdoc fundamentally needs to be able to import your source code. Everything else is out of scope for the project. So you need to come up with some hacks in your code, or look at other documentation generators.

**Comment by dingetje** [comment]
sounds like an easy enough feature to add some markers to exclude certain parts of a source file for being parsed. But I'm not a python nor a pdoc expert.

**Comment by mhils** [comment]
> sounds like an easy enough feature to add some markers to exclude certain parts of a source file for being parsed

Not really, because we would need to modify Python's entire import machinery. It's out of scope for us, sorry!
