### ISSUE TITLE
Docs: https://pdoc.dev/ link to Google usage example is outdated

### ISSUE THREAD

**Issue by elliot-100** [mitmproxy/pdoc#759]
#### Problem Description
https://google.github.io/or-tools/ gives 404; appears to have moved to https://or-tools.github.io/docs/pdoc/ortools.html

#### Steps to reproduce the behavior:
1. Go to https://pdoc.dev/
2. Click Google logo near foot of page

(It looks like the Apache one may also be outdated, as clicking around I could only find  https://pulsar.apache.org/api/python/3.5.x/ and https://pulsar.apache.org/api/python/3.0.x/ which seem to use pydoctor?)

#### System Information
Not applicable, docs only

**Comment by elliot-100** [comment]
PS: I did try to submit a PR, but after installing OK as per `CONTRIBUTING.md`, and amending `docs/index.html.jinja2`, I ran `make.py` as per `docs/README.md` with no errors, but it did not build `index.html`.

**Comment by mhils** [comment]
Please do send a PR, CI will take of building. :)

**Comment by elliot-100** [comment]
Thanks - raised #760.

(After updating a few packages in my environment, I did eventually get output which implied I had been hitting memory issues when building the search index.)

**Comment by mhils** [comment]
Thanks again!
