### ISSUE TITLE
Documentation for methods with @MethodName decorator

### ISSUE THREAD

**Issue by gvvka0327** [mitmproxy/pdoc#76]
I have a class with staticmethods and methods with @MethodName decorator

staticmethods with @staticmethod decorator got documented but other methods got skipped... does pdoc handle methods with @MethodName differently, for example,

   @MethodName
    def to_tab_delimited(self, output):
        """Reformats columnar output from pxssh session to be tab-delimited
      """"

This method got skipped, and consistently in other modules as well, all methods with @MethodName decorator got skipped... anything I need to take care of ...

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. This should be fixed with the latest release. 😃
