### ISSUE TITLE
document a folder with several .py files

### ISSUE THREAD

**Issue by EliosMolina** [mitmproxy/pdoc#79]
I have a folder with several .py scripts (no **init**.py file). I get a nice web documentation using:

$ PYTHONPATH=$dir pdoc --http --only-pypath

But I don't know how to save it into html files. Is there anyway to do it?

Thanks.

**Comment by gvvka0327** [comment]
pdoc generates html files and is saving them under /tmp/pdoc-2.7 folder... thatz what happened on my end...
do you have any idea if I want to only generate html files for the folder and not publish on HTTP server

**Comment by mikecharles** [comment]
If you run `pdoc --help` you'll see there's a `--html-dir` option for just that. Is that what you mean?

**Comment by gvvka0327** [comment]
Getting error,

NameError: name '__all__' is not defined

do we need to specify __all__ in __init__.py file..

-Vijay

**Comment by mikecharles** [comment]
Which method did you try?

**Comment by gvvka0327** [comment]
PYTHONPATH=$dir/.. pdoc --html-dir=./api_folder --html --only-pypath $dir
ReTried this approach and it worked... thank you.

**Comment by mikecharles** [comment]
Glad it worked!
