### ISSUE TITLE
Import Error if module is not defined in this environment

### ISSUE THREAD

**Issue by pyatil** [mitmproxy/pdoc#8]
test.py:

import fooooooo
#### 

Traceback (most recent call last):
  File "C:\Python27\Scripts\pdoc", line 454, in <module>
    module = imp.load_source('**pdoc_file_module**', fp, f)
  File "User\work\test.py", line 17, in <module>
    import bdf
ImportError: No module named fooooooo
#### 

My project works in an environment who constructs python module dynamically. I can't use pdoc in this environment. How can I ignore this module and continue generate docs?

Thx for the help.

**Comment by ryneeverett** [comment]
> There are no plans to change this. (It would require parsing the Python AST manually.)

Perhaps that would be prohibitively difficult but it seems like the tool would be a lot more robust if you didn't have to worry about import side-effects. For instance any django project would currently have to write a wrapper script to handle `DJANGO_SETTINGS_MODULE`.

**Comment by BurntSushi** [comment]
@ryneeverett No, really, it's a non-starter. I totally agree that what you're describing would be awesome, but it would literally require a ground up rewrite. This means `pdoc` is not the project for that. It should be a new project.

**Comment by BurntSushi** [comment]
@ryneeverett It's also probably one or two orders of magnitude harder to do.

**Comment by BurntSushi** [comment]
@ryneeverett On top of all of that, it's really hard (for me personally) to justify that kind of effort to work around non-idiomatic Python code (which shouldn't have nasty import side effects).

**Comment by TheCherry** [comment]
Have at the moment the same problem.
Did write a large application, that application use the vbox api.
There is at the moment no way to document my software, course he tell me every time:
```Exception ImportError: 'No module named xpcom' in <bound method VirtualBoxManager.__del__ of <vboxapi.VirtualBoxManager object at 0x7fd3266d1b10>> ignored```
I see noway to ignore that import and create a documentation, that is required for our customer.
Pydoc have exactly the same problem ...

**Comment by hammad93** [comment]
Would you be able to write a flag that simply ignores all import errors?
