### ISSUE TITLE
find a better way to get module descriptions

### ISSUE THREAD

**Issue by BurntSushi** [mitmproxy/pdoc#9]
As pointed out in #7, [importlib.abc.InspectLoader](https://docs.python.org/3/library/importlib.html#importlib.abc.InspectLoader) should be used to load the source code to get a module description from a module loader. But this appears to only be available in Python 3, so its implementation should fail gracefully in Python 2. (i.e., Return an empty string.)

**Comment by mhils** [comment]
This is fixed. :)
