### ISSUE TITLE
Is it possible to remove author's information at the bottom of the produced documentation? 

### ISSUE THREAD

**Issue by nbro** [mitmproxy/pdoc#92]
Is it possible to remove author's information at the bottom of the produced documentation?  I mean, that might depend on the license of `pdoc`, but I think it's not interesting to show in every page the author of `pdoc`, with all respect and gratitude for what he's made, which is amazing.

Note that I am not asking how to manually do it, but if it's possible according to pdoc's license or not.

**Comment by BurntSushi** [comment]
`pdoc` is licensed under the [UNLICENSE](https://github.com/BurntSushi/pdoc/blob/master/UNLICENSE), which is a dedication to the public domain with a fallback for regions that have crazy laws prohibiting such debauchery. So legally, if the license works, then you can do anything you want with `pdoc`, up to and including re-releasing it and claiming that you wrote it.

Are you referring to "Design by Kailash Nadh"? If so, I might indeed consider removing that. Kailash is not the author of `pdoc` but is the author of the beautiful display. It doesn't seem quite right to prioritize his name over everyone else who has contributed, so I'd personally prefer removing it. @knadh, what do you think?

**Comment by knadh** [comment]
I agree. The name needn't be there.
