### ISSUE TITLE
Possible bug: HTML code in the source code rendered is not displayed but rendered

### ISSUE THREAD

**Issue by nbro** [mitmproxy/pdoc#93]
I wanted to use Latex math notation to write simple formulas in the docstrings, etc, but since I discovered it's still not possible to do it, and I am not even sure if you plan to add this feature, I decided to use plain HTML for example to render powers or subscripts, etc. 

What I noticed is that in the source code of the function in the produced documentation, subscripts and superscripts produced with HTML code are rendered, instead of the HTML code to produce them being displayed, since the source code should actually show the real source code, I guess. Is this a bug or something that you wanted to achieve for some reason, or maybe you simply didn't think about it?

Here's an example

<img width="688" alt="screen shot 2016-02-03 at 21 19 50" src="https://cloud.githubusercontent.com/assets/9349000/12795822/355ca3fc-cabc-11e5-8b58-b9aaec2e50bf.png">

**Comment by BurntSushi** [comment]
Yup, that sounds like a bug to me!

**Comment by mhils** [comment]
Thanks for reporting and sorry for the slow turnaround time. This should be fixed with the latest release. 😃
